### ISSUE TITLE
Boinc client can't run in ipv6

### ISSUE THREAD

**Issue by talregev** [BOINC/boinc#3659] opened 2020-04-29 19:12 UTC
**Describe the bug**

**Steps To Reproduce**
1. change your internet to ipv6 protocol 
2. connect to projects.

**Expected behavior**
Boinc client will connect to projects

**Screenshots**

**System Information**
 - OS: Windows 10 64bit
 - BOINC Version:  7.16.5

**Additional context**

My country will go to phase in July 2020 that all internet provider in my country will switch to ipv6.
They also allow for ipv4.
In July 2021 I will not able to connect via ipv4.

You are in develop  a new client version 8, also for android. and new server version 1.2.
Please include connection via ipv6.
Thank you.

**Comment by AenBleidd** [comment] 2020-04-29 19:15
Just curious, which country?

**Comment by talregev** [comment] 2020-04-29 19:15
Israel.

**Comment by AenBleidd** [comment] 2020-04-29 19:18
Ok, I see. I heard no statements about this for any country. 
There is no plans to support IPv6 yet, so if you can contribute - that would be really great

**Comment by talregev** [comment] 2020-04-29 19:20
I can send you articles in hebrew about this statement.

**Comment by talregev** [comment] 2020-04-29 19:24
Not sure how to switch boinc to ipv6.  It not an easy task and I am not an expert in this.

**Comment by AenBleidd** [comment] 2020-04-29 19:39
Yes, it's not an easy task. But, I suppose, also not so hard as it looks like because basically everything is already implemented in openSSL and curl.

**Comment by talregev** [comment] 2020-04-29 19:46
Greate! you understand in it? You can guide me?

**Comment by AenBleidd** [comment] 2020-04-29 20:04
Not really 😄 I just working with related stuff. But I can try to help you if I can.

**Comment by talregev** [comment] 2020-04-29 20:17
I want to do one feature in android, then I will think how to switch to IPv6.

**Comment by AenBleidd** [comment] 2020-04-29 20:28
Android will have big changes soon. So if you want to make some changes - it's better to ask me first. Just not to do unnededwork

**Comment by AenBleidd** [comment] 2020-04-29 20:28
Let's discuss this in discord: Vitalii Koshura#0794

**Comment by talregev** [comment] 2020-04-29 20:48
> Vitalii Koshura#0794

Not sure how to contact you.

**Comment by AenBleidd** [comment] 2020-04-29 20:51
Here: https://discord.gg/wPRafUq

**Comment by sirzooro** [comment] 2020-04-30 21:24
Most of the work probably will be related to code which expects that IP address has 4 bytes or X.X.X.X format. Some changes also will be needed for socket creation. Here are some helpful documents how to support both IP versions in the app:
[Implementing AF-independent application](http://www.kame.net/newsletter/19980604/)
[Porting applications to IPv6 HowTo](http://long.ccaba.upc.edu/long/045Guidelines/eva/ipv6.html)

**Comment by davidpanderson** [comment] 2020-04-30 21:40
BOINC uses Curl for all network communication except GUI/client RPCs.

**Comment by talregev** [comment] 2020-09-27 00:06
My Issue is duplicate with this issue:
https://github.com/BOINC/boinc/issues/539

I also can change this issue that android client (app) will need to support ipv6.

**Comment by AenBleidd** [comment] 2020-09-27 08:51
Closed as a duplicate of #539

**Closed by AenBleidd** 2020-09-27 08:51 UTC
Labels: C: Client - Daemon, P: Minor, R: duplicate, Newbie
