### ISSUE TITLE
When putting Event Log on second monitor, after closing and reopening BOINC Manager, it's back at first monitor

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#3942] opened 2020-07-22 22:18 UTC
When I put the Event Log on my secondary monitor, then close BOINC Manager and reopen it, it will open the Event Log on my primary monitor, behind the open BOINC Manager window. 
When I move BOINC Manager to my secondary monitor, then close it there and reopen it, it opens on my primary monitor. 

Shouldn't it remember that these were on the secondary monitor?
XPos and YPos do change, for instance 0xfffff643 and 0x35b, but after reopening BOINC Manager they're at 0x30 and 0x35b. At least the YPos is kept. Event Log will go for instance from 0xfffff61a and 0x2f8 to 0x0 and 0x2f8

I'm using Extended displays in Windows 10. 
Doesn't BOINC know about positions 0xffffxxx?

**Comment by AenBleidd** [comment] 2020-07-22 22:37
Closing as a duplicate of #2219

**Closed by AenBleidd** 2020-07-22 22:37 UTC
Labels: C: Manager, P: Minor, R: duplicate, E: to be determined
