### ISSUE TITLE
Windows boinc pause tray icon disappears when context menu is opened

### ISSUE THREAD

**Issue by informatorius** [BOINC/boinc#1419] opened 2015-10-25 11:35 UTC
On Windows 7 when I pause Boinc 7.6.9 then the tray icon gets a pause icon added.
![pausetrayicon](https://cloud.githubusercontent.com/assets/6989214/10715374/c0926792-7b14-11e5-9978-5f4570731b02.PNG)
When I open the tray icon context menu again then the pause icon disappears.
![pausetrayicondisappearsonopencontextmenu](https://cloud.githubusercontent.com/assets/6989214/10715376/c819ced8-7b14-11e5-8db4-165bad54cecc.png)

After closing context menu it takes 30 seconds until the pause icon shows again.

Expected behavior: the pause icon stays shown until Boinc is unpaused.

**Comment by AenBleidd** [comment] 2015-10-27 14:44
I can confirm this. But in my case icon is restored during ~1 second. I'll take a look at this issue this week.

**Comment by informatorius** [comment] 2015-10-27 17:20
Today I also only see the 1 second flickering.
Maybe it depends on the work unit type.

**Comment by AenBleidd** [comment] 2015-10-28 00:49
Fixed in https://github.com/BOINC/boinc/pull/1422

**Comment by informatorius** [comment] 2015-10-29 10:12
Thanks!

**Comment by mustafaxub** [comment] 2015-10-29 11:12
Who cares Windows. Why you don't install Ubuntu and your graphic vendor's proprietary drivers. And you won't see these... If you interested how you can compile BOINC 7.6.9 for Ubuntu, read this: https://xubuntutimelinux.wordpress.com/2015/10/28/compiling-boinc-7-6-9-on-xubuntu/

**Comment by AenBleidd** [comment] 2015-10-29 11:33
mustafaxub, it's very tactlessly as for me. Some people use Windows because they like this system more than Linux. Some other people have to use Windows because of some business utilities or application which are Windows only.

**Comment by AenBleidd** [comment] 2015-10-29 11:34
informatorius, I think you close this issue too fast because my pull request isn't merged and not tested yet.

**Comment by mustafaxub** [comment] 2015-10-29 11:57
AenBleidd, sorry it is my idea. BOINC is open source project, and Linux is open source project also Xubuntu too. I am just carrying freedom or open source / free software. Sorry don't need to insist. But, I like Linux more than windows. In the future I have to use Linux for business utilities or application which are Linux only. ( Octave and also some business projects like Inkscape/GIMP/Blender/Apache/GnuCash/Openstack/...).If you need to run a secure server/fast clusters you have to use Linux, like RedHat Linux/SUSE/Ubuntu(Canonical)... So it's in your hand. BOINC is started for Linux and open source (I guess ). If you like BOINC and If you support it. You may be change your idea with open source OS(es) like Linux as helping BOINC projects. Sorry I guess I am self-assertive/one-way/insistent. Sorry, Don't call my post as tactlessly... Thanks for your time. I hope your bug fixed, too.

**Comment by ChristianBeer** [comment] 2015-10-29 12:14
@mustafaxub: Please don't start off-topic discussions in an issue. Your comment has nothing to do with the subject.

@informatorius: I reopened the issue because the fix is not confirmed. Please only close if the issue is resolved.

**Comment by mustafaxub** [comment] 2015-10-29 12:16
@ChristianBeer you reopened this issue again. So, should I erase my post(s) or I have to stop answering which is a comment to my post(s)

**Closed** 2017-04-11 14:57 UTC
Labels: C: Manager, P: Minor, T: Defect
