### ISSUE TITLE
Close to menu bar on MacOS

### ISSUE THREAD

**Issue by cazzzac** [BOINC/boinc#5520] opened 2024-02-16 12:00 UTC
**Describe the problem**
BOINC currently minimises to both the menu bar and the Dock.

**Describe the solution you'd like**
It'd be great to have a setting that lets you minimise just to the menu bar to keep the Dock clear of background tasks. 

**Additional context**

**Comment by AenBleidd** [comment] 2024-02-16 12:19
Closing as a duplicate of #1424

**Closed by AenBleidd** 2024-02-16 12:19 UTC
Labels: R: wontfix, T: Task, C: Manager - Macintosh

**Comment by eprillios** [comment] 2024-03-09 18:26
I don't agree that this issue is a duplicate of #1424. Currently, BOINC on Mac resides in _both_ the Dock and the system menu bar. This is rather superfluous and provides an inconsistent user interface.

A lot (if not nearly all) of stay-resident Mac applications (including password management, cloud synchronization and disk monitoring software) only reside in the menu bar, so the BOINC Manager should provide a consistent user interface by following this standard behaviour.

**Comment by CharlieFenton** [comment] 2024-03-10 00:14
As you can see from #1424, a very small number of people want it only in the Dock, and you want it only in the menu bar. Most people are happy to have it in both. Just because a number of other applications do it the way you say does not make it "standard behavior." 

As BOINC is maintained only by volunteers, we have very limited resources, and even if we agreed with our request, it would be so low on the priority list that it would never be done.
