### ISSUE TITLE
Manager unresponsive when remotely connected to old clients

### ISSUE THREAD

**Issue by CharlieFenton** [BOINC/boinc#1909] opened 2017-05-09 01:05 UTC
Please see [this forum post](https://boinc.berkeley.edu/dev/forum_thread.php?id=11607)

The poster to the forum wrote that the problem occurs in BOINC Manager version 7.6.20 and later, but not in 7.6.18. since I had saved the source trees for versions 7.6.18 and 7.6.21, I compared these and found the following differences which would affect the manager:

in clientgui/BOINCGUIApp.cpp, .h: 
 *  added call to wxhandleFatalExceptions() in CBOINCGUIApp::OnInit()
 *  added new OnFatalException() method

in lib/gui_rpc_client_ops.cpp, .h:
*  added support for "platform" entry in RESULT::parse()
*  added result->platform argument to lookup)app_version() call in CC_STATE::parse()
*  added support for "platform" entry in CC_STATE::lookup_app_version()

I suspect the changes in gui_rpc_client_ops.cpp may be the problem, since (I presume) the older remote clients he is trying to manage don't have this field and I don't see any provision in the newer RPC code to deal with this situation.

**Comment by ChristianBeer** [comment] 2017-05-09 07:07
We are using git so everyone has the complete source tree and thanks to the work by the poster it is now fairly easy to pinpoint the commit that most likely introduced this:
localy: `git log --pretty=format:"%h : %s" --graph client_release/7.6/7.6.18...client_release/7.6/7.6.20`
or via github: https://github.com/BOINC/boinc/compare/client_release/7.6/7.6.18...client_release/7.6/7.6.20

This narrows it down to this commit (I excluded translation and obviously unrelated changes):
7522f842e74eeb564cb7aaa32b8822482034e1b8 (new platform element in GUI RPC)

@CharlieFenton I don't see any changes to clientgui/BOINCGUIApp.* between those two versions.

**Comment by JuhaSointusalo** [comment] 2017-05-09 18:54
This should be fixed already with dde9573d644deea6c239797adc0cb06cf4411660. I'm not seeing Manager freezes but that may be because my remote host is Raspberry Pi with two projects and two tasks.

The rather embarrassingly poor commit message fails to mention that the bug causes Manager to request full status info from the client non-stop. With 300 tasks it may be that the Manager is too busy handling replies from the client and has no time to update UI.

**Comment by ChristianBeer** [comment] 2017-05-10 06:09
That's possible but since your commit was merged after 7.7.2 was built it is not part of that version and we have to wait on a real development release to test this further. I'll try to verify this at home where I can remotely connect to a host that has several hundred tasks and is usually very sluggish with Manager 7.6.33.

**Comment by ChristianBeer** [comment] 2017-05-12 13:58
I can confirm that a Manager which contains dde9573d644deea6c239797adc0cb06cf4411660 is much faster than 7.6.33 when connected to a remote Client 7.2.33 so in fact the problem is fixed.

This would be worth backporting to 7.6 I think, so I'll keep this issue open.

**Comment by adamradocz** [comment] 2017-05-15 12:11
I have the same issue. I have a 7.7.2 manager and if I want to connect to a 7.6.33 client, the manager is unresponsive and slow.

**Comment by AenBleidd** [comment] 2018-09-19 13:40
What is the current strategy regarding this ticket?
Could it be just closed or we still want to backport it to 7.6?

CC: @ChristianBeer, @RichardHaselgrove

**Comment by RichardHaselgrove** [comment] 2018-10-04 09:50
Maybe one final test with a 7.14.0 Manager and a 7.6.33 client, to test @adamradocz comment above? O can do that for Windows (OS not mentioned in the comment). I see no need for a backport - we've moved on a long way and I'm not aware of any compelling reason not to update beyond 7.6.33

**Comment by adamradocz** [comment] 2018-10-04 12:10
I close the issue, the new versions work perfectly, so I don't really care about 7.6.33 :)

**Closed by adamradocz** 2018-10-04 12:10 UTC
Labels: C: Manager, P: Major, T: Defect
