### ISSUE TITLE
Android BOINC 7.16.16 notifications aren't showing in Notices

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4185] opened 2021-02-16 11:32 UTC
Let me start by saying thank you to the developers of the new Android app. Finally one that does work on my phone. :)

But I have found a small bug of sorts. When I have the phone unplugged, I get a notification in Androids notification bar that tells me in a hyphenated sentence that I should put the phone on a charger if I want it BOINC to do work. Tapping on this notification brings me to the Notices tab of the BOINC app, but there's nothing there, it's all empty whitespace. 

I would expect that the Notices tab in the BOINC app says something about the phone needing to be on the charger, if the preferences are set for only able to do computations while on a charger. Especially if tapping on that notification brings me to the Notices tab in the app.

**Comment by AenBleidd** [comment] 2021-04-17 09:27
Duplicate of #4187

**Closed by AenBleidd** 2021-04-17 09:27 UTC
Labels: C: Android - Manager, P: Minor, R: duplicate, T: Defect
