### ISSUE TITLE
Reduced CPU utilization for exclusive use with "while computer is in use"

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#903] opened 2015-02-04 03:17 UTC
**Reported by halemos on 6 May 39485310 04:26 UTC**
I find that my systems respond sluggishly when I am making use of them AND boinc is running. I know that I am not taxing my systems with document writing and web browsing, but my 'user experienced' is diminished while boinc runs.

It would be great if the boinc application could be prioritized lower when the user is logged in AND the "while computer is in use" option is checked. Optionally, the "use at most X% of CPU time" option could be used in coordination with the "while computer is in use" option.

Overall what I'm shooting for is full use (by boinc) of my system when I am away, and partial use while I am logged in and doing work.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/926

**Comment by romw** [comment] 2015-02-04 21:54
**Commented by Nicolas on 23 Sep 39485324 19:33 UTC**
BOINC is '''always''' prioritized at the lowest your OS allows.

Do you run BOINC projects on your graphics card (CUDA)? That is known to cause sluggish systems. There is an option to suspend GPU tasks when the computer is in use, and keep running CPU tasks.

**Comment by romw** [comment] 2015-02-04 21:54
**Commented by cli on 10 Feb 40872116 06:40 UTC**
I think halemos want something like this in the preferences

"Use X percent of [cores|GPUs|cputime](CPU) when user is idle"[Y percent of [CPU cores|GPUs|cputime]([BR]]"Use) when user is active"

(X > Y)

**Comment by ChristianBeer** [comment] 2017-04-07 09:59
duplicate of #41

**Closed by ChristianBeer** 2017-04-07 09:59 UTC
Labels: C: Undetermined, P: Undetermined, T: Enhancement
