### ISSUE TITLE
Manager: can't reopen after abend

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#3310] opened 2019-09-27 19:29 UTC
**Describe the bug**
Impossible to re-open BOINC Manager after abnormal closures. Reported in https://boinc.berkeley.edu/forum_thread.php?id=13132 as the result of a system crash: also observed as the result of using the top-right 'x' closer in v7.16.1

**Steps To Reproduce**
1. Crash the system
2. or (sporadically) forget to use the menu to close the Manager window

**Expected behavior**
the Manager re-opens normally on request

**System Information (please complete the following information):**
 - OS: Linux - Ubuntu and Mint
 - BOINC Version: unstated and v7.16.1

**Additional context**
Problem was found to be resolved by deleting a left-over file: ` /home/<ID>/BOINC Manager-<ID>`

**Comment by AenBleidd** [comment] 2019-09-30 12:14
Closed as a duplicate of #1576

**Closed by AenBleidd** 2019-09-30 12:14 UTC
Labels: R: duplicate
