### ISSUE TITLE
Fix software weaknesses around the message “Authorization required, but no authorization protocol specified”

### ISSUE THREAD

**Issue by elfring** [BOINC/boinc#5374] opened 2023-09-23 11:18 UTC
**Describe the bug**
The message “Authorization required, but no authorization protocol specified” is logged by the program “boinc” with a remarkable frequency.
:thought_balloon: I find that too much computation resources are acquired then.

:eyes: See also [a related clarification approach](https://github.com/BOINC/boinc/issues/4048#issuecomment-1728393573 "BOINC Manager interface shouldn't fully block user interaction when in communicating with client dialog").

**Steps To Reproduce**
Start a service like “boinc-client-variant” (on demand).

**Expected behavior**
I would expect significantly less log messages for an ordinary operation of this service implementation.
More useful work should be performed for popular data processing projects.

**System Information**
 - OS: openSUSE Tumbleweed
 - BOINC Version: 7.25?
   https://github.com/BOINC/boinc/commit/16a8fa2f0089ee6d79f7d0273cfc9e3428769906

**Additional context**
:thought_balloon: It seems that the text “Authorization required” is not stored within the BOINC development repository.
Thus I assume that it is provided by an external software component somehow.
Which function calls would indicate a questionable situation here? :thinking:

**Comment by AenBleidd** [comment] 2023-09-23 13:11
Closed as a duplicate of #2256

**Closed by AenBleidd** 2023-09-23 13:11 UTC
Labels: P: Undetermined, R: duplicate, T: Defect, C: Client - Linux

**Comment by elfring** [comment] 2023-09-27 12:14
:crystal_ball: How much further considerations will the following analysis result trigger?
```
Sonne:/var/lib/boinc # XX=$(date) && time echo "$(journalctl --since today --identifier=boinc | wc -l) lines" && YY=$(date) && echo "$XX | $YY"
232500 lines

real    0m17.826s
user    0m8.139s
sys     0m9.924s
Wed Sep 27 14:11:48 CEST 2023 | Wed Sep 27 14:12:06 CEST 2023
Sonne:/var/lib/boinc # XX=$(date) && time echo "$(journalctl --since today --identifier=boinc --grep='Authorization required' | wc -l) lines" && YY=$(date) && echo "$XX | $YY"
232451 lines

real    0m18.970s
user    0m9.404s
sys     0m9.879s
Wed Sep 27 14:12:16 CEST 2023 | Wed Sep 27 14:12:35 CEST 2023
```

**Comment by AenBleidd** [comment] 2023-09-27 12:22
@elfring, as I wrote above, there is currently a bug in BOINC, and this issue you created is a duplicate of it. There are several workaround that could temporary solve this issue om your side. You were already pointed to them.
We're currently working on providing our own packages for the major linux distributions.
After that it will be easier and possible to handle this issue as well.
Currently this issue is not on the top of our backlog since it requires a redesign of idle detection check implemented in BOINC. I don't see currently a solution to fix this quickly and in a safe way.
Stay tuned, and I'll let you know when we have this issue solved.

**Comment by CharlieFenton** [comment] 2023-09-27 12:43
Please also see my comment [here](https://github.com/BOINC/boinc/issues/4048#issuecomment-1737217103)

**Comment by nethershaw** [comment] 2024-09-03 02:55
@AenBleidd How about, instead of redesigning the idle detection check, you allow us to simply _shut it the hell off?_
