### ISSUE TITLE
Adding project with white space in password breaks authentication

### ISSUE THREAD

**Issue by Raventara** [BOINC/boinc#2587] opened 2018-07-04 02:33 UTC
You cannot authenticate with a project (at least I couldn't with SETI@Home) if your password contains spaces.

**Comment by CharlieFenton** [comment] 2018-07-04 08:00
IMO, passwords should never contain spaces. I would be surprised if there are many web sites that allow spaces in passwords.

**Comment by mohe2015** [comment] 2018-07-04 10:11
@CharlieFenton There is no real reason. See https://security.stackexchange.com/questions/32691/why-not-allow-spaces-in-a-password Spaces at the beginning and end should maybe be trimmed because of copy pase errors etc. but ones in the middle should be fine. They can give additional security as you normally don't brute force passwords with spaces. You don't have to use them if you don't want to.

**Comment by Ageless93** [comment] 2018-07-04 10:44
Most of my newer passwords (outside of BOINC) contain spaces, as these are more difficult to 'guess' by brute force cracking than letters, numbers and underscores are. I think even that we should allow for all characters on the keyboard to be used in passwords. Or even allow a pass sentence.

**Comment by Raventara** [comment] 2018-07-05 01:00
@Ageless93 - Exactly - wherever possible I use a passphrase. They're more secure and can be super easy to remember.

On a side note it's hilarious/frustrating as all get out when a website not only disallows spaces, but also sets a *maximum* character limit on a password! :D

**Comment by davidpanderson** [comment] 2018-07-05 07:19
FWIW, the web interface for creating accounts and login allows spaces in
passwords,
including leading/trailing.

**Comment by Ageless93** [comment] 2018-07-05 09:45
Okay, I have tested that. Changed my password at Seti to be a passphrase with spaces, removed the project from BOINC, added it again. Chose the Yes, existing user route in the add project wizard, filled in my new passphrase, which BOINC had no problems with. 

So BOINC 7.10.2 at least has no problems with passwords/passphrases with spaces in them.

**Comment by AenBleidd** [comment] 2018-10-02 19:17
@Raventara, is this still an issue? Looks like no one else has the same issue

**Comment by AenBleidd** [comment] 2018-10-25 12:48
Since there is no answer from topic starter for 3 weeks already I'm closing this issue.
If it still could be reproduced feel free to reopen it

**Closed by AenBleidd** 2018-10-25 12:48 UTC
Labels: C: Server - Other, C: Web - Forums, P: Blocker, R: worksforme, E: to be determined
