### ISSUE TITLE
Cannot  add project

### ISSUE THREAD

**Issue by zhaonianzhu** [BOINC/boinc#4132] opened 2020-12-24 14:26 UTC
After installing the app on my computer，Cannot log in when adding project

1. Keyboard can’t type
2. And No response，only the way Close app

I hope I can log in normally, and I can add volunteers for the project

PC
3500x
ram 48G
x64
win10

**Comment by AenBleidd** [comment] 2020-12-24 14:39
Could you please add more details and steps you did while installing BOINC and adding a project? Because using description you provided I can't reproduce it. Also please tell what project you're trying to add.
Thanks in advance

**Comment by zhaonianzhu** [comment] 2021-02-19 13:35
https://blog.csdn.net/zhaqonianzhu/article/details/113872282
please look at gif，I recorded

**Comment by AenBleidd** [comment] 2021-04-25 19:08
Closed as a duplicate of #4014

**Closed by AenBleidd** 2021-04-25 19:08 UTC
Labels: C: Manager, P: Major, R: duplicate
