### ISSUE TITLE
BOINC Manager macOS Spotlight search result says "Unknown Version"

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3794] opened 2020-06-01 06:40 UTC
<img width="792" alt="Screen Shot 2020-05-31 at 11 39 21 PM" src="https://user-images.githubusercontent.com/1305957/83382512-14f24680-a398-11ea-9f12-67e95e3a3a6a.png">

**Comment by CharlieFenton** [comment] 2020-06-01 10:47
I can confirm this. It also happens for The BOINC Installer, BOINC Uninstaller and BOINC Screensaver. I don't know why it happens, but I suspect that perhaps it could be fixed by adding another field to each one's Info.plist file with the key "Bundle versions string, short" and the version number. 

The Info.plist files are created dynamically when BOINC for the Mac is built by running a small utility SetVersion, which is generated from the code in clientgui/mac/SetVersion.cpp and the files in clientgui/mac/templates/. Adding this field involves changing each of those files.

But if I select any of these applications or BOINCSaver.saver in the Finder, it shows the correct version number, and if I then select "Get Info" from the File menu it also shows the correct version number. So ultimately I think it would be nice to fix this, but certainly not critical.

@AustinConlon since I am basically retired from writing software, BOINC needs new Mac software developers to take over maintenance. it would be great if you might be interested in helping with BOINC development on the Mac. Please feel free to implement this change.

Here is a bit more info to get you started: SetVersion is built by  the SetVersion target in boinc.xcodeproj and then run from the "Run Script" phase of the SetVersion target. The SetVersion target is listed as a Target Dependency by the mgr_boinc, Install_BOINC, Uninstaller, Postinstall and ScreenSaver targets.

**Comment by makeasnek** [comment] 2023-04-26 04:28
A $25 bounty has been placed on this issue by the [Science Commons Initiative](http://thesciencecommons.org). If you would like to contribute to this bounty or claim it, visit BountySource https://app.bountysource.com/issues/119782299-fix-boinc-version-numbering-on-macos

**Closed** 2023-05-03 04:23 UTC
Labels: P: Major, T: Defect, C: Installer - Macintosh, The SCI Campaign
