### ISSUE TITLE
BOINC Advanced View tabs are too small

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#3940] opened 2020-07-22 21:54 UTC
I noticed this first on the Notices tab, when there's a number behind it, the opening bracket shows but nothing else. In the rest of the tabs, the text also shows kinda squished. 

But it's worse when I switch to my native language (Dutch), then the words are just cut off. 

![tabs too small](https://user-images.githubusercontent.com/10869587/88232595-6c18e700-cc76-11ea-88a2-c83747b0a99c.png)
![tabs too small in other languages](https://user-images.githubusercontent.com/10869587/88232603-7509b880-cc76-11ea-95de-4dc4b9c3f46d.png)

Weren't tabs dynamic in size, that they could adjust their size according to the word they wanted to show? Because this is bad. 
BOINC 7.16.7, Windows 10.

**Comment by AenBleidd** [comment] 2020-07-22 22:37
Closing as a duplicate of #2364

**Closed by AenBleidd** 2020-07-22 22:37 UTC
Labels: C: Manager, P: Minor, R: duplicate, E: to be determined
