### ISSUE TITLE
Gui Client : Unredable interface in dark mode on macOS

### ISSUE THREAD

**Issue by LoHub** [BOINC/boinc#3544] opened 2020-03-29 16:44 UTC
**Describe the bug**

The last BOINC Client version has an issue with dark mode on macOS. In particularly, text button is white over a white background

**Steps To Reproduce**

0. Close BOINC client if it is already opened
1. Set macOS in dark mode
2. Open BOINC client

**Expected behavior**
An easy to read interface

**Screenshots**

![Capture d’écran 2020-03-28 à 16 03 36](https://user-images.githubusercontent.com/11139973/77854779-cda2da80-71db-11ea-864d-e25d0b3cc446.png)

**System Information**
 - OS: 10.14.6
 - BOINC Version: 7.14.3

** Related issue **

#2917

**Comment by AenBleidd** [comment] 2020-03-29 16:45
Duplicate of #2917

**Closed** 2020-03-29 16:46 UTC
Labels: R: duplicate

**Comment by CharlieFenton** [comment] 2020-03-31 10:49
I have released BOINC 7.14.4 for Macintosh which tells the OS to not use dark mode for BOINC even when Dark Mode is generally selected. This workaround allows BONC to be usable under Dark Mode until BOINC can be updated to fully support dark mode.
