### ISSUE TITLE
"Tools > Use account manager... > Account manager URL:" Not working [7.6.9 (x64)]

### ISSUE THREAD

**Issue by Kati3e** [BOINC/boinc#1454] opened 2015-12-16 23:57 UTC
Entering another account manager's URL does not work as expected. It will always use whichever is selected in the list (Currently either BAM! or GridRepublic), ignoring the custom URL.

This means no other account managers besides BAM! or GridRepublic are usable unless adding them thru the boinccmd.

Also while I am here, how do I go about requesting to be added to that list?

**Comment by davidpanderson** [comment] 2015-12-17 08:24
I can't repro this with the manager built from trunk - I'll look in to 7.6.9.

What's your acct mgr URL?  I'll check it out and maybe add to the list.

**Comment by davidpanderson** [comment] 2015-12-17 08:55
The problem does occur in 7.6.9.
It will be fixed in the next release (hopefully soon).

**Comment by ChristianBeer** [comment] 2015-12-17 13:42
This was already fixed in 7.6.10+ see: f7b760e1b

**Closed by ChristianBeer** 2015-12-17 13:42 UTC

**Comment by grctest** [comment] 2016-02-12 18:45
RE: Fixed in 7.6.10+

[The latest linux releases are:](https://boinc.berkeley.edu/download_all.php)
7.4.22: Development version 
7.2.42: Recommended version

Since the latest linux release is < 7.6.10, they're still affected by this issue. (Assumption, not confirmed it).
Are there plans in the future for releasing a new BOINC client version on linux? Is it a matter of funding?

**Comment by pedrosimao** [comment] 2016-04-07 09:27
Hello, I have an issue using Account Manager on Ubuntu.
I try to synchronise my account, but it says: "unexpected XML tag or syntax""

Any solutions?

**Comment by grctest** [comment] 2016-10-02 17:03
How consistent are version numbers between the different BOINC platforms? (Windws vs linux vs mac vs android) - If this was fixed in 7.6.10 then wouldn't that mean that the following platforms haven't received the fix?

7.2.42: Mac OS X (32-bit or 64-bit Intel)
6.12.35: Mac OS X (Power PC or 32-bit Intel)
7.2.42: Linux x64
7.2.42: Linux x86
6.12.22: Older Linux x86 and x64
7.4.53: Android

Or is this inaccurate & the BOINC website is just showing old data? https://boinc.berkeley.edu/download_all.php

**Comment by davidpanderson** [comment] 2016-10-03 07:21
That's accurate.
Some of those we don't support any more.
Linux and Android we support but for various reasons don't have a current release
(we're working on it).
-- David
