### ISSUE TITLE
Intel Xe Driver support

### ISSUE THREAD

**Issue by debianmain1** [BOINC/boinc#5639] opened 2024-05-28 00:09 UTC
**Describe the bug**
Feature request & bug report

**Steps To Reproduce**
1. Enable Intel Xe driver support with >6.8 Linux Kernel & Mesa 24.1
2. Expect to see reported video driver in BOINC Manager

**Expected behavior**
BOINC using the Intel Xe driver for compute tasks.

**System Information**
- **Date generated:**                           2024-05-27 17:05:26

## Hardware Information:
- **Hardware Model:**                         ASUS ROG STRIX Z790-H GAMING WIFI
- **Memory:**                                      32.0 GiB
- **Processor:**                                   13th Gen Intel® Core™ i7-13700KF × 16
- **Graphics:**                                     Intel® Arc™ A750 Graphics (DG2)
- **Disk Capacity:**                              3.5 TB

## Software Information:
- **Firmware Version:**                         2102
- **OS Name:**                                     EndeavourOS
- **OS Build:**                                      2021.04.17
- **OS Type:**                                      64-bit
- **GNOME Version:**                          46
- **Windowing System:**                      Wayland
- **Kernel Version:**                              Linux 6.9.2-zen1-1-zen
 
BOINC version: git-version 8.1 (build 5-27-2024)

**Additional context**
This is a VERY experimental addition...but in view of the upcoming Intel BattleMage video cards, very timely. BattleMage will be on the market within the next 6 months & full support will be available for them with the 6.10 Kernel. To leverage the increased computing power, it would be very advantageous to have the Xe driver available to BOINC.

Reference information:   https://www.phoronix.com/news/Intel-Linux-Display-Battlemage

**Comment by AenBleidd** [comment] 2024-05-28 00:21
Closed as a duplicate of #5537

**Closed by AenBleidd** 2024-05-28 00:21 UTC
Labels: P: Undetermined, R: duplicate, T: Defect, C: Client - Linux
