### ISSUE TITLE
BOINC freezes when entering email adress.

### ISSUE THREAD

**Issue by xu-shawn** [BOINC/boinc#4014] opened 2020-09-08 15:07 UTC
**Describe the bug**
Typeing in input box after connecting to projects cause BOINC to freeze(Can't open event log,Can't press any buttons,Can't do anything)

**Steps To Reproduce**
1. Open BOINC
2. Click "Add Project"
3. Choose any project
4. Click "next"
5. Enter email address

**Steps To Reproduce**
1. Open BOINC
2. Click "Add Project"
3. Choose any project
4. Click "next"
5. Click "back" after connected
6. Enter project URL

**Expected behavior**
Address sucessfully being typed in.
project URL being typed in.

**Screenshots**

**System Information**
 - OS: windows10
 - BOINC Version: 7.16.11

**Additional context**

**Comment by Ageless93** [comment] 2020-09-08 16:08
Before playing thirteen questions, see https://boinc.berkeley.edu/forum_thread.php?id=13955 for slightly more information.

**Comment by putianyi889** [comment] 2021-03-19 10:51
I have the same issue. I used BOINC on a few other devices, but can't get it work on my new laptop. It's just a minor bug but could hold many people back.

**Comment by putianyi889** [comment] 2021-03-19 11:12
I've figured it out. BOINC conflicts with Windows' default Chinese input method, Microsoft Pinyin. We can switch the keyboard to US and then everything is fine. I was using Google Pinyin on old devices. I haven't tested if Google Pinyin works.

**Comment by AenBleidd** [comment] 2022-03-26 15:37
Looks like an issue of wxWidgets with Microsoft Pinyin. Not sure we can do anything with this, so closing this ticket for now.

**Closed by AenBleidd** 2022-03-26 15:37 UTC
Labels: C: Manager, P: Major, R: wontfix

**Comment by putianyi889** [comment] 2022-08-01 08:20
Can BOINC switch the keyboard mode automatically when it detects Microsoft Pinyin?

**Comment by AenBleidd** [comment] 2022-08-09 21:01
@putianyi889, is this issue still reproducible on BOINC 7.20.2 ?

**Comment by putianyi889** [comment] 2022-08-09 21:06
@AenBleidd No. I was on 7.16.11 which couldn't fetch update automatically. 7.20.2 works.
