### ISSUE TITLE
7.14.1 for Android: Size-based settings multiply inputs by powers of 1.024

### ISSUE THREAD

**Issue by numbermaniac** [BOINC/boinc#3032] opened 2019-02-24 07:32 UTC
**Describe the bug**
In the advanced settings of the beta Android app (7.14.1), there are some settings available that take an amount of bytes - "Daily transfer limits" takes a number of megabytes, and "Min spare storage" takes a value in gigabytes. However, whatever value you enter is multiplied by a power of 1.024 (I think), based on the default unit.

**Steps To Reproduce**
1. Open Settings and activate advanced settings.
2. Tap "Daily transfer limit" and type in 100. When you hit save, it shows 105 MB.
3. Tap it again and enter 500, and when you hit save, it says 524 MB.
4. Scroll down to "Min. spare storage".
5. Tap on it and enter 1. When you save, it shows "1.1 GB". Tap it again and enter 100 - when you save, it shows 107 GB.

**Expected behavior**
If I enter 100 MB for example, it should show 100 MB.

**System Information:**
 - OS: Android 8.0.0
 - BOINC Version: 7.14.1

**Additional context**
What seems to be happening is that it's multiplying the input by 1.024, for each "tier" up to the expected unit. "Daily transfer limit" is measured in megabytes, so it multiplies your input by 1.024² - once to go from bytes to kilobytes, and again to go to megabytes.

"Min spare storage" is measured in gigabytes, so it multiplies your input by 1.024³ - same as above, but once more to go up to gigabytes.

I didn't have this issue on the stable version of BOINC running on Android 6.0.1.

**Comment by numbermaniac** [comment] 2019-03-08 08:01
This issue is not present in the stable version, 7.4.53, of BOINC on Android 8 either.

**Comment by AenBleidd** [comment] 2019-05-09 21:17
Looks like this issue is already fixed in master. At least I could not reproduce it. Should be verified on Release build when ready

**Closed** 2019-10-02 19:28 UTC
Labels: C: Android - Manager, P: Minor, R: worksforme, E: 1 day
