### ISSUE TITLE
Update Flatpak runtime since org.gnome.Platform branch 44 is end-of-life

### ISSUE THREAD

**Issue by latenightdef** [BOINC/boinc#5683] opened 2024-07-13 06:44 UTC
This template is for miscellaneous issues not covered by the other issue categories.

When I run flatpak upgrade, I get this in the terminal
```
Info: runtime org.gnome.Platform branch 44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   edu.berkeley.BOINC
```

Please update to the latest runtime (currently 46), thanks!

**Comment by AenBleidd** [comment] 2024-07-13 06:50
Closing this as a duplicate of https://github.com/flathub/edu.berkeley.BOINC/issues/16

**Closed by AenBleidd** 2024-07-13 06:50 UTC
Labels: C: Undetermined, R: duplicate, T: Defect
