### ISSUE TITLE
BOINC Manager doesn't minimise to tray

### ISSUE THREAD

**Issue by shalnoff** [BOINC/boinc#1352] opened 2015-02-14 02:10 UTC
the window of BOINC Manager doesn't minimise to tray at all, whatewer buttons you click (Mate, Linux Mint 32bit. BOINIC 7.0.27) It would be great to hide it in tray and restore on click on the icon.

thank you for great applicaiton!

**Comment by ChristianBeer** [comment] 2015-02-14 11:51
duplicate of #1348

**Closed by ChristianBeer** 2015-02-14 11:51 UTC
