### ISSUE TITLE
Boinc doesn't accurately detect when computer is in use

### ISSUE THREAD

**Issue by evilonod** [BOINC/boinc#4627] opened 2022-02-04 19:47 UTC
I'm running version 7.17.0 on Ubuntu 20.04 LTS.

Boinc doesn't detect when computer is in use when I'm typing in a web browser.    And certainly doesn't detect mouse motion at all.

It works as expected when typing in a terminal.   But not when I'm checking my e-mail using a web interface for instance.

**Comment by AenBleidd** [comment] 2022-10-07 23:41
Closed as a duplicate of #1187

**Closed by AenBleidd** 2022-10-07 23:41 UTC
Labels: P: Undetermined, R: duplicate, T: Defect, C: Client - Linux
