### ISSUE TITLE
BOINC Screen Saver does not respond properly when a graphics application spawns a window (like RNA World cmsearch spawns Adobe Flash 9)

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1056] opened 2015-02-04 04:23 UTC
**Reported by JacobKlein on 11 Aug 41249025 08:00 UTC**
Rom and I have been doing some screensaver testing in Alpha testing, and I believe I have come up with some reproducible bugs that should be reported as tickets. As far as I know, these bugs exist on 6.10.58 and the latest alphas.

This ticket is regarding applications where, while in screensaver, their graphics launch a window. In my case, RNA World Project has an application called "cmsearch S" whose graphics consist of spawning an Adobe Flash 9 window even while in screensaver mode.

When the BOINC screensaver runs, and is set to rotate between projects, and an RNA World task gets rotated in, bad things can happen.

Among those bad things are:[Moving mouse/keyboard does not release the screensaver, and the user has to hit Ctrl+Alt+Del[[BR]([BR]]-)]- Moving mouse/keyboard does not dismiss the spawned window[The BOINC screen saver shows "unspecified error" for some periods of time[[BR]([BR]]-)]- When rotating the project in, the screen can be completely black for that rotation, yet appear to work fine for the next rotation if it is a different project.

I believe this should be considered one bug -- the BOINC screensaver needs to either properly handle the spawned window graphics, or somehow not allow them.

I'm betting there are other projects that, while in screensaver, launch graphics in a window... but of my projects, only RNA World is causing the problem.

Below is an email detailing the things I found, which I believe are attributable to this ticket's bug(s):

---

From: jacob_w_klein@msn.com[romw@romwnet.org; boinc_alpha@ssl.berkeley.edu[[BR]([BR]]To:)]Date: Thu, 31 Mar 2011 !17:13:43 -0500[Re: [boinc_alpha]([BR]]Subject:) 6.12.19 - Strange screensaver results[[BR]]

```

Rom (et al):

I have good news, I hope!
After more testing (with your most recent build boincscr.310311.x64), I might finally be able to conclude some stuff!

Note: I'm only about 70% sure that the following is accurate, but preliminary results show:
- If, when the screensaver is 1-minute-cycling between projects, if the RNA project is selected at all, then I will be later forced to Ctrl+Alt+Del to get back to the login, even if the screensaver shifts out of RNA project before use mouse/keyboard.
- If RNA is selected first in the rotation, I will be able to see the Adobe window, but it will be a) non-focused (could this be a problem?), and b) non-Win-7-Aero (meaning the window frame uses Aero Basic -- could this be a problem? Should be full-screen?)
- If RNA is selected first in the rotation, if the screen saver needs to transition to another project, it will have problems for a short time, and I will see "unspecified error" a few times
- If RNA was not selected first in the rotation, but then needs to "rotate in", sometimes for that whole minute I don't get the Adobe window, and my screen is just completely blank.

I've attached some stdoutscr.txt log files, along with an .xlsx Excel file I'm using as a legend.  (Hopefully you can read .xlsx - I think Microsoft may offer a free Windows Excel viewer)

Note that "->" means a transition between projects during the screensaver run.

The logs that are good control-tests are:
009 (which FAILED): RNA World -> Rosetta, Moved mouse, screen went black, waited 25 seconds, No response, Hit Ctrl, No effect, Hit Ctrl+Alt+Del, Responded.
010 (which DID work correctly): World Community Grid (no transitions), Moved Mouse, responded immediately.
011 (which DID work correctly): Rosetta (no transitions), Moved Mouse, responded immediately.
012 (which DID work correctly): Was showing the generic BOINC screensaver (no transitions), Moved Mouse, responded immediately.
013 (which DID work correctly): Docking (no transitions), Hit Ctrl, responded immediately.
014 (which FAILED): Docking for 1 min -> Blank screen for 1 min (Should have been RNA because I only had those 2 projects running!) -> Docking for 20 seconds, Moved Mouse, screen went black, waited 25 seconds, No response, Hit Ctrl, No effect, Hit Ctrl+Alt+Del, Responded.
015 (which FAILED): RNA World (with nonfocused non-Win7-Aero Adobe window) for 1 min -> On switch to Docking, briefly saw "unspecified error" a couple times -> Eventually switched to Docking, then after 20 seconds, I moved mouse, screen went black, waited 25 seconds, No response, Hit Ctrl, No effect, Hit Ctrl+Alt+Del, Responded.

I'm becoming a believer that the funky RNA method of Graphics (and the fact that BOINC screensaver is not handling the funkyness correctly)... is the cause of the problems!
I'll keep testing, but I'm at least smiling - aren't you?

- Jacob
```

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1080

**Comment by romw** [comment] 2015-02-04 23:21
**Commented by JacobKlein on 8 Nov 41253123 04:26 UTC**
Note 1: When the only project I'm running is RNA World, and the screensaver kicks in, the screensaver will load Adobe Flash 9 and I can see the graphics for the first task, but then if another RNA World task rotates in, the screensaver will fail repeatedly, in the form of a blinking BOINC logo with text that says:

"There was an unspecified problem[the BOINC screensaver."

Note 2: When not in screensaver mode, if I run the graphics for an RNA World task, then let the screensaver kick in, the screensaver will fail immediately (and repeatedly),in the form of a blinking BOINC logo with text that says:

"There was an unspecified problem[[BR]([BR]]with)] with the BOINC screensaver."

Hope this is somehow helpful!

**Comment by romw** [comment] 2015-02-04 23:21
**Commented by JacobKlein on 24 Aug 41328362 06:40 UTC**
Tickets [#1080](http://boinc.berkeley.edu/trac/search/opensearch?q=ticket%3A1080) and [#1094](http://boinc.berkeley.edu/trac/search/opensearch?q=ticket%3A1094) are probably related.

**Comment by Ageless93** [comment] 2017-08-17 16:50
Is this still an issue?

**Comment by AenBleidd** [comment] 2018-10-02 13:33
Up

**Comment by ab1vl** [comment] 2018-10-19 12:04
10-19-18 re BOINC 7.14.2 release:

That BOINC screensaver and/or project graphics can have issues is well established historically.

Recent regression testing of BOINC 7.14.2 for windows with various project WUs has shown that even with the same Windows version (e.g WIndows Home Premium) differences in BOINC screensaver and project graphics interaction are observed on similar, but not identical, hardware configurations used for the console video port.  As a specifically example, a PC with GPU as console port may function normally but another using native motherboard port may not, and this is reproducible.  So here it remains undetermined whether the hardware itself or the driver software, or both, or BOINC screensaver are at the root cause of all observed screensaver/graphics issues.  Thus it seems likely that many reported issues of these types are as much dependent on the host computer HW and SW configuration as they reflections of BOINC software defects.  Note that no other configuration information than Adobe Flash and an old BOINC manager version are given in this issue, so no meaningful testing to dig down into root causes can be done at this time. 

I suggest the reporter(s) of this bug retest with BOINC for windows 7.14.2 (non Vbox) using the latest Flash, RNA World project (or equivalent) software, and report back with specifics if there are still graphics problems. Failing that I suggest we close out this issue.

**Comment by CharlieFenton** [comment] 2018-10-19 12:18
Correct me if I am mistaken, but if the project graphics are using Flash, I believe they are not in conformance with BOINC graphics requirements. My understanding is that project graphics for BOINC are **required** to render using OpenGL and / or GLUT and to link with the BOINC graphics libraries.

**Comment by JacobWKlein** [comment] 2018-10-20 00:37
I no-longer have a way to reproduce this issue, since RNA World doesn't have those task types anymore. Also, I haven't seen the issue recently, in my limited sampling of testing projects that have graphics apps. I'm okay if you decide to close this, so long as we can re-investigate if the issue happens again. Thanks.

**Closed** 2018-10-20 00:41 UTC
Labels: C: Client - Screen Saver, P: Major, T: Defect, Validate
