### ISSUE TITLE
Battery level or threshold wrongly recognized

### ISSUE THREAD

**Issue by ljez** [BOINC/boinc#5362] opened 2023-09-15 15:30 UTC
**Describe the bug**
I have the client set to use all power sources, including battery, and the battery's minimum charge is set as low as possible, i.e., at 10%.  Nevertheless, at seemingly random random points the computations stop and at the bottom there is a message that "computations will resume when battery charge reaches " --- yes, there is no number at the end of the message.  It happened a few times around 50% charge, but also at 94%.  The phone is a fairly old Asus ZenFone 3 Zoom ZE553KL with Android 8.0.0.  On previous version of BOINC this never happened.

**Steps To Reproduce**
1. Execute tasks from battery and wait?
2. 

**Expected behavior**
I expect the phone to keep executing tasks until battery charge drops to 9%.

**Screenshots**

**System Information**
 - OS: Android 8.0.0
 - BOINC Version: 7.24.1

**Additional context**

**Comment by AenBleidd** [comment] 2023-09-15 16:19
Closed as a duplicate of #5305

**Closed by AenBleidd** 2023-09-15 16:19 UTC
Labels: R: duplicate, T: Defect, C: Client - Android
