### ISSUE TITLE
Android client fails to get project list

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1411] opened 2015-10-20 04:14 UTC
From boinc_projects:
We followed the wiki and built the app successfully.
But, once launched,logging in, it shows null projects with continue button.

In logcat, we see BOINC_GUI: UpdateProjectListAsyncTask: fails to retrieve
data.

**Comment by Ageless93** [comment] 2017-08-17 21:41
Same issue as in #1384

**Comment by AenBleidd** [comment] 2018-10-23 14:11
Closed as a duplicate of #1384

**Closed by AenBleidd** 2018-10-23 14:11 UTC
Labels: C: Android - Manager, P: Major, R: duplicate
