### ISSUE TITLE
Computing preferences displays only white while in simple mode on linux

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#5246] opened 2023-05-21 17:41 UTC
**Describe the bug**

**Steps To Reproduce**
1. Install BOINC 7.20.5 from https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/boinc
2. Start systemd service
3. Start boincmgr.
4. open Options>Computing preferences.

**Expected behavior**

**Screenshots**

**System Information**
 - OS: Ubuntu 22.04
 - BOINC Version: 7.20.5

**Additional context**
The same happened with boinc-manager-7.20.2-1.el8.x86_64.rpm on Rocky Linux 8.

**Comment by AenBleidd** [comment] 2023-05-21 17:42
Looks like a duplicate of #4902

**Closed** 2023-05-21 17:47 UTC
Labels: P: Undetermined, R: duplicate, T: Defect, C: Manager - Simple View
