### ISSUE TITLE
"This version of BOINC requires MacOS 10.9 or later."

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#5317] opened 2023-08-03 12:05 UTC
As reported in https://boinc.berkeley.edu/forum_thread.php?id=15053

> Boing Manager suggest me to update and gives link to this page:
> https://boinc.berkeley.edu/download.php
> 
> Don't you think it's quite misleading to say 10.9 or later, when the installer needs 10.13 or later?

https://boinc.berkeley.edu/download_all.php does show the required MacOS versions correctly, just not the main download page. 
I can't edit the main page, so putting it here for someone who can.

**Comment by AenBleidd** [comment] 2023-08-03 12:07
@davidpanderson, @CharlieFenton, could you please handle this issue?
Thank you in advance

**Comment by CharlieFenton** [comment] 2023-08-03 20:35
@davidpanderson the versions.inc file has the minimum MaOS version required for each build in the form xxyyzz for mac OS version xx.yy.zz. For BOINC 7.22.2 it has: 
`"min_os_version"=>"101300"`
Which is MacOS 10.13.0. You could use this to always show the correct minimum MacOS version in https://boinc.berkeley.edu/download.php

**Comment by davidpanderson** [comment] 2023-08-04 09:27
I'll look into this.

**Comment by davidpanderson** [comment] 2023-08-04 11:07
I fixed this (hopefully) in 
https://github.com/BOINC/boinc-site/commit/f3dce9147160a7d2873eb8bfd63659a5dd9a7867

**Comment by AenBleidd** [comment] 2023-08-04 13:48
@Ageless93, could you please ask the user to test the Download page again?
Thank you in advance.

**Comment by Ageless93** [comment] 2023-08-04 18:39
Alright, I asked if he can test it. Or for someone else with MacOS version lower than 10.13 of course.

**Comment by CharlieFenton** [comment] 2023-08-05 01:09
I have confirmed it appears fixed on my Mac running MacOS 13.4. On my Mac, it previously showed:
> This version of BOINC requires MacOS 10.9 or later.

It now shows:
> This version of BOINC requires MacOS 10.13 or later.

@davidpanderson However, my quick look at your changes to _download_util.inc_ seems to show you simply hard-coded it to say `10.13` instead  of `10.9`. This is inadequate. With each new major version of Xcode, the minimum OS version for which it can build has been increasing. This text in https://boinc.berkeley.edu/download.php should be generated dynamically from the value in versions.inc, as I explained earlier. Also, there will be more _Older Versions_ in the future with newer minimum MacOS versions. It would be much better if this didn't need additions to _download_all.php_ and _download_util.inc_ each time, but could be dynamically determined from the `"min_os_version"=>` values already present in _versions.inc_, which I will continue to maintain.

**Comment by CharlieFenton** [comment] 2023-08-05 07:58
I was able to get my old Mac to work well enough to visit https://boinc.berkeley.edu/download.php while running macOS 10.12.6. It correctly gave me a link to download BOINC 7.20.2. It didn't show any text about the minimum requirement for this build of BOINC, but that is fine since it offered the correct download for the computer making the request.

**Comment by AenBleidd** [comment] 2024-01-27 09:53
@CharlieFenton, @davidpanderson, is there anything left in this ticket not done?

**Comment by davidpanderson** [comment] 2024-01-27 10:15
Not as far as I know.  Charlie?

**Comment by CharlieFenton** [comment] 2024-01-27 10:26
I think this can be closed as completed.

**Closed** 2024-01-27 10:33 UTC
Labels: C: Web - Other, P: Major, R: fixed
