### ISSUE TITLE
BOINC Manager starting from the registry.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#858] opened 2015-02-04 02:55 UTC
**Reported by Ageless on 21 Oct 39314219 03:33 UTC**
As per [this thread](http://boinc.berkeley.edu/dev/forum_thread.php?id=3508) in the BOINC Dev forums, people are requesting that there be an option to disable BOINC Manager from starting up automatically through its registry setting. Useful for multiple user systems and when installing BOINC (silently) on lots of (school) computers. 

Can't the option to check that you want to start BOINC Manager on Windows Login come back to the installer? 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/881

**Comment by romw** [comment] 2015-02-04 21:06
**Commented by romw on 26 Nov 39425704 08:53 UTC**
Punting remaining new feature work to 6.10

**Comment by romw** [comment] 2015-02-04 21:07
**Commented by romw on 24 Feb 40859073 16:26 UTC**
Setup bugs are being punted to a future release.  This work item should be completed with the new open source installer.

**Comment by AenBleidd** [comment] 2019-07-20 23:55
Closed as a duplicate of more recent and better discussed #2414

**Closed by AenBleidd** 2019-07-20 23:55 UTC
Labels: P: Minor, R: duplicate, T: Enhancement, Feature Request, C: Installer - Windows
