### ISSUE TITLE
Specify number of free cores

### ISSUE THREAD

**Issue by wiedenhoeft** [BOINC/boinc#4017] opened 2020-09-10 15:06 UTC
**Describe the problem**
In addition to specifying the number of cores used, allow the user to set the number of cores to keep free.

**Describe the solution you'd like**
In a multi-user environment such as a server, one may wish to keep a certain number of cores free to facilitate smooth login and so on. To that end, it would be nice to be able to specify the number of cores to keep free. For instance, if that number is 10, and the number of idle cores is 12, 2 processes should be run, if 11 are idle, 1 should be run, and if 10 or less are idle, no process should be run. This prevents a situation where, say, BOINC is allowed to use 80% of cores, then users start processes using up the other 20%, and suddenly the server is under full load.

**Comment by AenBleidd** [comment] 2020-09-10 15:10
The problem is that core could be under load for several seconds and then free again. Run and pause BOINC processes too frequently is not efficient. I believe it's better to use next option instead:
![image](https://user-images.githubusercontent.com/3234209/92751654-79a24180-f388-11ea-84ce-d9bd28b8c7d6.png)

**Comment by smoe** [comment] 2020-09-15 18:11
"The suspend if above" suspends the whole of BOINC which is not how I read the request. In my understanding this asks to just not use one (or two or ...) of the cores. While we got used to determine the percentage of processors that should be used, a different kind of semantics in particular for a zoo of differnet machines would indeed be nice.

**Comment by davidpanderson** [comment] 2020-09-16 04:07
I don't think it's desirable (or possible) for BOINC to act as a process scheduler; that's the job of the OS.
We should look more carefully at the features of modern OS's,
such as sched_setscheduler() in Linux.

**Comment by wiedenhoeft** [comment] 2020-09-22 15:28
Very well, it's just that a lot of these options are somewhat unintuitive. For instance, even the option to suspend when non-BOINC usage is above x% does not seem to work as I would understand it, as it fails to suspend if those other tasks are run at niceness 19, which is not unheard of in an HPC context with many users and lots of competing CPU-heavy tasks. I find this surprising, as this option is not controlled by the scheduler, is it?

**Comment by truboxl** [comment] 2020-09-27 15:07
Suppose if BOINC will not do this,
another way is for build an external application that can detect this kind of workload and
directly interface the client through RPC to suspend / continue compute.

Like a script that can detect the workload,
edits global_prefs_override.xml (controls the no. CPU core used) and/or cc_config.xml on the fly,
wrapping around boinccmd that talks to the client to read the config files above and suspend / continue compute.

This is a very niche idea to implement natively though.

**Comment by wiedenhoeft** [comment] 2020-09-30 08:28
So, how does BOINC actually compute external CPU usage, specifically with regards to niceness/priority? It certainly does not count active user tasks.

**Comment by davidpanderson** [comment] 2020-09-30 09:03
It looks in /proc.  See
https://github.com/BOINC/boinc/blob/master/lib/procinfo_unix.cpp

**Comment by wiedenhoeft** [comment] 2020-09-30 09:22
Thanks. Am I understanding correctly that
`p.is_low_priority = (ps.priority == 39);`
means that processes with priority 39 (niceness 19) will not ever be considered as user processes that could trigger a suspension?

**Comment by wiedenhoeft** [comment] 2020-09-30 12:17
I created some CPU-heavy tasks at different niceness levels and it appears that niceness 19 does not trigger suspension, but starting at 18 it works like a charm.

**Comment by wiedenhoeft** [comment] 2020-09-30 12:58
I think this behavior should either be documented, or the special treatment of niceness 19 be removed, as there may be valid user processes run at lowest priority which should still be respected by BOINC.

**Comment by truboxl** [comment] 2020-09-30 13:53
Not running at the lowest priority is detrimental to the entire system stability. The same can be said if tasks and other user processes running at niceness 18 and compete resources there.

BOINC actually run tasks at the lowest priority using SCHED_IDLE policy which technically is lower than niceness 19.
https://github.com/BOINC/boinc/blob/24548b00ccc9e5b16c04948fb35bb1b2c0d75f3f/client/app_start.cpp#L1091

I feel like this thread is derailing... Is this still about the feature request or is it a bug report?

**Comment by wiedenhoeft** [comment] 2020-09-30 14:12
Well, according to top it runs at niceness 19 and priority 39 on my Linux system at least. The original request was argued against, in that BOINC should not act as a scheduler. The second closest alternative that was suggested does not exactly do what it claims to do, as it treats niceness 19 differently than lower niceness. I'm trying to follow up on that alternative, to clarify how that would at least remotely achieve the intention of my first request. It appears the original feature request has been denied, but the issue has been made into a To Do. The rest of this thread is about clarification. Not sure that qualifies as derailing :-)

**Comment by wiedenhoeft** [comment] 2020-09-30 14:16
In short, I still want the behavior of the original request, or at least something similar in spirit as far as practically possible. :-)

**Comment by AenBleidd** [comment] 2024-08-29 14:17
This is a very edge case, but implementing such a functionality will make BOINC client configuration too complex.
As it was mentioned above, for such a cases it's better to create a custom script, that will monitor needed conditions and adjust BOINC client settings of the fly via boinccmd utility.

Closing this as "won't fix".

**Closed by AenBleidd** 2024-08-29 14:17 UTC
Labels: C: Client - Scheduler Policy, P: Minor, R: wontfix, T: Enhancement
