### ISSUE TITLE
Boinc manager goes to foreground when getting focus

### ISSUE THREAD

**Issue by LinAGKar** [BOINC/boinc#1782] opened 2017-02-05 13:17 UTC
If the WM is set to focus follows mouse, the window the pointer is over will gain focus, but will not go to the foreground until clicked. However, whenever Boinc-manager gets focus it moves to the foreground, which conflicts with this behavior, as Boinc Manager will go to the foreground whenever the pointer is over it.

Boinc Manager 7.6.33
OpenSUSE Leap 42.2
KDE 5.8.3

**Comment by ChristianBeer** [comment] 2017-04-12 12:38
duplicate of #1347

**Closed by ChristianBeer** 2017-04-12 12:38 UTC
Labels: C: Manager, E: to be determined, P: Minor, T: Defect
