### ISSUE TITLE
boinc-client loops on connection attempts to 600X ports on 127.0.0.1

### ISSUE THREAD

**Issue by ifettich** [BOINC/boinc#4025] opened 2020-09-20 09:33 UTC
I'm not really sure if this is a bug. At first I thought it's something the distro specific package would have added, but the maintainer of that package advised to ask upstream.

Problem as being bitten by:
___
I have boinc (7.16.6+dfsg-1) installed on two systems, both recently upgraded toUbuntu 20.4 from 18.04.
On the desktop, it works fine.
On a remote server where I log in via ssh, whereas the client seem to work, I cannot communicate with it...
Is it supposed to work or is that not yet in place/tested...?
___

I then figured out part of what was going on:
___
Hi Gianfranco,

just in case that would help to make the boinc-client better:
turns out that the client ***is*** actually responding boinccmd!
BUT: it does so after some 30 minutes... [YEP: 30 MINUTES!]
When boinccmd of course gave up already long ago.
The boinc-client seems to stubbornly and desperately want to connect to some 60XX ports - looking for a connection to X windows, on a headless server...?! There is no X.
Those attempts take time. Much time, as they'll one by one time out - just to have boinc-client reiterate the search after the last checked port.
I have no solution so far.  Is there a way to tell the boinc-client to forget about searching for X and just do it's job?
Thank you,
___

And then I also found a way to live with it:

___
I've got boinccmd working by doing

iptables -I INPUT -p tcp --dport 6000 -j REJECT
iptables -I INPUT -p tcp --dport 6001 -j REJECT
iptables -I INPUT -p tcp --dport 6002 -j REJECT
iptables -I INPUT -p tcp --dport 6003 -j REJECT
iptables -I INPUT -p tcp --dport 6004 -j REJECT
iptables -I INPUT -p tcp --dport 6005 -j REJECT
iptables -I INPUT -p tcp --dport 6006 -j REJECT

boinc-client still loops on connection attempts to 600X ports on 127.0.0.1, but at least it doesn't block any more... and overall, it appears to work as expected [while ist is not busy trying to connect].
I'm a bit disgruntled by seeing things like that in Ubuntu 20.4. It's supposed to be stable and solid... Hmm.
___

Conclusion (more or less):

___
the main cause for not being able to get boinccmd to talk to boinc-client were the very strict settings within the firewall.
While access to port 31416 was explicitely allowed, all other connections to unknow ports/services were DROPped - even from localhost.
That made boinc-client being extremely low in responses, as it has to timeout while connecting to port 6001, 6001, ..., 6006 before being able to do anything else.
I still consider that boinc-client's attempts to connect to these 6000+ ports are not legit and should not 'just happen', but I now have boinc-client happily working, and boinccmd and boincmgr as well.

# iptables -I INPUT -p tcp -s 127.0.0.1 -j ACCEPT

was the silver bullit to make evything work...
Please consider that severe access restrictions on headless servers might be rather common, so the issue I had to fight might hit others as well.
And the solution is rather not at all obvious - nowhere the docs are mentioning that connections to ports 6000+ are part of boinc-client's 'normal' behavior.

Well, thanks for your attention.
___

Now I'm curious - am I really the only one who had to fight with this...?

**Comment by AenBleidd** [comment] 2020-09-20 20:17
Looks like a duplicate of #3405.
Feel free to reopen if my assumption is wrong.

**Closed by AenBleidd** 2020-09-20 20:17 UTC
Labels: C: Client - Daemon, R: duplicate, C: Client - Linux

**Comment by ifettich** [comment] 2020-09-21 20:01
It is more or less a duplicate, so closing it here and mentioning it there should be OK, as the underlying issue is the same.
I'm just a bit unsure about the handling of it: I didn't get any notification about the decision. 
So when I looked if there would be any comment on 'my' issue, at first it appeared to have vanished... Had to look for it. Is that normal...? Shouldn't I get an e-mail  notification about the issue being marked as a duplicate and being closed here?
Thanks.

**Comment by AenBleidd** [comment] 2020-09-21 20:14
You should be subscribed to this issue to receive email notifications (or whatever is set in your preferences):
![image](https://user-images.githubusercontent.com/3234209/93816441-d38fea80-fc57-11ea-8c96-dcb3de939c96.png)
By default you subscribed to the ticket you created

**Comment by ifettich** [comment] 2020-09-21 20:28
I am subscribed now and got this comment of yours.... But I didn't get any notification about the issue being closed here and being marked as a duplicate of another issue. I'd have expected to get an e-mail about that. 
Maybe _actions_ are not subject of outgoing e-mails, and just the comments are? 
Not even you're closing comment reached me. Weird. Or is closing an issue stopping outgoing e-mails as well?
Thanks - looks all well now.

**Comment by AenBleidd** [comment] 2020-09-21 21:00
TBH, it's better to ask GitHub support :)
You should have receive all notifications about every change except comment/title edit, labels change and similar.

**Comment by davidpanderson** [comment] 2020-09-25 05:24
The client looks for X server names in /tmp/.X11-unix/
On your server, what does this dir contain?

**Comment by ifettich** [comment] 2020-09-25 06:01
> The client looks for X server names in /tmp/.X11-unix/
> On your server, what does this dir contain?

That directory exists, and it is empty.

Thanks,

Iosif Fettich

**Comment by davidpanderson** [comment] 2020-09-25 06:05
Hmm.  It's possible that this is fixed in 7.16.11
