### ISSUE TITLE
Docker web-based manager

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#3158] opened 2019-05-24 00:30 UTC
I created a [Boinc Web Manager](https://github.com/adamradocz/boinc-manager) in asp.net core. It uses Docker. It's very rudimentary, currently, it can only show information about the client, but it has multiclient support and very useful if you want to monitor multiple clients on your network.

The [Boinc Client Docker](https://github.com/BOINC/boinc-client-docker) is very popular, it's over 1 million downloads, so I think this one could be too.
I'd like to create an official Boinc Web Manager in Docker Hub.

@davidpanderson, @AenBleidd @marius311 @TheAspens What do you guys think about it?

**Comment by AenBleidd** [comment] 2022-10-07 15:55
Closed as a duplicate of #2112

**Closed by AenBleidd** 2022-10-07 15:55 UTC
Labels: R: duplicate, T: Informational
