### ISSUE TITLE
option to not compute while recharging

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1776] opened 2017-01-29 20:48 UTC
(from a user email)

Have an option (in the desktop non-Android version) to not compute while
battery charge is less than some fraction.
Apparently computing slows down battery charge on some computers.

First step is to identify APIs for finding battery charge level.

**Comment by sirzooro** [comment] 2017-01-29 21:08
This could be achieved with battery level thresholds proposed in #1758, by setting them to e.g. suspend at 90%, resume at 100%.

**Comment by CommonLaw8390** [comment] 2017-01-29 21:11
I'm the person who emailed you!

So, apparently the command for charge level is "ioreg -l -w0 |grep CurrentCapacity" and the command for the maximum charge is "ioreg -l -w0 |grep MaxCapacity". http://stackoverflow.com/questions/1432792/how-to-get-the-battery-life-of-mac-os-x-macbooks-programatically (I've never ran a command before, thanks David) :)

**Comment by ChristianBeer** [comment] 2017-01-30 07:43
Duplicate of #1758. I added the API info there too.

**Closed by ChristianBeer** 2017-01-30 07:43 UTC
