### ISSUE TITLE
Taskbar context menu crashes manager (Win 10)

### ISSUE THREAD

**Issue by martixy** [BOINC/boinc#4312] opened 2021-04-04 09:02 UTC
**Describe the bug**
Old taskbar context menu crashes BOINC Manager.

**Steps To Reproduce**
1. Try to bring up the old context menu - the one with maximize/minimize/move, etc.
2. BOINC Manager crashes.

**Expected behavior**
No crash, duh.

**Screenshots**
N/A

**System Information**
 - OS: Win 10 v2004
 - BOINC Version: v7.16.11

**Additional context**
I use a program called 7tt that gives me the old context menus. Not sure how to bring up in vanilla win 10, since I've never used vanilla win 10.

**Comment by RichardHaselgrove** [comment] 2021-04-04 09:28
Please distinguish exactly what crashes. Your subject line says it's the client, but your description says it's the manager.

These are separate and distinct programs within the BOINC package. If (as seems likely) it's a Manager problem, please amend the subject line accordingly.

**Comment by AenBleidd** [comment] 2021-04-04 10:28
Looks like a duplicate of #4186, and thus should be fixed by #4198
@martixy, could you please download this custom build https://github.com/BOINC/boinc/suites/2054202143/artifacts/41415177
and test whether it fixes your issue?

**Comment by martixy** [comment] 2021-04-17 05:20
> Please distinguish exactly what crashes. Your subject line says it's the client, but your description says it's the manager.
> 
> These are separate and distinct programs within the BOINC package. If (as seems likely) it's a Manager problem, please amend the subject line accordingly.

I was under the impression that boinc featured a client-server architecture. The thing that runs the actual computations, `boinc.exe` being the server, and the UI/manager `boincmgr.exe` being the client. What am I missing here? (Regardless it is the manager.)

@AenBleidd It does fix the issue.

**Comment by AenBleidd** [comment] 2021-04-17 08:16
This is a brief architecture of BOINC:
![image](https://user-images.githubusercontent.com/3234209/115106570-e2c4e580-9f65-11eb-9708-8a68bf3394a4.png)

**Closed by AenBleidd** 2021-04-17 08:16 UTC
Labels: C: Manager, R: duplicate

**Comment by davidpanderson** [comment] 2021-04-17 08:38
Nice picture!

**Comment by martixy** [comment] 2021-04-28 06:34
> Looks like a duplicate of #4186, and thus should be fixed by #4198
> @martixy, could you please download this custom build https://github.com/BOINC/boinc/suites/2054202143/artifacts/41415177
> and test whether it fixes your issue?

This build errors out when shutting down the computer however (preventing the shutdown). Since it's not the release build, I'm not sure how to go about reporting this.

**Comment by AenBleidd** [comment] 2021-04-28 08:22
> This build errors out when shutting down the computer however (preventing the shutdown). Since it's not the release build, I'm not sure how to go about reporting this.

@martixy, please create a new ticket and include information about this crash. Thanks
