### ISSUE TITLE
[Android] 7.16.3, empty task list

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#3338] opened 2019-10-16 20:35 UTC
From a user email:

Essentially I've found that it works, although one major bug is that my task list is empty yet I'm certain that work has been downloaded. Judging by a post in the forum I think last year it seems to occur when too much work has been downloaded and the task list is greater then a given number (the forum poster suggested 163, but I cant confirm).

The other small bug is that the tray icon doesn't show at any point (I've tried all setting permutations I can think of) - Its quite minor but along with the above bug its hard to tell whether any work is being done at all.

**Comment by adamradocz** [comment] 2019-10-17 06:48
Same as #2123

**Comment by AenBleidd** [comment] 2019-10-17 08:24
I'm not so sure that this is the same as #2123. The symptoms looks similar but the main problem could be with the process that is killed, that is why there is no tasks shown and no status icon. But need to be additionally verified

**Comment by adamradocz** [comment] 2019-10-17 09:39
The status icon not working on the beta version.

**Comment by AenBleidd** [comment] 2019-10-17 09:43
On my device I have icon shown. Need to be additionally verified.

**Comment by techsy730** [comment] 2019-10-30 00:58
The limit to trigger this bug can now be hit on moderately high chipsets (like Snapdragon 855) and a project that likes to give lots of smaller tasks all at once (such as Einstein@Home)

**Comment by AenBleidd** [comment] 2021-01-23 15:26
Closed as a duplicate of #2123

**Closed by AenBleidd** 2021-01-23 15:26 UTC
Labels: C: Android - Manager, P: Major, R: duplicate, E: to be determined
