### ISSUE TITLE
Don't execute tasks that have already expired

### ISSUE THREAD

**Issue by smoe** [BOINC/boinc#3972] opened 2020-08-15 10:58 UTC
**Describe the problem**
There are some machines that I only run sporadically, say, when it's cold outside. When I fire them up and some tasks have expired in the mean time, then BOINC still computes on them. Just - why - if the project ignores late WUs anyway? So, something like
```
14) -----------
   name: fp200809_pair1221_fnr2_X_fnr_81_8_0001_fragments_abinitio_SAVE_ALL_OUT_1006162_779_0
   WU name: fp200809_pair1221_fnr2_X_fnr_81_8_0001_fragments_abinitio_SAVE_ALL_OUT_1006162_779
   project URL: http://boinc.bakerlab.org/rosetta/
   received: Mon Aug 10 21:49:37 2020
   report deadline: Thu Aug 13 21:49:36 2020
   ready to report: no
   state: downloaded
   scheduler state: scheduled
   active_task_state: EXECUTING
```
that on the 15th of August is executing that should have been delivered on the 13th, is a waste and should not happen.

**Describe the solution you'd like**

Upon start-up, cancel all expired tasks and all those tasks that have an estimated remaining runtime such that their deadline is unlikely to be met.

**Additional context**

This Rosetta task had a deadline of just three days but a runtime of >11 hours. That is a bit difficult at times if a machine is not running 24/7. I'll change projects, but maybe other ideas arise to better match machines and their anticipated runtimes with tasks.

**Comment by smoe** [comment] 2020-08-15 11:05
I just saw that Rosetta offers to shorten the "target run time" of its tasks, which I have now shortened. But this does not affect the nature of my feature request to not execute tasks that have expired.

**Comment by AenBleidd** [comment] 2020-08-15 11:24
Closed as a duplicate of #2366

**Comment by RichardHaselgrove** [comment] 2020-08-15 11:41
The current rule is "abort if unstarted" - the client will do that by itself, without reference to the project server.

I think, if you check back, that you will find that the 'active task' had already started running before you shut the machine down.

Most projects will accept returned tasks after the declared deadline, and many will award credit (depending on the validation schema in operation). Some projects have enabled the explicit 'grace period' available in the BOINC Server configuration, whereby the absolute deadline (shown on the project web site) is significantly later than the one displayed in BOINC Manager.

All of these are compromises, and I think the current set is reasonable, given the range of scientific needs that BOINC is catering for. Perhaps the best solution would be to add a flag to the task specification "useless after deadline", that projects with a real need for rapid processing could add to their templates. I would support your proposal **if it only applied at projects where the need arose**. Perhaps the same could apply to #2366 

P.S. - I started typing this reply before @AenBleidd closed the issue. 'Abort if unstarted' applied here too!

**Comment by smoe** [comment] 2020-08-15 13:39
I was like "this must have been discussed before" but did not find it. Many thanks, @AenBleidd . With tools that are a bit stochastic by nature, say ligand docking, I tend to think that the extra confidence by a redudant work unit is welcome. But when delayed already, and the task possibly being already being sent to a third contributor, it seems reasonable to ask the server if that WU is still wanted. Conversely, maybe the server should have an option to cancel the compute of delayed tasks when their compute has not started, yet. Sigh.

A quick project-specific solution as suggested by @RichardHaselgrove seems very reasonable.

Are there statistics on how many tasks have not been completed in time? And how this depends on the deadline?

**Comment by RichardHaselgrove** [comment] 2020-08-15 15:12
Yes, it has been discussed before. The converse of "abort if unstarted" is "I've started, so I'll finish". People who have invested a significant amount of computation - 50%? 90%? 99%? - in a task tend to get very annoyed if it suddenly gets cancelled: and sometimes job estimates get messed up. If missing the deadline by 5 minutes on a bad job estimate meant that all work done so far was wasted, I suggest that would be worse.

The user can always abort an unwanted task, but they can't resurrect one which has been aborted by the system.

**Comment by AenBleidd** [comment] 2020-08-15 15:17
@smoe, 
> Are there statistics on how many tasks have not been completed in time? And how this depends on the deadline?

you should ask projects directly

**Closed** 2020-08-15 22:50 UTC
Labels: R: duplicate
