### ISSUE TITLE
On Windows 10, boincmgr.exe doesn't appear in the icon box when closed as of 0900 GMT Jan 01 2018 master build.

### ISSUE THREAD

**Issue by ghost** [BOINC/boinc#2284] opened 2018-01-01 11:50 UTC
Hi,

Title says it all.   The problem is that boincmgr.exe stays in the background even when closed.  So in order to bring up boincmgr again, it must be killed in the task manager once, then start from the start menu.  Very troublesome and different from 7.8.3.

**Comment by AenBleidd** [comment] 2018-01-01 12:47
Hello,

What is the build number of Windows do you use?

Could you please also check whether you experience the same behavior using
BOINC release 7.8.3?

I have never see such behavior.

Thanks

Best regards,
Vitalii

Sent via Android

1 янв. 2018 г. 5:20 PM пользователь "maverick6664" <notifications@github.com>
написал:

**Comment by maverick6664** [comment] 2018-01-01 12:57
Hi,

I use Windows 10 build 17046 (Insider Preview) and 16299.15 (Fall Creators update).  BOINC 7.9.0 behaves like this on both of them.  I haven't seen BOINC release 7.8.3 behaves in such a way.

Regards,

**Comment by tristanolive** [comment] 2018-01-09 21:41
On 01/01/2018 07:57 AM, maverick6664 wrote:
> I use Windows 10 build 17046 (Insider Preview) and 16299.15 (Fall
> Creators update). BOINC 7.9.0 behaves like this on both of them. I
> haven't seen BOINC release 7.8.3 behaves in such a way.


Is this a 64-bit build of BOINC? I have experienced similar issues on a
Windows 10 system, but 32-bit builds do not have the same problem.

-- 
Tristan Olive

**Comment by maverick6664** [comment] 2018-01-09 22:54
Hi tristanolive,

Yes, mine is 64-bit.  If 32-bit builds don't have this problem, this may be a bug of vs2013.   Then vs2010 may work.

In 2015 Visual C/C++ was notorious for not being able to compile working fftw.   It compiled, but the binary didn't work.   So it may be the case again.   Or another hope is mingw.

Thank you for notifying it!  But 32bit version is also good, because it can reside 64-bit projects (I don't know about graphics, though).

-Tetsuji

**Comment by maverick6664** [comment] 2018-01-10 02:00
BTW can boinc be built by VS2017 community?   I guess it's worth trying and now am trying :)

-Tetsuji

**Comment by AenBleidd** [comment] 2018-01-10 02:42
Porting BOINC to VS2017 is in progress now.

Best regards,
Vitalii

Sent via Android

10 янв. 2018 г. 7:31 AM пользователь "Tetsuji Maverick Rai" <
notifications@github.com> написал:

**Comment by maverick6664** [comment] 2018-01-10 02:50
Great!   I've just installed VS2017!   Then I don't have to port it.

**Comment by maverick6664** [comment] 2018-01-10 02:53
Great!  Then I don't have to port it?

**Comment by AenBleidd** [comment] 2018-01-10 03:34
Here's a ticket about this: #1832

**Comment by maverick6664** [comment] 2018-01-10 05:51
Oh,

I also tried to build boinc on Fedora 27 Linux which provides Mingw32 and Mingw64 as packages.   However the compiler seems too modern (gcc/g++ version 7.2.0), it gives errors.   It's an irony.

**Comment by Ageless93** [comment] 2018-01-10 07:52
I'm sorry to have to ask, but is it really necessary to be bleeding edge when that means that it takes up one of our coder-developers? Especially seen when we may only have two or three active developers, and still have a backlog of 26 pull requests and 360 other open issues that can be worked on?
If anyone needs to be so bleeding edge, can't they do this conversion themselves? 
Can't we add some documentation on how to port the build code to the next compiler? Or direct someone to add such documentation? 

Because we're not spilling over in coders who need more plus extra on their to-do lists. 
We really have to see where we are and believe you me when I say that we're in dire straits, and if we're to keep this up, this software will probably meet its end this year. Is that where we want to end, just to be bleeding edge?

**Comment by maverick6664** [comment] 2018-01-10 08:11
As for VS2017, it looks like current version (the one I downloaded today is 15.5.17130.2020) supports XP according to [https://developercommunity.visualstudio.com/content/problem/125415/2017-windows-xp-platform-toolset.html](url).  So it will not be the problem.

I found crosscompiling Windows binaries on Linux was not smart, so I abandoned this idea.  Especially Fedora is the most current cutting edge version which might not support Xp.   Personally, I guess cygwin with mingw works fine if libnotify can be installed successfully.   Cygwin is easier and quicker to install than VS2017.

**Comment by AenBleidd** [comment] 2018-01-10 08:59
All versions of VS can support XP but we need to be careful with porting it
to the latest version of VS because some things can work not as expected.

And as Jird already said we have no many active developers and testers to
fix all possible issues.

I'll be back this Friday and start my work on BOINC again. If I'll find
enough time I can take a look at this issue too.

But as soon as there need to be all 3rd party libraries to be recompiled so
we need to keep them somewhere, I'll probably take a closer look to vcpkg
too.

Best regards,
Vitalii

Sent via Android

10 янв. 2018 г. 1:41 PM пользователь "Tetsuji Maverick Rai" <
notifications@github.com> написал:

**Comment by maverick6664** [comment] 2018-01-10 11:35
I fiddled with VS2017 today, but it is not my favorite one.   I like Linux environment much better....

**Comment by RichardHaselgrove** [comment] 2018-01-13 11:07
What was the build status when this bug was first observed? I have seen it with VS2013 debug builds, but not with VS2013 release builds. I suspect it may be a problem with the VS C++ debug runtime (debug builds require debug runtime)

**Comment by JuhaSointusalo** [comment] 2018-01-13 20:19
This bug is in VS2013 release builds too.

As for using MinGW. I tried to build BOINC using mingw-w64 from MSYS2 some
months ago. I discovered that the Autotools build system is not in healthy
state when building for Windows. I hacked it enough to get BOINC to build
only to find out that the client crashes at startup. At that point I put it
in the backburner.

As for VS2017. I have been working on it for a while now. There are some
things that need to be decided on. I'll try to have them written down and
an issue opened for discussion soon.

**Comment by adamradocz** [comment] 2018-11-20 07:59
Is this still an issue?

**Comment by AenBleidd** [comment] 2019-05-23 10:20
Up

**Comment by RichardHaselgrove** [comment] 2019-05-23 11:43
It's still an issue, but not quite as originally described. I have a Windows 10 test machine, still running at version 1809 (the anticipated v1903 hasn't been offered to this machine yet).

The problem remains that by default, the icon for BOINC Manager resides in the 'notification area' of the taskbar, starts minimised, and is hidden except when displaying notification of a notice. Most Windows users can't find it, because they don't even know there's a place to look. Trying to open BOINC Manager manually simply hands focus to the hidden instance without changing its state. That's why people like the OP think that they "must" kill BOINC Manager via the Task Manager.

I wrote up some background and workrounds in the [Client version 7.14.2 release](https://boinc.berkeley.edu/forum_thread.php?id=12676&postid=89589#89589) thread on the BOINC message board.

So far as I know, Microsoft has made it impossible to alter this behaviour with application installer tools - unless anyone knows better?

**Comment by AenBleidd** [comment] 2019-05-23 12:05
If the icon is present but hidden - is not an issue, it is just behavior by design. And it is mostly about User Experience with Windows infrastructure rather than with BOINC itself. Here's the corresponding discussion: #2954
So this particular ticket is about an issue when icon is not present in tray at all

**Comment by RichardHaselgrove** [comment] 2019-05-23 12:21
At no point does the OP actually say that he has opened the notification area 'show hidden icons' and found the BOINC icon to be either present or missing - unless that's what he meant by 'icon box'.

My feeling is that the original issue could be ascribed to a bug in the 'insider preview' version of windows he was running: the subsequent discussion of build tools is a separate issue.

I think we can close this ticket, but we should continue to monitor the behaviour of each subsequent service pack (sorry, 'six monthly release') for Windows 10, and try to find ways of either changing icon behaviour through the build, or educating users, or both.

**Comment by AenBleidd** [comment] 2019-05-23 12:29
Closing this as WorksForMe.
Please feel free to reopen once this issue will happen again.

**Closed by AenBleidd** 2019-05-23 12:29 UTC
Labels: C: Manager, P: Trivial, R: worksforme, E: to be determined
