### ISSUE TITLE
Single core task will not run alongside a multicore task

### ISSUE THREAD

**Issue by Dave-catcher** [BOINC/boinc#5254] opened 2023-05-27 14:50 UTC
BOINC 7.23.0 compiled from source.
Ubuntu 23.04
Cpu Ryzen 7 16 core.
32GB RAM 54GB Swap
Running a single core task from CPDN I thought i would run some Amicable Numbers tasks alongside it. These downloaded as 7 core tasks. (I had BOINC set to use 7 cores. Even after increasing the number of cores available to BOINC to 8 and then to 9 the Ssingle core task from CPDN would not start unless i paused all the multi-core tasks. It would then run but if I resumed a multicore task the single core one would stop after about 1 or 2 minutes.

**Comment by AenBleidd** [comment] 2023-05-27 14:56
This is the expected default behavior.
If you want to limit number of cores for multithreaded tasks to let BOINC run it alongside with singlethreaded tasks, you should configure every particular project as described here:
https://boinc.berkeley.edu/forum_thread.php?id=13170

**Comment by RichardHaselgrove** [comment] 2023-05-27 15:03
That thread has my suggested resolution in it, but there's one additional wrinkle: the core and thread counts for the MT task are only applied when the task **first** starts (from the beginning): they aren't changed by a pause and restart.

**Comment by Dave-catcher** [comment] 2023-05-27 15:11
Thanks Richard. The bit I don't understand is that if I increase the cores available after the multicore task has started, the CPDN one still stops within two minutes after an Amicable Numbers one is restarted.

**Comment by RichardHaselgrove** [comment] 2023-05-27 15:23
Is anything useful logged, perhaps with <cpu_sched_debug>? Otherwise, we probably need to explore the whole configuration 'in the round', including preferences and all app_config.xml files - that might be better done on one of the message boards we both use, at least for the exploration phase. If we find anything, it should be reported here, of course.

I don't know Amicable Numbers well, in particular whether they use the form of MultiThreading controlled by --nthreads, as assumed in BOINC documentation. Maybe I should try one.

**Comment by Dave-catcher** [comment] 2023-05-27 15:24
I will carry out the further investigations you suggest Richard.

**Comment by RichardHaselgrove** [comment] 2023-05-28 10:43
We have been discussing this further in https://boinc.berkeley.edu/forum_thread.php?id=14994

So far, I've got as far as

Sun 28 May 2023 11:25:55 BST | NumberFields@home | [cpu_sched_debug] all CPUs used (8.00 >= 6), skipping wu_sf3_DS-16x271-21_Grp883275of1000000_0
Sun 28 May 2023 11:25:56 BST |  | [cpu_sched_debug] Request CPU reschedule: application exited
Sun 28 May 2023 11:25:56 BST |  | [cpu_sched_debug] final job list:
Sun 28 May 2023 11:25:56 BST | Einstein@Home | [cpu_sched_debug] 0: LATeah4021L07_940.0_0_0.0_34824363_2 (MD: no; UTS: yes)
Sun 28 May 2023 11:25:56 BST | Einstein@Home | [cpu_sched_debug] 1: LATeah4021L08_1116.0_0_0.0_6637911_0 (MD: no; UTS: no)
Sun 28 May 2023 11:25:56 BST | Amicable Numbers | [cpu_sched_debug] 2: amicable_10_21_2426_1685252702.324398_984_1 (MD: no; UTS: yes)
Sun 28 May 2023 11:25:56 BST | Amicable Numbers | [cpu_sched_debug] 3: amicable_10_21_2426_1685252702.324398_998_1 (MD: no; UTS: yes)
Sun 28 May 2023 11:25:56 BST | NumberFields@home | [cpu_sched_debug] 4: wu_sf3_DS-16x271-21_Grp883275of1000000_0 (MD: no; UTS: no)
Sun 28 May 2023 11:25:56 BST | NumberFields@home | [cpu_sched_debug] 5: wu_sf3_DS-16x271-21_Grp881899of1000000_0 (MD: no; UTS: no)
Sun 28 May 2023 11:25:56 BST | NumberFields@home | [cpu_sched_debug] 6: wu_sf3_DS-16x271-21_Grp890082of1000000_0 (MD: no; UTS: no)
Sun 28 May 2023 11:25:56 BST | NumberFields@home | [cpu_sched_debug] 7: wu_sf3_DS-16x271-21_Grp889806of1000000_0 (MD: no; UTS: no)
Sun 28 May 2023 11:25:56 BST | NumberFields@home | [cpu_sched_debug] 8: wu_sf3_DS-16x271-21_Grp890572of1000000_0 (MD: no; UTS: no)
Sun 28 May 2023 11:25:56 BST | NumberFields@home | [cpu_sched_debug] 9: wu_sf3_DS-16x271-21_Grp898646of1000000_0 (MD: no; UTS: no)
Sun 28 May 2023 11:25:56 BST | Einstein@Home | [cpu_sched_debug] scheduling LATeah4021L07_940.0_0_0.0_34824363_2
Sun 28 May 2023 11:25:56 BST | Einstein@Home | [cpu_sched_debug] scheduling LATeah4021L08_1116.0_0_0.0_6637911_0
Sun 28 May 2023 11:25:56 BST | Amicable Numbers | [cpu_sched_debug] scheduling amicable_10_21_2426_1685252702.324398_984_1
Sun 28 May 2023 11:25:56 BST | Amicable Numbers | [cpu_sched_debug] scheduling amicable_10_21_2426_1685252702.324398_998_1
Sun 28 May 2023 11:25:56 BST | NumberFields@home | [cpu_sched_debug] all CPUs used (8.00 >= 6), skipping wu_sf3_DS-16x271-21_Grp883275of1000000_0
Sun 28 May 2023 11:25:56 BST | Einstein@Home | Starting task LATeah4021L08_1116.0_0_0.0_6637911_0
Sun 28 May 2023 11:25:56 BST | Einstein@Home | [cpu_sched] Starting task LATeah4021L08_1116.0_0_0.0_6637911_0 using hsgamma_FGRPB1G version 128 (FGRPopencl2Pup-nvidia) in slot 1
Sun 28 May 2023 11:25:56 BST |  | [cpu_sched_debug] enforce_run_list: end

That's definitely an over-commit bug, even if not exactly the same as Dave first reported. Investigations will continue.

**Comment by RichardHaselgrove** [comment] 2023-05-28 11:29
Confirmed in the client emulator - Scenario 201, Simulation 1.

**Comment by AenBleidd** [comment] 2023-05-28 11:41
@davidpanderson, could you please take a look?

**Comment by RichardHaselgrove** [comment] 2023-05-28 12:27
The specific problem in this case seems to be starting the second MT task - that's the moment when the CPU becomes overcommitted. I've noticed before that when a CPU becomes overcommitted because a MT task is started while single-threaded CPU tasks are running, it takes until the next cpu_sched cycle (1 minute later) before the overcommittment is resolved by pre-empting running tasks, and confirmed that again today:
```
Sun 28 May 2023 11:09:50 BST | NumberFields@home | Computation for task wu_sf3_DS-16x271-21_Grp890573of1000000_0 finished
Sun 28 May 2023 11:09:50 BST | Amicable Numbers | [cpu_sched] Starting task amicable_10_21_2426_1685252702.324398_984_1 using amicable_10_21 version 300 (mt) in slot 2
Sun 28 May 2023 11:10:50 BST | NumberFields@home | [cpu_sched] Preempting wu_sf3_DS-16x271-21_Grp883275of1000000_0 (left in memory)
Sun 28 May 2023 11:10:50 BST | NumberFields@home | [cpu_sched] Preempting wu_sf3_DS-16x271-21_Grp881899of1000000_0 (left in memory)
```

**Comment by Dave-catcher** [comment] 2023-05-28 12:32
The thing I am seeing is that on increasing the number of cores available to BOINC the single core task doesn't restart and the event log seems to suggest that despite what I see in the manager, the client still thinks (in my case) it should only be using six cores even though I have increased the number available to 8.

**Closed** 2023-06-15 18:43 UTC
Labels: C: Client - Scheduler Policy, T: Defect, Validate
