### ISSUE TITLE
Window previews on taskbar do not correspond to real windows

### ISSUE THREAD

**Issue by kotenok2000** [BOINC/boinc#4620] opened 2022-02-02 17:50 UTC
**Describe the bug**
When i open logging window and try to switch windows between  BOINC Manager window and BOINC Manager - Event Log window windows are switched.
**Steps To Reproduce**
1. Enable taskbar grouping
2. Open boinc manager 
3. Open event log.
4. Try to switch between event log and main window with task bar previews.
5. Displayed window titles and previews do not correspond to real windows.

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/8822292/152209137-0235fc40-aa50-4b7e-b90d-03b5b7a85f8c.mp4

**System Information**
 - OS: Microsoft Windows [Version 10.0.22000.469]
 - BOINC Version: 7.16.20

**Additional context**

**Comment by AenBleidd** [comment] 2022-02-02 17:53
Closed as a duplicate of #1741

**Closed by AenBleidd** 2022-02-02 17:53 UTC
Labels: C: Manager, R: duplicate
