### ISSUE TITLE
GUI Scrollbar glitch on left panes of Projects tab and Tasks tab

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1031] opened 2015-02-04 04:14 UTC
**Reported by JacobKlein on 30 May 41244833 08:26 UTC**
I have noticed 2 instances of a small GUI Scrollbar glitch, and have found ways to reproduce it.  Below are the steps to reproduce the 2 issues.
- 1-1 Go to Projects tab, and click a project that has several "Web Sites" buttons on the left pane, like World Community Grid.
- 1-2 Make window sufficiently big so that there is whitespace below the list of Projects.
- 1-3 Make window sufficiently small so that there is a scrollbar in the left pane.
- 1-4 Click the Tasks tab, then click the Projects tab, then click into the whitespace below the list of Projects.
- 1-5 The result is a left pane that has a scrollbar, but the pane itself doesn't need a scrollbar, and the pane data overlays the scrollbar.
  Expected result: No scrollbar in left pane.
- 2-1 Go to Tasks tab, and click a task that has several "Web Sites" buttons on the left pane, like a World Community Grid task.
- 2-2 Make window sufficiently big so that there is whitespace below the list of active tasks.
- 2-3 Make window sufficiently small so that there is a scrollbar in the left pane.
- 2-4 Click the Projects tab, then click the Tasks tab, then click into the whitespace below the list of active tasks.
- 2-5 The result is a left pane that has a scrollbar, but the pane itself doesn't need a scrollbar, and the pane data overlays the scrollbar.
  Expected result: No scrollbar in left pane.

I'll attach some screenshots, but hopefully the above 2 examples are enough data to replicate and fix this bug.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1055

**Comment by ChristianBeer** [comment] 2017-04-07 11:26
Can't reproduce with 7.6.33 must have been fixed in the past.

**Closed by ChristianBeer** 2017-04-07 11:26 UTC
Labels: C: Manager, P: Minor, T: Defect
