### ISSUE TITLE
BOINC Manager GUI not rendered correctly in advanced mode

### ISSUE THREAD

**Issue by hakuseki** [BOINC/boinc#3545] opened 2020-03-30 07:32 UTC
**Describe the bug**
On Mac with Dark mode enabled, the GUI is not rendered correctly

**Steps To Reproduce**
1. Latest BOINC
2. Dark mode ON

**Expected behavior**
The GUI must be readable in Advanced mode

**Screenshots**

<img width="877" alt="BOINC_Manager_and_New_Issue_·_BOINC_boinc" src="https://user-images.githubusercontent.com/5478862/77886263-d8578100-7268-11ea-8f83-4d93e6287ebb.png">
<img width="809" alt="BOINC_Manager" src="https://user-images.githubusercontent.com/5478862/77886278-e1e0e900-7268-11ea-8203-12f6c1d1dece.png">
<img width="567" alt="BOINC_-_Computing_preferences_and_BOINC_Manager_and_New_Issue_·_BOINC_boinc" src="https://user-images.githubusercontent.com/5478862/77886298-ead1ba80-7268-11ea-9613-5609b9967487.png">

**System Information**
 - OS: Mac 10.15.4
 - BOINC Version: 7.14.3

**Additional context**

**Comment by AenBleidd** [comment] 2020-03-30 08:21
Duplicate of #2917

**Closed by AenBleidd** 2020-03-30 08:21 UTC

**Comment by hakuseki** [comment] 2020-03-30 08:25
The previous version was rendering the GUI fine although not using the OS theme settings.
This version has a bug

**Comment by AenBleidd** [comment] 2020-03-30 09:00
BOINC Manager currently has no Dark Mode support. Once this feature will be
implemented, then it will be reasonable to post issues like this.
Currently, all this is just a different symptoms of the same problem.There
was no GUI changes between versions, so it is more likely wxWidgets that
was updated.
Best regards,
Vitalii Koshura


пн, 30 мар. 2020 г. в 10:25, Mikael Andersson Wigander <
notifications@github.com>:

**Comment by hakuseki** [comment] 2020-03-30 09:08
OK, makes sense! 

Thx

**Comment by CharlieFenton** [comment] 2020-03-31 10:50
I have released BOINC 7.14.4 for Macintosh which tells the OS to not use dark mode for BOINC even when Dark Mode is generally selected. This workaround allows BONC to be usable under Dark Mode until BOINC can be updated to fully support dark mode.
