### ISSUE TITLE
Enable the BOINC app movable to SD card on android phone

### ISSUE THREAD

**Issue by fckwan** [BOINC/boinc#3441] opened 2020-01-28 16:45 UTC
**Describe the problem**
Please enable the BOINC app movable to SD card on android phone. So user can free up the internal memory on their android phone.

**Describe the solution you'd like**
http://programmerguru.com/android-tutorial/how-to-create-android-app-with-movable-to-sd-card-feature/

It is very simple to enable move to SD card feature in Android applications, all you need to do is specify the installLocation attribute in Android manifest as ‘auto’. Please refer to the link above.

**Additional context**
https://play.google.com/store/apps/details?id=com.a0soft.gphone.app2sd&hl=en

I use App Mgr III to move the other apps to SD card. I do not need to root an android device to use this app and move to SD card functionality.

The app is free with ads.

**Comment by AenBleidd** [comment] 2020-01-28 17:01
It's impossible to do on non-rooted device because SD card by default has no execution permissions.
Closed as a duplicate of #1599

**Closed by AenBleidd** 2020-01-28 17:01 UTC
Labels: C: Android - Manager, R: duplicate
