### ISSUE TITLE
GPU Throttling

### ISSUE THREAD

**Issue by lancerkind** [BOINC/boinc#3760] opened 2020-05-25 02:29 UTC
**Describe the problem**
When allowing GPU, it really heats up the laptop and I'm not willing to wear out my laptop fans. I'd like to be able to throttle GPU computing just BOINC does for CPU.  I'm using a MacBookPro 15" 2019.

**Describe the solution you'd like**
Ideally, throttle based of fan speed.  Second to that, give me a "percentage of GPU" to allow to use and I'll work out the percentage based on what I hear my fans doing.

**Comment by AenBleidd** [comment] 2020-05-25 02:38
Closed as a duplicate of #799.
Also, here's a reason why this should not be done: https://github.com/BOINC/boinc/issues/1451#issuecomment-435188395

**Closed by AenBleidd** 2020-05-25 02:38 UTC
Labels: C: Client - Daemon, R: duplicate
