### ISSUE TITLE
BOINC Manager Crash - Quickly alternate clicks on tray icon

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1299] opened 2015-02-04 06:10 UTC
**Reported by JacobKlein on 30 Dec 43661007 21:55 UTC**
I went to open the BOINC window, but instead of double-left-clicking the tray icon, I accidentally also included a right-click in the mix.
Then BOINC Manager crashed.

Steps to reproduce:
- Open BOINC Manager (It doesn't matter if the window is open or not, I believe)
- On the BOINC system tray icon, quickly right-click-then-immediately-left-click
- Do that action a few times quickly, and BOINC Manager should crash.

(Stacktrace was removed by Christian Beer for brevity)

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1328

**Comment by Ageless93** [comment] 2017-08-17 20:48
Is this reproducible with BOINC 7.6 or 7.8?

**Comment by Ageless93** [comment] 2017-10-24 16:12
Testing again with 7.8.3, still cannot reproduce a crash. All it does is open the right-click dialog and sometimes the exit dialog window. Closing for now.

**Closed by Ageless93** 2017-10-24 16:12 UTC
Labels: C: Manager, P: Minor, T: Defect
