### ISSUE TITLE
Android CPU recognition

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1477] opened 2016-01-26 08:08 UTC
(from user email)

It would be nice that BOINC shows the model of the smartphone. I have a LG G4 H815 (Qualcomm Snapdragon 808 MSM8992) so WuProp@Home would collect some data of Android processors. I have also a Nexus 7 2013 (Qualcomm Snapdragon S4 Pro APQ8064) and I'll buy a Asus ZenFone Zoom (Intel Atom Z3590). Please let BOINC recognize the smartphone processor.

---

I have a LG G4 H815 with Android 6.0 and the app doesn't recognize the CPU. In every Account page of the projects, it shows only ARM 6 cores. It should be AArch64 Processor rev..... and so on. Please, solve this problem.

**Comment by ChristianBeer** [comment] 2017-04-11 15:38
closing as duplicate of #1597

**Closed by ChristianBeer** 2017-04-11 15:38 UTC
Labels: C: Android - Manager, T: Enhancement
