### ISSUE TITLE
 Boinc does not download GPU projects, even if it is set to use the GPU.

### ISSUE THREAD

**Issue by StiwyBomba** [BOINC/boinc#4199] opened 2021-02-16 23:23 UTC
BOINC has been set up so that:
1) use the GPU;
2) that the GPU was always active, even with the <use_all_coprocessors> command;
3) That it received projects that use the GPU;
The thing is, I reinstalled BOINC 3 times first with everything enabled, the second time I didn't use the GPU (because I was wrong to press the button) and then with everything enabled again. My doubt is that if, with the second reinstall, the settings not to use the GPU could have been memorized, even if I then reinstalled it with everything operational? This is because the Milkyway @ home projects with GPU, I ran them before, now not anymore even if I have the possibility to manage the gpu in: always active, according to preferences or suspend. I don't know what to do, recommend something, thanks.

I would have expected that with my preferences I would receive the requested projects with GPU and CPU.

System information:
OS: Win 10 Pro
Boinc version: latest, 7.16.11 (x64)

PS: I am an Italian, I apologize if I made some orthosyntactic error, I don't know how to speak English very well.

**Comment by AenBleidd** [comment] 2021-02-16 23:52
@StiwyBomba, could you please share info from `stdoutae.txt` file? It's located in BOINC Data directory (default path is `C:\ProgramData\BOINC\

**Comment by StiwyBomba** [comment] 2021-02-17 00:17
[stdoutdae.txt](https://github.com/BOINC/boinc/files/5992395/stdoutdae.txt)

**Comment by AenBleidd** [comment] 2021-02-17 00:37
You have your Milkyway added twice:
```
16-Feb-2021 19:27:30 [Milkyway@Home] Requesting new tasks for NVIDIA GPU
16-Feb-2021 19:27:33 [Milkyway@Home] Scheduler request completed: got 0 new tasks
16-Feb-2021 19:27:33 [Milkyway@Home] You are attached to this project twice.  Please remove projects named Milkyway@Home, then add http://milkyway.cs.rpi.edu/milkyway/
```
I see you use GRC pool. You should ask on their Discord server why you have the same project added twice.

And I don't see an obvious reason why you don't receive tasks for AmicableNumbers: looks like you cancelled one and now you blocked for some time

**Comment by StiwyBomba** [comment] 2021-02-17 00:44
ok, many thanks for the advice.  I canceled a task because it was using the CPU, in fact the program that processes on the GPU did not download.  I don't have a powerful GPU I know, but I'm very fond of Boinc and I want to contribute as much as possible.

**Comment by AenBleidd** [comment] 2021-02-17 01:17
@StiwyBomba, regarding Amicable Numbers, looks like your GPU is too old for this project:
https://sech.me/boinc/Amicable/forum_thread.php?id=79

**Comment by StiwyBomba** [comment] 2021-02-17 10:23
Hello, I have some news regarding yesterday's problem, in a nutshell today I reinstalled BOINC deleting all folders, reinstalled the NVIDIA drivers and synchronized everything again, I still compare the notification of the double addition by Milkyway @ Home but now i receive Amicable Numbers projects also on GPU. There was probably something that was preventing BOINC from reading the GPU, however now everything works and I'm happy.

**Comment by talregev** [comment] 2021-02-19 05:43
Try another project like [Einstein@home](https://einsteinathome.org/), it always use my gpu.

**Comment by AenBleidd** [comment] 2021-02-19 11:32
As far as I understood, the issue is already solved.
Closing this for now.
Feel free to reopen in case the issue still exists.

**Closed by AenBleidd** 2021-02-19 11:32 UTC
Labels: C: Client - Daemon, R: invalid
