### ISSUE TITLE
[Linux] BOINC Manager does not stop running tasks when closing as requested

### ISSUE THREAD

**Issue by Vulpine05** [BOINC/boinc#5629] opened 2024-05-20 01:56 UTC
**Describe the bug**
I have a fresh installation of Ubuntu 22.04 with BOINC 8.01.  I am able to get BOINC to attach to a project and run successfully. However, trying to close BOINC and stop running tasks when closing BOINC is not straightforward.  When closing the Manager while enabling "Stop running tasks when existing the BOINC Manager", the Manager closes with no problems, but the tasks (and I assume the Client) still run in the background.

**Steps To Reproduce**
1. Clean install of BOINC.
2. Attach a project, let work run.
3. File->Exit BOINC Manager
4. Click on "Stop running tasks when existing the BOINC Manager", then OK.
5. Observe that tasks still run, even if you wait for a several minutes.

**Expected behavior**
The Client should close and stop tasks.  Otherwise, if this option is not available due to user permissions, then it would be great if a dialogue box popped up stating that the user doesn't have permission to close the Client.

**System Information**
 - OS: Ubuntu 22.04
 - BOINC Version: 8.01

**Additional context**
I have also tried adding my user name to the BOINC group (via sudo usermod -a -G boinc $USER), but the same problem would occur.

**Comment by AenBleidd** [comment] 2024-05-22 07:29
Closed as a duplicate of #5601

**Closed by AenBleidd** 2024-05-22 07:29 UTC
Labels: C: Manager, P: Minor, R: duplicate, T: Defect
