### ISSUE TITLE
project preference to set number of used cpu's

### ISSUE THREAD

**Issue by UweBeckert** [BOINC/boinc#1414] opened 2015-10-20 08:24 UTC
Users of yafu@home and RNA World requests an option to limit the number of used CPU for multi core systems and multi threaded apps per project.
E.g. they want to use on a 8 core system only 6 cores for yafu@home and use the remaining 2 cores for other boinc projects.

**Comment by bsegal** [comment] 2015-10-20 12:31
On behalf of CERN's BOINC projects using virtualization (vLHC@home, etc.) I'd like to support Uwe's request. More precisely we would like a volunteer to be able to select the number of cores allocated (per task) for a specific project/application (e.g. in project preferences), without implicitly offering these cores to all attached project tasks. The number of cores should be able to be specified explicitly, not just as a % of the hosts's total number of CPU's. The default will of course remain as 1 CPU.

This would be used to support multi-threaded apps (either within a VM or natively), and multiple containers running inside suitably configured VM's.

**Comment by marius311** [comment] 2015-10-20 12:44
Cosmology@home users have also requested this so I echo support. In the meantime one of our users found a solution reproduced here http://beta.cosmologyathome.org/faq.php#how-can-i-limit-the-number-of-cpus-used

**Comment by bsegal** [comment] 2015-10-20 14:18
Thanks Marius! I need to clarify my request. Currently if I want to use 4 CPU's on any app I can set in my BOINC preferences "On multiprocessors, use at most <4> processors" but this works for ALL projects. There is no per-project or per-app option for this today. I want to be able to set the number of CPU's for selected project(s) WITHOUT affecting other projects I'm attached to. In addition I'd like to be able to set the DEFAULT number of CPU's used by all my other attached projects (typically to 1). This default is currently set to the full number of CPU's in my system, which has side effects like getting multiple tasks from certain projects, which in turn forces the use of scripts like Crystal Pellet's which you referred to.

**Comment by ChristianBeer** [comment] 2015-10-25 13:22
Test message, please ignore.

**Comment by Ageless93** [comment] 2017-08-17 21:43
Is this still being asked for?

**Comment by AenBleidd** [comment] 2022-10-07 18:35
Since this was not asked last 5 years and there is a possibility to achieve the same using anonymous platform, I'm closing this as 'wontfix' for now

**Closed by AenBleidd** 2022-10-07 18:35 UTC
Labels: C: Client - Scheduler Policy, P: Minor, R: wontfix, T: Enhancement, Feature Request
