### ISSUE TITLE
BOINC Shut Down Problem

### ISSUE THREAD

**Issue by AlanDJordan** [BOINC/boinc#1385] opened 2015-08-29 06:18 UTC
I am happily running the latest version of BOINC (7.2.42 64bit) under Ubuntu Linux 15.04. HOWEVER, when I shut down BOINC Manager by selecting File/Exit BOINC (because as reported elsewhere, the Close Window Button does not shut down BOINC), the Project Tasks do NOT shut down, but remain running! 

I assume that there is/are Linux Terminal Command(s) which can stop the Project Tasks running, but I don't know how to do this. Consequently, the only way I can stop the Project Tasks running is to shut down or restart my PC.

NOTE that the version of BOINC supplied via the Ubuntu Software Centre does NOT suffer from this problem. However, I prefer to run the latest version of BOINC in order to benefit from the latest features and bug fixes. I wonder whether this problem would be fixed IF it was possible to install the latest version of BOINC via the Ubuntu Software Centre, as is possible with some other Linux Applications not provided by Ubuntu? However, if this is possible, I don't know how to do it.

**Comment by elfring** [comment] 2015-09-16 14:37
>…, the Project Tasks do NOT shut down, but remain running! 

Did you tick the check box "Stop running tasks when exiting the BOINC Manager" in [the dialogue "BOINC Manager - Exit Confirmation"](https://boinc.berkeley.edu/wiki/BOINC_Manager#The_BOINC_Manager_icon_and_menu "The BOINC Manager menu")?

**Comment by AlanDJordan** [comment] 2015-09-16 16:53
Yes, I learnt many years ago that you have to select this option in 
order to close BOINC. Unfortunately it now has no effect.

Alan Jordan


-----Original Message-----

**Comment by ChristianBeer** [comment] 2015-09-16 17:51
The current version in Ubuntu 15.04 (Vivid Vervet) is 7.4.23 and 7.6.2 would be available through a ppa. So you could update through the Software Center and fix it that way.

If you prefer to use the Berkeley BOINC please tell me where you installed the Package to. I'll try to reproduce it locally using a standard Ubuntu 15.04.

**Comment by AlanDJordan** [comment] 2015-09-17 09:53
Christian,

Many thanks for your Email.

I would be happy to install the latest RECOMMENDED version of BOINC 
Manager (7.2.42) via the Ubuntu Software Centre, as I assume doing 
things this way will be likely to ensure better integration with Ubuntu 
Linux, However, I do NOT know which PPA Address to use; if you can help 
with this I would be grateful (I know how to set up a new PPA in 
Ubuntu, given the relevant address).

I notice from your Email, and can confirm, that the Ubuntu Software 
Centre currently installs Version 7.4.23, which would APPEAR to be a 
later version of BOINC Manager than the RECOMMENDED version (7.2.42) 
available from the Berkeley Website?  I find this confusing, as I seem 
to remember trying the Ubuntu Software Centre version, and getting the 
(usual) message that a newer Version is available! I am also confused 
because I can't find Version 7.6.2 available on the Berkeley BOINC 
Download Page! Perhaps you can explain.

NOTE - I only ever use the RECOMMENDED versions of BOINC, NOT the 
Development versions.

At present, I download the RECOMMENDED Berkeley BOINC from the Website, 
and extract it to a BOINC Folder in my Home Directory, and run it from 
there. This has always worked perfectly OK with previous versions of 
Ubuntu, but 15.04 leaves the Project Tasks running, even though I am 
always careful to shut down BOINC Manager via the File/exit BOINC Menu 
Option.

Regards,

Alan Jordan


-----Original Message-----

**Comment by ChristianBeer** [comment] 2015-09-17 10:50
A specific version of BOINC gets recommended by Berkeley if enough test reports are received for the particular platform. For Linux this has always been low. I assume that most Linux users (myself included) install BOINC through the Software Center and don't care about the Berkeley version because they trust the maintainer of the distribution to supply the latest stable version.

Though 7.4.22 is marked as development version for Linux it is very stable. 7.6.9 is marked recommended for Windows but not Linux. That doesn't mean it's not stable on Linux too we just haven't received enough feedback from Linux testers. But so far there is also no negative feedback.

So you can safely update to 7.4.23 and consider this stable (recommended). I currently use 7.6.9 on Debian and hadn't had problems with it. The PPA for Ubuntu is this: https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/boinc

**Comment by AlanDJordan** [comment] 2015-09-18 06:06
Christian,

Many thanks for your Email, which is very helpful, particularly the 
information regarding how the Development and Stable (recommended) 
Versions of BOINC are determined.

I have just tried the Software Centre Version of BOINC, which basically 
runs OK, and will shut the Project Tasks down when exiting BOINC 
correctly, but introduces two other Issues which cause me concern. I 
will take these up via the Ubuntu Forums, but in the meantime I am not 
happy using this option.

I will try the PPA you suggest, and see if this helps.

Regards,

Alan Jordan


-----Original Message-----

**Closed** 2017-04-11 14:37 UTC
Labels: C: Manager, P: Minor, T: Defect
