### ISSUE TITLE
Commas in usernames break private messages

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#572] opened 2015-02-04 00:40 UTC
**Reported by ToeBee on 8 Dec 38260853 16:00 UTC**
Commas are used on the "Send Private Message" page (pm.php?action=new) to allow you to send messages to multiple recipients. However this causes a problem if the user you are trying to send a message to has a comma in their username. It tries to find two users to send the message to. As a workaround you can remove the name and only use the user ID but when you click on a user's name from the forum both are included. 

Either a different delimiter needs to be used or the username needs to be enclosed in something or maybe commas in usernames should be escaped. Currently the username is enclosed in parens but the parsing of usernames apparently doesn't take them into account. Also, what if a username has parens in their name? Should some of these characters be disallowed?

Migrated-From: http://boinc.berkeley.edu/trac/ticket/594

**Comment by romw** [comment] 2015-02-04 16:01
**Commented by davea on 5 Nov 38260921 21:46 UTC**
The easiest thing to do is require that commas in user names be escaped with \
(and to do this when prepopulating the field).
This will require using preg_split() instead of explode()
in pm.php line 169.
I don't have time to do this right now; patches welcome.

**Comment by Ageless93** [comment] 2017-08-17 13:41
Is this still an issue?

**Comment by Ageless93** [comment] 2017-10-24 13:50
Tested on the BOINC forums with my own name, no problem found. Therefore closing this issue.

**Comment by tristanolive** [comment] 2017-10-24 14:06
This is a fringe issue, but should probably remain open. Either commas should be disallowed in usernames or they should not be used as delimiters in user lists. For reference, we have been working through a similar issue with Drupal private messages (see 1cbeb31), replacing spaces in usernames with non-breaking spaces so that spaces can be used as delimiters.

**Comment by JuhaSointusalo** [comment] 2018-11-04 20:19
For user friendliness I think it would be best if Drupal and BOINC basic web code used the same way to handle commas in user names.

**Comment by Delizald** [comment] 2023-11-14 14:41
I'm checking this one 
![image](https://github.com/BOINC/boinc/assets/5884968/f633bad7-aad1-4a88-b5b4-2d850e4be35c)

**Comment by Delizald** [comment] 2023-11-14 21:23
I was looking at the option of replacing the explode function to use this instead` preg_split('/,\s/', $input_line);`:

![image](https://github.com/BOINC/boinc/assets/5884968/e414bcc6-bf99-454d-a9a6-f49c21fe652c)

**Comment by davidpanderson** [comment] 2023-11-14 21:53
User names can contain ', ' so this doesn't work.

However, user names can't contain newline.

**Comment by Delizald** [comment] 2023-11-15 03:30
@davidpanderson May I have a sample string? 
I'm unfamiliar with sending messages over Boinic  and by reading the code I though that on line 235 of pm.php the $to variable could contain a list of recipients separated by a blank space as in "userr1, user,2, user3"
if that's the case, in theory my suggested change should work as we can appreciate the reg_split function returns an array of 3 users:


![image](https://github.com/BOINC/boinc/assets/5884968/ffb2840c-f7ba-47f1-8141-6ce8e17d985d)

**Comment by Rytiss** [comment] 2023-11-15 06:47
You don't want to require users to follow certain formatting. Spaces after commas may be common to us, but a lot of people type punctuation in a non-standard way: space, comma, space; space, comma; no space at all; doublespace. You want to cover them all.

David's idea about newlines makes sense; you could convert the PM input field to a textarea (possibly with just a tiny bit of javascript so that it doesn't take up a lot of space when you start, e.g. 2 lines, but once you start adding newlines it grows vertically), and then require separation of usernames by newlines - that is much harder to fudge by the user.

**Comment by davidpanderson** [comment] 2023-11-15 07:49
The issue is that user names themselves may contain commas and/or spaces

**Closed** 2024-07-26 22:06 UTC
Labels: C: Web - Private Messages, P: Minor, R: fixed, T: Defect, E: 1 day
