### ISSUE TITLE
Suggestion: allow a PARTIAL suspension while the computer is in use

### ISSUE THREAD

**Issue by MaxOfS2D** [BOINC/boinc#1443] opened 2015-12-02 10:37 UTC
Right now it's either "don't suspend and run with the same settings as when you're not using your computer", or "suspend completely while in use". I think being able to have separate settings for when the computer is in use could be pretty useful. For example I do 7 cores / 90% when not in use, but I'd like to still do 2 cores / 50% while still in use. (and all of that on "low" priority)

**Comment by ChristianBeer** [comment] 2017-04-11 15:22
duplicate of #41

**Closed by ChristianBeer** 2017-04-11 15:22 UTC
