### ISSUE TITLE
Bug installing BOINC 7.16.1 on Linux

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#3250] opened 2019-08-14 15:43 UTC
**Describe the bug**
There seems to be an error in the latest boinc-client 7.16.1 build. Upgrading an existing installation goes well, but installing 7.16.1 on a clean machine fails. It seems to fail on the creation of the 'boinc' user:

usermod: group 'render' does not exist
Could not assign boinc user to group 'render'
invoke-rc.d: syntax error: unknown option "--skip-systemd-native"
dpkg: error processing package boinc-client (--configure):
installed boinc-client package post-installation script subprocess returned error exit status 1

**System Information (please complete the following information):**
 - OS: Ubuntu Server 18.04.3 LTS
 - BOINC Version: 7.16.1

**Additional context**
This version was obtained from costamagnagianfranco/boinc repository

**Comment by adamradocz** [comment] 2019-08-15 09:46
I have an issue installing the v7.16.1 too on docker. Same costamagnagianfranco/boinc repo.
The original Ubuntu repo works fine.

Here's the console log:
```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
usermod: group 'render' does not exist
Could not assign boinc user to group 'render'.
invoke-rc.d: syntax error: unknown option "--skip-systemd-native"
dpkg: error processing package boinc-client (--configure):
 installed boinc-client package post-installation script subprocess returned error exit status 1
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 boinc-client
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Germano0** [comment] 2019-08-16 13:06
I think you should open a bugreport on Ubuntu bug reporting system

**Comment by smoe** [comment] 2019-08-27 08:58
@adamradocz, could you please install the package "dialog" prior to boinc-client (in a separate invocation of apt)? I mean, somewhat amazingly neither the Debian/Ubuntu-typical dialog system works nor the readline. We hence either miss a pre-install dependency (thought Ubuntu would always ship with that, may be something special because of that minimal docker image) or something is weird with the terminal.

**Comment by adamradocz** [comment] 2019-08-27 12:52
@smoe, I got the same error message.

**Comment by smoe** [comment] 2019-08-27 13:01
It says "TERM is not set" - could you please set that one? I found https://andykdocs.de/development/Docker/Fixing+the+Docker+TERM+variable+issue/ which seems promising.

**Comment by adamradocz** [comment] 2019-08-27 16:20
It doesn't help eighter. Same issue: 
```
Errors were encountered while processing:
 boinc-client
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

But the `debconf: (TERM is not set, so the dialog frontend is not usable.)` line is resolved :)

**Comment by smoe** [comment] 2019-08-28 09:11
You have installed "dialog", right? So we need to find out why it is not "usable". I was hoping the TERM would have addressed that. Hm. So, let's shift focus on Term/Readline.pm. This comes with "perl-modules". Installed?

But, anyway, the process fails later with the unknown option "--skip-systemd-native". Would you mind rebasing your effort on a more recent version of Ubuntu? A quick check on https://hub.docker.com/_/ubuntu suggests devel.

**Comment by smoe** [comment] 2019-08-28 09:16
Sidenote - there is no need to use the ppa for 7.16.1 with devel as it is the same package by the same maintainer (https://launchpad.net/ubuntu/+source/boinc) uploaded. My hunch is that it is also the same post-install script that has a bit of an issue to talk to earlier versions of invoke-rc.d.

**Comment by smoe** [comment] 2019-08-28 09:22
@LocutusOfBorg , (hello!), you may have extra insights on what is done for backporting/known incompatibilities. If my hunch is confirmed then this is less of a docker issue.

**Comment by adamradocz** [comment] 2019-08-28 10:35
I'm not at home now. Bit for your information, everything was working with v7.14.2 with the same script.

**Comment by smoe** [comment] 2019-08-28 13:39
Ah.  I would then expect you to have seen the ReadLine and Dialog error messages with that version already. Let us confirm that it works again with the devel version of Ubuntu and then we see what to do to port it back, properly.

**Comment by adamradocz** [comment] 2019-08-28 16:01
The devel works fine. Unfortunately, we use the 18:04 image.

**Comment by smoe** [comment] 2019-08-28 20:24
I have no idea where this "--skip-systemd-native" is coming from. I understand it is a pre-depends missing (https://lintian.debian.org/tags/skip-systemd-native-flag-missing-pre-depends.html) and leave it to that backports' maintainer, i.e. @LocutusOfBorg, to solve that mystery. I can confirm the problem 
```
Preparing to unpack .../boinc_7.16.1+dfsg+201908161115~ubuntu18.04.1_all.deb ...
Unpacking boinc (7.16.1+dfsg+201908161115~ubuntu18.04.1) over (7.9.3+dfsg-5ubuntu2) ...
Setting up libboinc7:amd64 (7.16.1+dfsg+201908161115~ubuntu18.04.1) ...
Setting up boinc-client (7.16.1+dfsg+201908161115~ubuntu18.04.1) ...
usermod: group 'render' does not exist
Could not assign boinc user to group 'render'.
invoke-rc.d: syntax error: unknown option "--skip-systemd-native"
dpkg: error processing package boinc-client (--configure):
 installed boinc-client package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of boinc-manager:
 boinc-manager depends on boinc-client; however:
  Package boinc-client is not configured yet.
```
on a throwaway ubuntu bionic VM. But, an "apt-get -u dist-upgrade" made it install
```
The following packages will be upgraded:
  init init-system-helpers
```
and this then also had the boinc-client install successfully.
```
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
Need to get 61.7 kB of archives.
After this operation, 6,144 B of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://ppa.launchpad.net/costamagnagianfranco/boinc/ubuntu bionic/main amd64 init-system-helpers all 1.57~ubuntu18.04.1~ppa1 [46.9 kB]
Get:2 http://ppa.launchpad.net/costamagnagianfranco/boinc/ubuntu bionic/main amd64 init amd64 1.57~ubuntu18.04.1~ppa1 [14.7 kB]
Fetched 61.7 kB in 0s (200 kB/s)
(Reading database ... 82354 files and directories currently installed.)
Preparing to unpack .../init-system-helpers_1.57~ubuntu18.04.1~ppa1_all.deb ...
Unpacking init-system-helpers (1.57~ubuntu18.04.1~ppa1) over (1.51) ...
Setting up init-system-helpers (1.57~ubuntu18.04.1~ppa1) ...
(Reading database ... 82354 files and directories currently installed.)
Preparing to unpack .../init_1.57~ubuntu18.04.1~ppa1_amd64.deb ...
Unpacking init (1.57~ubuntu18.04.1~ppa1) over (1.51) ...
Setting up init (1.57~ubuntu18.04.1~ppa1) ...
Setting up boinc-client (7.16.1+dfsg+201908161115~ubuntu18.04.1) ...
usermod: group 'render' does not exist
Could not assign boinc user to group 'render'.
Setting up boinc-manager (7.16.1+dfsg+201908161115~ubuntu18.04.1) ...
Setting up boinc (7.16.1+dfsg+201908161115~ubuntu18.04.1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
W: APT had planned for dpkg to do more than it reported back (16 vs 20).
   Affected packages: boinc-client:amd64
```
Not yet at the 1.5.8 that the linitan error description suggested, but working:
```
init-system-helpers                  1.57~ubuntu18.04.1~ppa1
```
I admit not to know if this comes from bionic-updates or bionic-backports. I tried `boinccmd --get_state` and that worked. Nothing else tested.

Thank you tons for your report. I am confident you get it to work from here. And @LocutusOfBorg likely adds that pre-depends Lintian suggests.

**Comment by LocutusOfBorg** [comment] 2019-09-10 08:04
https://launchpad.net/~costamagnagianfranco/+archive/ubuntu/boinc

Yes, I had the same trouble, and backported init-system-helpers	1.57~ubuntu18.04.1~ppa1	
to my ppa exacly for that reason

**Comment by LocutusOfBorg** [comment] 2019-09-10 08:05
@smoe that package is built directly from Debian git repo, so committing your fix there will automagically bring the fix in Ubuntu ppa after some hours :)

**Comment by smoe** [comment] 2019-09-11 13:33
I gave boinc-client a dependency on init-system-helpers >= 1.57 - did not tag a new version though.

**Comment by adamradocz** [comment] 2019-09-11 19:00
The Docker is working with your commit. I close the issue.

**Closed by adamradocz** 2019-09-11 19:00 UTC
