### ISSUE TITLE
Only one GPU is used.

### ISSUE THREAD

**Issue by efmer** [BOINC/boinc#4352] opened 2021-04-29 13:39 UTC
My log:

Computer: linux
22		Apr 29, 2021, 01:13:02 PM	Config: use all coprocessors

15		Apr 29, 2021, 01:13:02 PM	Disk: 456.95 GB total, 384.32 GB free
14		Apr 29, 2021, 01:13:02 PM	Memory: 7.73 GB physical, 2.00 GB virtual
13		Apr 29, 2021, 01:13:02 PM	OS: Linux Ubuntu: Ubuntu 20.04.2 LTS [5.8.0-50-generic|libc 2.31 (Ubuntu GLIBC 2.31-0ubuntu9.2)]
12		Apr 29, 2021, 01:13:02 PM	Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
11		Apr 29, 2021, 01:13:02 PM	Processor: 8 GenuineIntel Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz [Family 6 Model 158 Stepping 9]
10		Apr 29, 2021, 01:13:02 PM	Host name: linux
9		Apr 29, 2021, 01:13:02 PM	libc: Ubuntu GLIBC 2.31-0ubuntu9.2 version 2.31
8		Apr 29, 2021, 01:13:00 PM	OpenCL: NVIDIA GPU 1: GeForce GTX 770 (driver version 460.73.01, device version OpenCL 1.2 CUDA, 2000MB, 1924MB available, 3493 GFLOPS peak)
7		Apr 29, 2021, 01:13:00 PM	OpenCL: NVIDIA GPU 0: GeForce GTX 1080 (driver version 460.73.01, device version OpenCL 1.2 CUDA, 8116MB, 3968MB available, 9331 GFLOPS peak)
6		Apr 29, 2021, 01:13:00 PM	CUDA: NVIDIA GPU 1: GeForce GTX 770 (driver version 460.73, CUDA version 11.2, compute capability 3.0, 2000MB, 1924MB available, 3493 GFLOPS peak)
5		Apr 29, 2021, 01:13:00 PM	CUDA: NVIDIA GPU 0: GeForce GTX 1080 (driver version 460.73, CUDA version 11.2, compute capability 6.1, 4096MB, 3968MB available, 9331 GFLOPS peak)
4		Apr 29, 2021, 01:12:43 PM	Data directory: /var/lib/boinc2
3		Apr 29, 2021, 01:12:43 PM	Running as a daemon
2		Apr 29, 2021, 01:12:43 PM	Libraries: libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
1		Apr 29, 2021, 01:12:39 PM	Starting BOINC client version 7.16.6 for x86_64-pc-linux-gnu

If I run only Milkyway there are two tasks running at 0,97C + 1NV
No CPU.
A second project World Community Grid is suspended. 

When I let  World Community Grid run it starts 8 CPU tasks (High priority) and  one GPU tasks World Community Grid 0.926Cpu + 1NV.
One GPU is now idle, this is a real waist of GPU Power, letting one GPU idling.

The only solution I can find is start 2 BOINC instances and exclude one GPU in one and another in the second instance.

**Comment by AenBleidd** [comment] 2021-04-29 13:45
Looks like a duplicate of #1775

**Comment by AenBleidd** [comment] 2021-04-29 13:47
@efmer, feel free to reopen i you think it's a different issue

**Closed by AenBleidd** 2021-04-29 13:47 UTC
Labels: C: Client - Scheduler Policy, P: Minor, R: duplicate

**Comment by RichardHaselgrove** [comment] 2021-04-29 13:59
I think it's worth double-checking exactly what's going on, just in case.

@efmer  - exactly which meaning of the word 'priority' did you mean in 

> it starts 8 CPU tasks (High priority)

If that's EDF (Earliest Deadline First), the behaviour is by design: some task is in danger of missing its deadline. That is more important to the client scheduler than the idle GPU.

Try reducing the number of tasks in your cache ('Store at least ...' values), or examine the <rr_simulation> event log. If that clears it (in due course), we can leave this closed. If the cause is something other than EDF, post again.

**Comment by efmer** [comment] 2021-04-29 16:24
@RichardHaselgrove World Community Grid wants the highest scheduler priority most of the time.
The strange thing is BOINC always lets one GPU task running even I just got the task.
Why let one running? it wants 0.926 CPU and there are other cpu tasks that have way more priority.
Anyway the tasks have plenty of time to complete even with 2 GPU tasks running.

I solved it by splitting thing in two instances of BOINC one excluding GPU device 0 and the other device 1

**Comment by AenBleidd** [comment] 2021-04-29 16:28
@efmer, because 2 GPU tasks will occupy more than 1 CPU core, and total CPU cores then will be mote that available for BOINC.
I can suggest you to create custom app_config.xml and set 0.5 CPU usage instead of 0.926. This should enable 2 GPU tasks (of course, in case if other tasks will be closer to deadline, GPU (one or both) could be ignored again
