### ISSUE TITLE
Android Boinc shows 0 tasks

### ISSUE THREAD

**Issue by Stiwi** [BOINC/boinc#2123] opened 2017-09-14 20:30 UTC
If there are too much tasks (more than 100?) are running but the android client shows 0 tasks.

This happens on a Galaxy S5 Neo with Android 6.0.1.

See also https://boinc.berkeley.edu/dev/forum_thread.php?id=11640

**Comment by adamradocz** [comment] 2019-09-26 08:41
What version?
Is this still an issue?

**Comment by AenBleidd** [comment] 2019-09-26 08:42
Even if it is, I believe, it is a very rare case. I was not able to reproduce it

**Comment by adamradocz** [comment] 2019-10-02 18:45
Can we close this issue?

**Comment by AenBleidd** [comment] 2019-10-02 19:11
I'd keep it for now.

**Comment by adamradocz** [comment] 2019-10-14 18:51
I could reproduce the issue with v7.16,3.
I set the WU buffer for 7 days and probably get too many WUs, because it shows 0 tasks, but the CPU monitor shows that the phone is crunching.

**Comment by adamradocz** [comment] 2019-10-16 11:56
I can see the task again. It shows 140, so that or a similar number could be the limit.

**Comment by techsy730** [comment] 2019-10-30 00:59
The limit to trigger this bug can now be easily hit on moderately high chipsets (like Snapdragon 855) and a project that likes to give lots of smaller tasks all at once (such as Einstein@Home)

**Closed** 2021-01-24 08:54 UTC
Labels: C: Android - Manager
