### ISSUE TITLE
Please send notification to user that his/her host started producing invalid results

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1769] opened 2017-01-25 18:59 UTC
It will be good to implement on server side some mechanism which will look for hosts which started producing invalid results. When this will happen, it should automatically send email or private message with information about this and kindly ask user to check that machine because it may be overheating or have some hardware issue. You could also resend this notification periodically if host will keep producing these bad results for longer period of time. This should help reduce number of invalid WUs returned to projects servers.

**Edit:** it would be good to show some warning on user's home page too, this page is visited more often than task or computers list. You could also show some warning or special icon on computers list, this would be helpful for users with multiple machines to quickly identify ones which produces bad results.

**Comment by Toby-Broom** [comment] 2017-04-10 21:14
This would be a nice feature

**Comment by Ageless93** [comment] 2017-11-11 00:58
Possible duplicate of  #962 (although there it's asked to show this through BOINC Manager (Notices))

**Comment by sirzooro** [comment] 2017-11-11 20:48
That issue partially overlaps with issue, as both of them proposes how to tell user that his host is faulty. My proposal is to use email and web-based ways (notifications on home page and host list, private message), the other issue tells about using notifications. So the best approach would be to implement both propositions together, as some people may actively monitor BoincMgr, and rarely check project's website.

**Comment by lfield** [comment] 2018-10-12 07:44
Detection of invalid results and user notification is a general issue. We can decide on the best way to implemented the notification.

**Comment by AenBleidd** [comment] 2024-08-01 13:25
Closing this as a duplicate of #1413

**Closed by AenBleidd** 2024-08-01 13:25 UTC
Labels: C: Server - Other, C: Web - Other, P: Major, R: duplicate, T: Enhancement, Feature Request, E: 1 day
