### ISSUE TITLE
Boinc GUI is mirrored

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#911] opened 2015-02-04 03:20 UTC
**Reported by harley84 on 17 Nov 39527312 07:06 UTC**
Even though my Windows XP is an English version, my regional and Language options specify that I am using Hebrew preferences and located in Israel. Perhaps thats why all GUI looks mirrored to me. 

Migrated-From: http://boinc.berkeley.edu/trac/ticket/934

**Comment by ChristianBeer** [comment] 2017-04-07 09:59
This is an old report and it needs to be verified if this is still happening with a current version.

**Comment by Ageless93** [comment] 2017-08-17 15:10
Any users in Israel reading this who can check if this is still an issue with BOINC 7.6.33 or 7.8.1?

**Comment by AenBleidd** [comment] 2018-09-18 23:57
Yes, it is still an issue, please see screenshot, BOINC version 7.12.1
![image](https://user-images.githubusercontent.com/3234209/45722959-a49d9480-bbb7-11e8-8cff-b29e622e64eb.png)

**Comment by lfield** [comment] 2018-10-12 07:57
Closing as duplicate of  #988

**Closed by lfield** 2018-10-12 07:57 UTC
Labels: C: Manager - Localization, P: Trivial, T: Defect
