### ISSUE TITLE
Convert team name HTML and team description to BBcode.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#582] opened 2015-02-04 00:44 UTC
**Reported by Didactylos on 19 Feb 38264732 03:33 UTC**
Convert team name HTML and team description to BBcode.

Source: DevProjects

''(Note: there is some debate about the choice of formatting. Don't attempt this task without further discussion.)''

Migrated-From: http://boinc.berkeley.edu/trac/ticket/604

**Comment by romw** [comment] 2015-02-04 16:05
**Commented by Nicolas on 19 Sep 38266444 09:46 UTC**
Replying to [Didactylos](ticket:604):
> ''(Note: there is some debate about the choice of formatting. Don't attempt this task without further discussion.)''
Yeah, some people think it would be better to take forums back to HTML than to convert the little HTML left (like team descriptions) into BBcode.

**Comment by ChristianBeer** [comment] 2017-04-06 07:11
duplicate of #374 Closing this for the same reason. It's a lot of hassle to migrate from HTML to BBCode and even BBcode is not very convenient.

**Closed by ChristianBeer** 2017-04-06 07:11 UTC
Labels: C: Web - Project, P: Trivial, T: Task
