### ISSUE TITLE
Android BOINC 7.16.16 Notices don't work

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4208] opened 2021-02-19 13:43 UTC
Thus far I have found that the Notices tab stays really empty, no matter what I do. There's no news in it, there are not notices of user foul-ups. So I was wondering if it is working at all. Initially I posted this question the the Alpha list as I didn't have any projects which had up to date news or anything, other than LHC. But then I don't know if News is showing for 30 days or less either. 

In any case, the World Community Grid put some news out, which is available in BOINC 7.4.53 but isn't in BOINC 7.16.16 
I just checked on my PC and it isn't available in 7.16.11 (for Windows) either. So perhaps it's something in the 7.16 branch that got broken? Yes, I did update WCG there as well, the only news I have there is of Milkyway@Home (of 31/01, 01/02 and 02/02-2021). 

![Requesting update from WCG](https://user-images.githubusercontent.com/10869587/108511263-f9c9bd00-72bf-11eb-8c78-a590b3cd1684.jpg)
![No News or Notices](https://user-images.githubusercontent.com/10869587/108511268-fa625380-72bf-11eb-88de-02ca570b433e.jpg)

**Comment by Ageless93** [comment] 2021-02-19 13:45
I may have a double with #4185, but then I prefer this one to stay open.

**Comment by RichardHaselgrove** [comment] 2021-02-19 14:27
I managed to get this with v7.16.16 (Samsung tablet)

![Screenshot_20210219-141924_BOINC](https://user-images.githubusercontent.com/14886436/108516696-73f94200-72be-11eb-812c-96ea67d0a775.jpg)

**Comment by Ageless93** [comment] 2021-02-19 14:34
Which Android version do you run, Richard?
Maybe that that's something. My phone runs Android 9.0 with update
9.1.0.374 on it (Huawei EMUI update).

-- Jord

**Comment by RichardHaselgrove** [comment] 2021-02-19 14:44
![Screenshot_20210219-144034_Settings](https://user-images.githubusercontent.com/14886436/108518760-d94e3280-72c0-11eb-8584-85bd957d3525.jpg)

**Comment by talregev** [comment] 2021-02-19 18:36
Not sure what is your bug.
That you don't get notice at all? or you don't get notice from WCG?
I have various device with various android versions, and from 7.16.x branch, I can check to be specific, other then say that the notice is working on all, but one. and in that one I don't think the projects send any notice.

**Comment by Ageless93** [comment] 2021-02-19 19:16
> Not sure what is your bug.
> That you don't get notice at all? or you don't get notice from WCG?

I don't get any news (notices) from any project. The first project that this BOINC should've been able to receive News from was LHC, the second is WCG which has been putting out new news all of today (19/02.2021).

**Comment by AenBleidd** [comment] 2021-02-19 19:41
@Ageless93, I have WCG connected for more than a year already on my laptop but I have no news in Notices.

**Comment by AenBleidd** [comment] 2021-02-19 19:43
Ok, I see that I switched off all notifications on my WCG account. Will do some test now with notifications switched on.

**Comment by AenBleidd** [comment] 2021-02-19 19:46
I did manual Project update after switching In-app notifications on WCG and received all notices:
![image](https://user-images.githubusercontent.com/3234209/108553826-8346b280-72f3-11eb-887d-f1a49f94037c.png)

**Comment by talregev** [comment] 2021-02-19 20:56
> I don't get any news (notices) from any project. The first project that this BOINC should've been able to receive News from was LHC, the second is WCG which has been putting out new news all of today (19/02.2021).

I think the problem is in  maybe in boinc, but I know the problem is not connected to android version nor 7.16.x branch.
Because I get notice from many android devices and windows device. The devices is from the branch 7.16.x and I have android devices from android 7 to 9. I didn't check specific notice messages from WCG. 
So it should be something else.

**Comment by Ageless93** [comment] 2021-02-19 22:29
> 
> 
> Ok, I see that I switched off all notifications on my WCG account. Will do some test now with notifications switched on.

Aha. I didn't know that was an option. And for those who didn't know either, look at what communication preferences you have set for WCG at https://www.worldcommunitygrid.org/ms/viewNewsPreference.action, you'll need In-App Notifications enabled. Thanks Vitalii. 

Okay, so now WCG does show up in Notices in Android (although still not on my PC ;-)).

**Comment by talregev** [comment] 2021-02-21 12:45
@Ageless93 You can close this issue if it solve for you.

**Closed** 2021-02-21 12:56 UTC
Labels: C: Android - Manager, C: Client - Android, P: Major, T: Defect
