### ISSUE TITLE
Should we allow ALT+F4 to actually close BOINC?

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#2604] opened 2018-07-14 14:06 UTC
Testing ALT+F4 on an open BOINC (Manager) on Windows 7, it 'closes' the BOINC Manager window, but leaves everything actually running. It just moves it to the system tray. 
Same thing for right-clicking the BOINC icon on the task bar and clicking 'Close window'. 

In both cases it's as if one's clicking the red X in the top right corner. 

I'm sure this behaviour was added at one time to force the user to actually go through BOINC Manager or BOINCCMD to close everything down correctly - and in a timely fashion so it doesn't abruptly close the science application. But I'm wondering if we shouldn't allow ALT+F4 to close the manager and client down, as I can think of times when you quickly want rid of everything and going the cumbersome way of via the GUI or typing the whole command can cost precious time you don't want to lose in closing programs down 'the way the developer intended' (think breaking hardware). 

What does everyone think? 
And is what I surmise the actual reason that ALT+F4 doesn't close the program down?

**Comment by RichardHaselgrove** [comment] 2018-07-14 15:24
I'd agree: it's not just 'service' applications (as in Windows services), but anything which runs in the background - messaging apps, hardware monitors, or what you will.

I find the quickest way of making an orderly, complete, shutdown is by right-clicking the tray icon and choosing 'exit'.

That assumes the Manager's tray icon is visible, of course...

**Comment by Ferroin** [comment] 2018-07-16 11:33
It might be nice to have an option to close the manager completely though when you close the window.  On Linux, if there's no system tray that the manager supports, 'closing' the window minimizes it instead, which is seriously irritating because it keeps the window around in the task switcher.

**Comment by aaronpuchert** [comment] 2018-07-19 22:38
As @Ferroin pointed out, on Linux the current behavior doesn't make sense, especially since the client usually runs as background service and isn't tied to the GUI manager. Closing the manager usually doesn't shut down anything. I actually only start the manager when I need it, and then close it immediately. On Windows it's a different story though, since the client is usually started via the manager. So maybe it should be platform-dependent, or dependent on whether the client is run as a service as opposed to being started by the manager.

**Comment by IronCraftMan** [comment] 2018-08-25 20:39
I'm not sure if something changed in a recent version, I had to wipe my computer and when I installed BOINC I noticed that pressing the X button no longer closes BOINC completely, instead it just minimizes it to the Tray Icon. I'd like to have the feature restored where I can completely close out with the X Icon, as I always make sure no tasks are running before closing it, and I don't like having to go into my tray just to close it when a simple X button would do.

**Comment by CharlieFenton** [comment] 2018-08-26 09:37
That is not a change; it has always worked that way and is by design. By default, exiting the BOINC Manager also exits the BOINC client, stopping all tasks. A significant portion of BOINC users may not understand that, which is why the Manager was designed to simply move to the background unless Exit is specifically requested. Even for users who understand that, it is very easy to accidentally click the X out of habit even when you only want BOINC to run in the background. By the way, stopping all tasks from running (i.e., suspending them) before exiting accomplishes nothing, as exiting BOINC will stop them anyway. Either way, any work done since the last checkpoint will be lost.

**Comment by aaronpuchert** [comment] 2018-08-26 16:10
> By default, exiting the BOINC Manager also exits the BOINC client, stopping all tasks.

Only if BOINC is not run as a service, right? Hence my suggestion to make the behavior on closing the manager window dependent on that, too. On Linux must people run the BOINC client as background service, so closing the manager is just fine and doesn't stop any tasks.

**Comment by CharlieFenton** [comment] 2018-08-27 00:31
> Only if BOINC is not run as a service, right?
Right, which is why I wrote _by default_ in my response to @IronCraftMan.

**Comment by CharlieFenton** [comment] 2018-08-27 06:27
Since  @IronCraftMan did not say what OS he uses but refers to the tray icon, I guessed it is most likely MSWindows, where running BOINC as a service is less common; I believe BOINC can't compute using the GPU on MSWindows when run as a service.

**Comment by Ageless93** [comment] 2018-08-27 08:44
There's one caveat where exiting BOINC Manager will not stop running tasks and that's when you uncheck "Stop running tasks when exiting the BOINC Manager?", and this will continue to be the default when you also click "Remember this decision and do not show this dialog". And if you forgot you set that.... Now each time you exit BOINC manager, even when not installed as a service, tasks will continue to run.

> I believe BOINC can't compute using the GPU on MSWindows when run as a service.

That's true. When BOINC is installed as a service, it runs in a different session than the installed videocard drivers do. These run under the user account, whereas BOINC runs under the limited user account. Thus the default Windows drivers are used and to be as commonly usable by all videocards out there, these lack things as CUDA, OpenCL or (in the future) Vulkan.

**Comment by RichardHaselgrove** [comment] 2018-08-27 17:49
The trouble with this - as always with Windows - that there are so many different ways of doing things. I count at least five (clockwise from top left, examples from Windows 7):

1) File menu
![file menu](https://user-images.githubusercontent.com/14886436/44673149-9928d480-aa22-11e8-9f17-56706f0e63f6.png)

2) Control box
![control box](https://user-images.githubusercontent.com/14886436/44673178-a6de5a00-aa22-11e8-8a04-14980bd5f11a.png)

3) Red-X
![red-x](https://user-images.githubusercontent.com/14886436/44673230-d0978100-aa22-11e8-8dcc-46ee8735cbc2.png)

4) Notification area (was System Tray)
![system tray](https://user-images.githubusercontent.com/14886436/44673251-e442e780-aa22-11e8-8dde-1549df5a7380.png)

5) Task bar
![taskbar](https://user-images.githubusercontent.com/14886436/44673267-f02ea980-aa22-11e8-8b97-1445809b99ac.png)

Note that Alt-F4 appears in item 2, which I've labelled "Control box": that was the name for that particular button in Windows 3.1, and it's been completely forgotten by Google. I've still got the hard-copy manuals I used when converting an MS-DOS program to run under Windows 3, 25 years ago, so I'm being careful to check my memory and my terminology.

It's an incredibly ancient relic.

I thought we might be able to get guidance from something like [Keyboard shortcuts in Windows](https://support.microsoft.com/en-gb/help/12445/windows-keyboard-shortcuts), but that defines Alt-F4 as

`Close the active item, or exit the active app` - they leave it up to us.

In the BOINC environment, the word used is "Close", and I think that's deliberately done to distinguish it from the "Exit" used in other places. It behaves as close, like Ctrl-W in menu (1) or the red-X.

If the control box wording and behaviour could be changed to 'Exit BOINC Manager' in the two cases where this is the preferred action (service install - including Linux -, and user choice not to stop client), then it might help: but otherwise I'd prefer keeping 'exit' to the places where exit is really meant and which invoke the exit dialog if configured.

**Comment by Ferroin** [comment] 2018-08-27 18:35
@RichardHaselgrove I see exactly zero issue with respect to naming though.  Items 1 and 4 are controlled entirely by BOINC, it can do whatever it wants there.  2 (for reference, this is often known as a 'window menu' or 'window manager menu' on Linux), 3 (strictly speaking known as the 'close button', if you want to be more specific it's the `close button on the title bar'), and the taskbar popup are all controlled by the window manager (so, essentially the OS itself), and BOINC has exactly zero control over it.

The issue being discussed here is exactly because the BOINC Manager behaves in a manner which is not entirely consistent with other applications.

Expected behavior as far as I'm concerned is this:

* If there is a system tray supported by BOINC, closing the window with Alt-F4, the window menu, or the taskbar popup minimizes it to the system tray.
* If the BOINC client was not started by the BOINC Manager (for example, manually started from the CLI or run as a service), exit the BOINC manager if the window would be closed, and don't touch the client.
* Otherwise, minimize the window when asked to close.

Then, on top of that, have options to override this behavior.

Current behavior in comparison doesn't include the second part, which means that on 95% of Linux systems, the only way to close the BOINC manager is to use Qtrl-Q or the regular menus as in your first method of closing it, which is _seriously_ irritating.

Now, I do see a potential issue regarding handling of multiple BOINC Managers pointing at the same client where one of them exits, but that's just about the definition of a corner case.

**Comment by aaronpuchert** [comment] 2018-08-28 23:02
I would exchange points 1 and 2, otherwise I agree. On KDE there is a Windows-like system tray, but as long as BOINC runs as service, there is no reason *not* to quit the manager on closing it. It won't stop any tasks.

> Now, I do see a potential issue regarding handling of multiple BOINC Managers pointing at the same client where one of them exits, but that's just about the definition of a corner case.

Not sure about that, but I guess that only one manager "owns" the client then. In any event, I think this is unrelated to the issue here. It's not like we're discussing about the possibility to quit the manager, just about whether closing the window = <kbd>Alt</kbd>+<kbd>F4</kbd> should do it.

**Comment by Ferroin** [comment] 2018-08-29 11:09
THe problem arises from the fact that closing the window and not going to the system tray _is_ quitting the manager.

**Comment by aaronpuchert** [comment] 2018-09-08 12:56
Hmm, but what is the problem? I want it to quit if the client isn't attached to it, just like most other applications would do if I close them. Staying alive in tray or minimized only makes sense if the client is attached to the manager and quitting the manager would end all computation.

**Comment by AenBleidd** [comment] 2018-09-18 14:34
> Hmm, but what is the problem? I want it to quit if the client isn't attached to it, just like most other applications would do if I close them. Staying alive in tray or minimized only makes sense if the client is attached to the manager and quitting the manager would end all computation.

 One command should either close the application or hide it to tray. Additional conditions make behavior too complicated for understanding.

**Comment by aaronpuchert** [comment] 2018-09-20 00:55
Yet the condition is pretty natural, isn't it? Closing quits when it won't stop any tasks, otherwise it doesn't. Not all Linux desktops have a tray, in fact the most widely used doesn't, so hiding to tray is not always an option. Even with a tray it doesn't really make sense to use it if the client runs as a service independently of the manager.

**Comment by Germano0** [comment] 2018-12-10 14:07
> There's one caveat where exiting BOINC Manager will not stop running tasks and that's when you uncheck "Stop running tasks when exiting the BOINC Manager?", and this will continue to be the default

In CentOS (I assume in Fedora too) if you click on "Stop running tasks when exiting the BOINC Manager?" the service will stop. The problem is that to resume it you have to restart it from systemctl or reboot the machine.

I paste here the comment I inserted in the older issue ticket ["Closing manager window minimizes it instead (Linux)"](https://github.com/BOINC/boinc/issues/1348#issuecomment-444534306)
**Note that the patches affects only Linux**

============
Before filling a pull request I would like to hear some feedbacks.
I elaborated two different patches:

- send to tray icon patch;
- close window patch.

**Send to tray icon patch**
Closes the BOINC manager window, leaving only the tray icon.
Problems: 
1. for unknown reasons, once BOINC manager is reduced to tray icon, if you right click on tray icon and click on "Exit", the icon will disappear, but BOINC manager process will hang;
2. GNOME has no tray icons bar at all, so IMHO having BOINC manager reduced to icon is useless
3. BOINC runs as a service, regardless if the manager is opened / closed
So for the previous points, I would even remove the tray icon at all from BOINC Manager for Linux
```
diff -urNr boinc-client_release-7.14-7.14.2-orig/clientgui/BOINCBaseFrame.cpp boinc-client_release-7.14-7.14.2/clientgui/BOINCBaseFrame.cpp
--- boinc-client_release-7.14-7.14.2-orig/clientgui/BOINCBaseFrame.cpp	2018-10-11 02:43:27.000000000 +0200
+++ boinc-client_release-7.14-7.14.2/clientgui/BOINCBaseFrame.cpp	2018-12-05 14:42:08.350622590 +0100
@@ -329,13 +329,7 @@
         wxGetApp().FrameClosed();
         Destroy();
     } else {
-#ifdef __WXGTK__
-        // Apparently aborting a close event just causes the main window to be displayed
-        // again.  Just minimize the window instead.
-        Iconize();
-#else
         Hide();
-#endif
     }
 
     wxLogTrace(wxT("Function Start/End"), wxT("CBOINCBaseFrame::OnClose - Function End"));

```

**Close window patch**
```
diff -urNr boinc-client_release-7.14-7.14.2-orig/clientgui/BOINCBaseFrame.cpp boinc-client_release-7.14-7.14.2-close/clientgui/BOINCBaseFrame.cpp
--- boinc-client_release-7.14-7.14.2-orig/clientgui/BOINCBaseFrame.cpp	2018-10-11 02:43:27.000000000 +0200
+++ boinc-client_release-7.14-7.14.2-close/clientgui/BOINCBaseFrame.cpp	2018-12-05 15:21:43.728546201 +0100
@@ -330,9 +330,8 @@
         Destroy();
     } else {
 #ifdef __WXGTK__
-        // Apparently aborting a close event just causes the main window to be displayed
-        // again.  Just minimize the window instead.
-        Iconize();
+        wxGetApp().FrameClosed();
+        Destroy();
 #else
         Hide();
 #endif
```

**Closed** 2019-04-12 12:39 UTC
Labels: C: Manager, T: Informational
