### ISSUE TITLE
vboxwrapper Win 10 "VM failed to enter an online state..." errors

### ISSUE THREAD

**Issue by marius311** [BOINC/boinc#1737] opened 2016-12-18 22:02 UTC
Hi folks, trying to track down this error which seems to be plaguing a number of users across BOINC projects running VM apps. Based on the jobs in our database at Cosmology@Home (which includes two weeks worth of results), the symptoms appear to be:

* User receives the message "Postponed: VM Hypervisor failed to enter an online state in a timely fashion"
* stderr_log contains "VM failed to enter an online state" message
* About 50% of the time, the job is retried and finished successfully later 
* Not all jobs will have this error on a given host (on average, for hosts that see this error at all, 25% of their jobs will have it)
* This seems to be largely happening on Win 10 (especially 10.00.14393.00) 
* There's no super obvious client version / VBox version correlation (more data points might reveal something)

The error logs are a bit all over the place (plus many are truncated so stuff is often missing), but below is a list of some of the most common lines which appear amongst these logs (beyond the "failed to enter an online state" one which identifies jobs in the first place):

```
Status Report: virtualbox.exe/vboxheadless.exe is no longer running.
ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={f30138d4-e5ea-4b3a-8858-a059de4c93fd} aComponent={MachineWrap} aText={The object functionality is limited}, preserve=false aResultDetail=0
Power up failed (vrc=VERR_MODULE_NOT_FOUND, rc=E_FAIL (0X80004005)) 
ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={480cf695-2d8d-4256-9c7c-cce4184fa048} aComponent={Machine} aText={The object functionality is limited}, preserve=false                                                                                                                                 180
VMSetError: D:\tinderbox\win-4.3\src\VBox\VMM\VMMR3\PDMLdr.cpp(703) int __cdecl pdmR3LoadR0U(struct UVM *,const char *,const char *,const char *); rc=VERR_LDR_MISMATCH_NATIVE                                                                                                                            163
ERROR [COM]: aRC=VBOX_E_INVALID_OBJECT_STATE (0x80bb0007) aIID={480cf695-2d8d-4256-9c7c-cce4184fa048} aComponent={Machine} aText={The given session is busy}, preserve=false                                                                                                                               56
```

Here's the distribution of these errors across OS version (the way to read these tables is, e.g. the first row below says "17% of the 750 hosts running Windows 10.00.14393.00 saw this error at least once)

OS|frac|tot
-|-|-
Windows (10.00.14393.00)|0.17|750
Linux 4.4.0-47-generic|0.17|6
Windows (06.02.9200.00)|0.08|12
Windows (10.00.10240.00)|0.08|13
Windows (06.03.9600.00)|0.06|99
Windows (10.00.10586.00)|0.05|86
Windows (06.01.7601.00)|0.03|543

Across Vbox version:

VBox|frac|tot
-|-|-
4.2.4|1.00|1
4.3.8|0.50|4
4.3.12|0.32|194
5.0.4|0.29|7
4.3.12_ZZZZ|0.26|19
4.2.12|0.25|4
4.2.16|0.24|63
4.3.10|0.20|5
5.0.0|0.20|5
5.1.10|0.10|175
5.0.24|0.08|12
5.0.30r112061|0.08|13
5.0.28|0.08|26
5.0.12|0.07|321
5.0.18|0.07|159
5.0.30|0.06|36
5.1.8|0.04|79
5.0.10|0.04|57
5.1.6|0.02|91

And client version:

Client|frac|tot
-|-|-
7.4.42|0.39|41
7.0.28|0.33|3
7.2.47|0.33|3
7.6.9|0.31|83
7.4.36|0.26|23
7.4.27|0.15|20
7.6.33|0.09|437
7.6.22|0.06|1041
7.2.42|0.05|82

See also some project specific threads:
* https://www.cosmologyathome.org/forum_thread.php?id=7443
* https://www.cosmologyathome.org/forum_thread.php?id=7439
* http://lhcathome2.cern.ch/vLHCathome/forum_thread.php?id=1754
* http://lhcathome2.cern.ch/vLHCathome/forum_thread.php?id=1880
* https://www.rechenkraft.net/forum/viewtopic.php?f=75&t=15980
* https://lhcathome.cern.ch/lhcathome/forum_thread.php?id=3967
* http://atlasathome.cern.ch/forum_thread.php?id=544

**Comment by JacobWKlein** [comment] 2017-01-04 15:50
From: Rom Walton
Sent: Wednesday, January 4, 2017 10:24 AM
To: Marius Millea
Cc: Jacob Klein
Subject: RE: vbox debugging

The basic issue with Win10 is that the mechanism Oracle uses to determine that 3rd party drivers and DLLs are not running within the VirtualBox process space is fragile.

See:
https://forums.virtualbox.org/viewforum.php?f=38

Different versions of VirtualBox may or may not be compatible with different versions of Windows 10.

Jacob Klein probably has the feel of the compatibility matrix as it relates to BOINC and Virtualbox on Windows 10.

----- Rom

**Comment by JacobWKlein** [comment] 2017-01-04 15:51
From: Jacob Klein
Sent: Wednesday, January 4, 2017 10:48 AM
To: Rom Walton; Marius Millea
Subject: Re: vbox debugging

I'll chime in.

Oracle VirtualBox has a "Windows process hardening" security system in their code, that will intentionally disallow VMs to run, if the security check fails. The code is a bit fragile, and when new "Windows Insiders" builds of Windows 10 get releases, they are prone to cause the problem, until Oracle fixes it. And those would lead to your problems I think.

That link Rom gave, is the best avenue to keep track of which Win10 builds work against which VBox versions.
https://forums.virtualbox.org/viewforum.php?f=38

Ultimately, what you need to do (to determine if the problem was caused by Oracle VirtualBox's "Windows process hardening"), is:
Make 2 tables.

Table 1:
Windows 10 Build Version || Minimum Oracle VirtualBox Version including the R number, which passes security check

Table 2:
VBoxWrapper Version || Maximum compatible Oracle VirtualBox Version

Building Table 1 will involve going through all those threads in that forum. Which you could do! 😝

For instance, I know for fact that, in order to run Win10 Build 14971 or 14986, without error, you must use these VirtualBox branch versions or newer:
VirtualBox 4.3.41 r112025
VirtualBox 5.0.29 r112021
VirtualBox 5.1.9 r112020

Another for instance, is..
If you're using VBoxWrapper 26167, you must use VirtualBox 4.x or older
If you're using VBoxWrapper 26184, you must use VirtualBox 5.0.x or older
If you're using VBoxWrapper 26197, you must use VirtualBox 5.1.x or older

Are we having fun yet?

Regards,
Jacob

**Comment by JacobWKlein** [comment] 2017-01-04 16:12
From: Jacob Klein
Sent: Wednesday, January 4, 2017 11:12 AM
To: Rom Walton; Marius Millea
Subject: Re: vbox debugging
 
I did a little digging, to get one more info point for you.

For Win 10 Build 14393, to work without a "process hardening" error, I think you must use these VirtualBox branch versions or newer:
4.3.39 r106879
5.0.19 r106880

Regards,
Jacob

**Comment by JacobWKlein** [comment] 2017-01-04 16:56
Did you just reference a log where host has VirtualBox 4.3.12? :) That's ancient. Like, released around 5/16/2014!

Oracle is, ALL the time, fixing strange bugs that cause strange behaviors. Most deal with glitches in the VirtualBox Service (for Windows at least). Some of them cause the VBox Service to not respond at startup, or even worse, stop responding while running. Each OS-version of VirtualBox, has a handful of various issues getting fixed.

5.1.x, and recent versions of 5.0.x like 5.0.28+, are both WAY more stable than 4.3.x.

My recommendation would be get your userbase to be on newer versions (by force if necessary), before you try to research failures. Sorry if that's not as helpful as you wanted.

**Comment by marius311** [comment] 2017-01-04 19:24
I suppose I did, but its just one that randomly came up. If you look at my table above, plenty of the 5.X versions are seeing this error. I'll try to find you a log from those for definiteness. Of course my first answer on forums is always upgrade Vbox but it's clear it's not that simple.

**Comment by JacobWKlein** [comment] 2017-01-04 21:02
Most of your threads report general solutions of upgrading to newer VirtualBox versions. As I said, 5.1.x and 5.0.28+, are WAY more stable than 4.3.x and 5.0.26-.

**Comment by marius311** [comment] 2017-01-04 23:08
> You may even consider filtering those versions out of your searches. 

Right, for example, in my original post I show that 10% of 175 hosts running 5.1.10 are still seeing these errors. So again, its not as simple as I think you're trying to make it.

**Comment by AenBleidd** [comment] 2022-10-07 18:55
Current used version of VBox is 6.1.smth.
I'm closing this as 'wontfix' for now.
If this is still an issue - please reopen it.

**Closed by AenBleidd** 2022-10-07 18:55 UTC
Labels: P: Major, R: wontfix, T: Defect, C: Apps - VboxWrapper

**Comment by JacobWKlein** [comment] 2022-10-07 19:58
For what it's worth, I have been actively testing VirtualBox versions to make sure they stay compatible with Microsoft's changes to Windows 10 and Windows 11. You can see more here: https://forums.virtualbox.org/viewtopic.php?f=38&t=80967&sid=2f291313ab2defa78efa75f4e3ddec10
