### ISSUE TITLE
[Android] Building on Windows(VirtualBox) freezes on SplashScreen

### ISSUE THREAD

**Issue by thiagopelikan** [BOINC/boinc#3556] opened 2020-04-04 20:57 UTC
**Describe the bug**
I'm trying to build the Android app following the steps from Vagrant.README.md and after I run the project, the app freezes on splashScreen with the bellow log:

From Device:
`04-04 17:34:39.195 E/BOINC_GUI( 5656): IOException
04-04 17:34:39.192 W/BOINC_GUI( 5656): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
04-04 17:34:39.157 E/BOINC_GUI( 5656): IOException: /data/data/edu.berkeley.boinc/client/boinc (No such file or directory)
04-04 17:34:39.157 E/BOINC_GUI( 5656): IOException: arm64-v8a/boinc
04-04 17:34:38.192 E/BOINC_GUI( 5656): ... 8 more
04-04 17:34:38.192 E/BOINC_GUI( 5656): at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at java.lang.ProcessImpl.start(ProcessImpl.java:128)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at java.lang.UNIXProcess.forkAndExec(Native Method)
04-04 17:34:38.192 E/BOINC_GUI( 5656): Caused by: java.io.IOException: error=2, No such file or directory
04-04 17:34:38.192 E/BOINC_GUI( 5656): at java.util.TimerThread.run(Timer.java:505)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at java.util.TimerThread.mainLoop(Timer.java:555)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:366)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at edu.berkeley.boinc.client.Monitor.access$200(Monitor.java:77)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:378)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:572)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:649)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at java.lang.Runtime.exec(Runtime.java:691)
04-04 17:34:38.192 E/BOINC_GUI( 5656): at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
04-04 17:34:38.192 E/BOINC_GUI( 5656): java.io.IOException: Cannot run program "/data/data/edu.berkeley.boinc/client/boinc" (in directory "/data/data/edu.berkeley.boinc/client"): error=2, No such file or directory
04-04 17:34:38.192 E/BOINC_GUI( 5656): IOException
04-04 17:34:38.187 W/BOINC_GUI( 5656): Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
04-04 17:34:38.159 E/BOINC_GUI( 5656): IOException: /data/data/edu.berkeley.boinc/client/boinc (No such file or directory)`

From Logcat
`2020-04-04 20:41:23.900 7486-7486/edu.berkeley.boinc D/BOINC_GUI: SplashActivity onResume()
2020-04-04 20:41:23.903 7486-7486/edu.berkeley.boinc V/PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@d4c87dd[]
2020-04-04 20:41:23.911 7486-7486/edu.berkeley.boinc D/WindowClient: Add to mViews: DecorView@d4c87dd[SplashActivity], this = android.view.WindowManagerGlobal@de44102
2020-04-04 20:41:23.912 7486-7486/edu.berkeley.boinc D/OpenGLRenderer: Dumper init 2 threads <0x7c4131a5c0>
2020-04-04 20:41:23.912 7486-7486/edu.berkeley.boinc D/OpenGLRenderer: <edu.berkeley.boinc> is running.
2020-04-04 20:41:23.916 7486-7516/edu.berkeley.boinc D/OpenGLRenderer: CanvasContext() 0x7c4f86b000
2020-04-04 20:41:23.932 7502-7502/edu.berkeley.boinc:remote W/System: ClassLoader referenced unknown path: /data/app/edu.berkeley.boinc-1/lib/arm64
2020-04-04 20:41:23.934 7486-7486/edu.berkeley.boinc D/GraphicBuffer: register, handle(0x7c4cfd1a40) (w:960 h:576 s:960 f:0x1 u:0x000100)
2020-04-04 20:41:23.935 7486-7486/edu.berkeley.boinc D/ViewRootImpl[SplashActivity]: hardware acceleration is enabled, this = ViewRoot{f8a7a13 edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity,ident = 0}
2020-04-04 20:41:23.940 7486-7486/edu.berkeley.boinc V/PhoneWindow: DecorView setVisiblity: visibility = 0, Parent = ViewRoot{f8a7a13 edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity,ident = 0}, this = DecorView@d4c87dd[SplashActivity]
2020-04-04 20:41:23.948 7502-7502/edu.berkeley.boinc:remote V/Monotype: SetAppTypeFace- try to flip, app = edu.berkeley.boinc
2020-04-04 20:41:23.952 7502-7502/edu.berkeley.boinc:remote V/Monotype:     Typeface getFontPathFlipFont - systemFont = default#default
2020-04-04 20:41:23.954 254-254/? I/BufferQueueConsumer: [edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity](this:0x70d3d2e800,id:2815,api:0,p:-1,c:254) setConsumerName: edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity
2020-04-04 20:41:23.954 254-254/? I/BufferQueueConsumer: [edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity](this:0x70d3d2e800,id:2815,api:0,p:-1,c:254) setDefaultBufferSize: width=1 height=1
2020-04-04 20:41:23.957 894-5379/? V/WindowManager: Changing focus from null to Window{5f6868b u0 edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity} Callers=com.android.server.wm.WindowManagerService.relayoutWindow:3155 com.android.server.wm.Session.relayout:227 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:148 
2020-04-04 20:41:23.957 894-5379/? D/WindowManager: Input focus has changed to Window{5f6868b u0 edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity}
2020-04-04 20:41:23.966 7502-7502/edu.berkeley.boinc:remote W/System.err: java.io.FileNotFoundException: /jacoco.exec (Read-only file system)
2020-04-04 20:41:23.966 254-254/? I/BufferQueueConsumer: [edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity](this:0x70d3d2e800,id:2815,api:0,p:-1,c:254) setDefaultBufferSize: width=720 height=1280
2020-04-04 20:41:23.966 7502-7502/edu.berkeley.boinc:remote W/System.err:     at java.io.FileOutputStream.open(Native Method)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at org.jacoco.agent.rt.internal_28bab1d.output.FileOutput.openFile(FileOutput.java:67)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at org.jacoco.agent.rt.internal_28bab1d.output.FileOutput.startup(FileOutput.java:49)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at org.jacoco.agent.rt.internal_28bab1d.Agent.startup(Agent.java:122)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at org.jacoco.agent.rt.internal_28bab1d.Agent.getInstance(Agent.java:50)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at org.jacoco.agent.rt.internal_28bab1d.Offline.<clinit>(Offline.java:31)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at org.jacoco.agent.rt.internal_28bab1d.Offline.getProbes(Offline.java:51)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at edu.berkeley.boinc.client.Monitor.$jacocoInit(Monitor.java)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at edu.berkeley.boinc.client.Monitor.<clinit>(Monitor.java)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at java.lang.Class.newInstance(Native Method)
2020-04-04 20:41:23.967 7502-7502/edu.berkeley.boinc:remote W/System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3253)
2020-04-04 20:41:23.968 7502-7502/edu.berkeley.boinc:remote W/System.err:     at android.app.ActivityThread.-wrap5(ActivityThread.java)
2020-04-04 20:41:23.968 7502-7502/edu.berkeley.boinc:remote W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1617)
2020-04-04 20:41:23.968 7502-7502/edu.berkeley.boinc:remote W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
2020-04-04 20:41:23.968 7502-7502/edu.berkeley.boinc:remote W/System.err:     at android.os.Looper.loop(Looper.java:208)
2020-04-04 20:41:23.968 7502-7502/edu.berkeley.boinc:remote W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6267)
2020-04-04 20:41:23.968 7502-7502/edu.berkeley.boinc:remote W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-04-04 20:41:23.968 7502-7502/edu.berkeley.boinc:remote W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
2020-04-04 20:41:23.968 7502-7502/edu.berkeley.boinc:remote W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
2020-04-04 20:41:23.973 7486-7516/edu.berkeley.boinc D/OpenGLRenderer: CanvasContext() 0x7c4f86b000 initialize window=0x7c56255e00, title=edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity
2020-04-04 20:41:23.973 7486-7486/edu.berkeley.boinc D/Surface: Surface::allocateBuffers(this=0x7c56255e00)
2020-04-04 20:41:23.975 7502-7502/edu.berkeley.boinc:remote V/ActivityThread: SVC-Creating service CreateServiceData{token=android.os.BinderProxy@8563cc6 className=edu.berkeley.boinc.client.Monitor packageName=edu.berkeley.boinc intent=null}
2020-04-04 20:41:23.975 7502-7502/edu.berkeley.boinc:remote D/BOINC_GUI: Monitor onCreate()
2020-04-04 20:41:23.978 7486-7516/edu.berkeley.boinc I/OpenGLRenderer: Initialized EGL, version 1.4
2020-04-04 20:41:23.978 7486-7516/edu.berkeley.boinc D/OpenGLRenderer: Swap behavior 1
2020-04-04 20:41:23.981 7486-7486/edu.berkeley.boinc V/InputMethodManager: onWindowFocus: null softInputMode=288 first=true flags=#81810100
2020-04-04 20:41:23.983 7486-7516/edu.berkeley.boinc D/OpenGLRenderer: Created EGL context (0x7c4f81ec80)
2020-04-04 20:41:23.986 7486-7516/edu.berkeley.boinc D/OpenGLRenderer: ProgramCache.init: enable enhancement 1
2020-04-04 20:41:23.987 7486-7516/edu.berkeley.boinc I/OpenGLRenderer: Get disable program binary service property (0)
2020-04-04 20:41:23.987 7486-7516/edu.berkeley.boinc I/OpenGLRenderer: Initializing program atlas...
2020-04-04 20:41:23.988 7486-7516/edu.berkeley.boinc I/ProgramBinary/Service: ProgramBinaryService client side disable debugging.
2020-04-04 20:41:23.988 7486-7516/edu.berkeley.boinc I/ProgramBinary/Service: ProgramBinaryService client side disable binary content debugging.
2020-04-04 20:41:23.988 7486-7516/edu.berkeley.boinc D/ProgramBinary/Service: BpProgramBinaryService.getReady
2020-04-04 20:41:23.989 7486-7516/edu.berkeley.boinc D/ProgramBinary/Service: BpProgramBinaryService.getProgramBinaryData
2020-04-04 20:41:23.990 7486-7516/edu.berkeley.boinc I/OpenGLRenderer: Program binary detail: Binary length is 182828, program map length is 124.
2020-04-04 20:41:23.990 7486-7516/edu.berkeley.boinc I/OpenGLRenderer: Succeeded to mmap program binaries. File descriptor is 58, and path is /dev/ashmem.
2020-04-04 20:41:23.990 7486-7516/edu.berkeley.boinc I/OpenGLRenderer: No need to use file discriptor anymore, close fd(58).
2020-04-04 20:41:23.990 7486-7516/edu.berkeley.boinc D/OpenGLRenderer: Initializing program cache from 0x0, size = -1
2020-04-04 20:41:23.993 7486-7516/edu.berkeley.boinc D/Surface: Surface::connect(this=0x7c56255e00,api=1)
2020-04-04 20:41:23.994 254-5780/? I/BufferQueueProducer: [edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity](this:0x70d3d2e800,id:2815,api:1,p:7486,c:254) connect(P): api=1 producer=(7486:edu.berkeley.boinc) producerControlledByApp=true
2020-04-04 20:41:23.994 7486-7516/edu.berkeley.boinc W/libEGL: [ANDROID_RECORDABLE] format: 1
2020-04-04 20:41:23.996 7486-7516/edu.berkeley.boinc D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
2020-04-04 20:41:23.997 7502-7502/edu.berkeley.boinc:remote D/MPlugin: com.mediatek.common.telephony.IOnlyOwnerSimSupportClazz exists on mapping table : false
2020-04-04 20:41:23.997 7502-7502/edu.berkeley.boinc:remote E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
2020-04-04 20:41:23.999 7502-7502/edu.berkeley.boinc:remote D/BOINC_GUI: Monitor onCreate(): singletons initialized
2020-04-04 20:41:24.000 7502-7502/edu.berkeley.boinc:remote D/MPlugin: com.mediatek.common.telephony.IOnlyOwnerSimSupportClazz exists on mapping table : false
2020-04-04 20:41:24.000 7502-7502/edu.berkeley.boinc:remote E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
2020-04-04 20:41:24.006 7502-7502/edu.berkeley.boinc:remote D/ActivityThread: SVC-Calling onStartCommand: edu.berkeley.boinc.client.Monitor@d4c87dd, flags=0, startId=1
2020-04-04 20:41:24.006 7502-7502/edu.berkeley.boinc:remote D/BOINC_GUI: Monitor onStartCommand()
2020-04-04 20:41:24.008 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: Monitor.clientSetup()
2020-04-04 20:41:24.009 894-6645/? V/ActivityManager: Broadcast: Intent { act=edu.berkeley.boinc.clientstatuschange flg=0x10 } ordered=false userid=0 callerApp=ProcessRecord{71536bd 7502:edu.berkeley.boinc:remote/u0a571}
2020-04-04 20:41:24.016 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: BOINC platform: aarch64-android-linux-gnu for os.arch: aarch64
2020-04-04 20:41:24.017 7502-7519/edu.berkeley.boinc:remote E/BOINC_GUI: IOException: arm64-v8a/boinc
2020-04-04 20:41:24.018 7502-7519/edu.berkeley.boinc:remote E/BOINC_GUI: IOException: /data/data/edu.berkeley.boinc/client/boinc (No such file or directory)
2020-04-04 20:41:24.033 7486-7516/edu.berkeley.boinc D/OpenGLRenderer: ProgramCache.generateProgram: 0
2020-04-04 20:41:24.037 254-338/? I/BufferQueueProducer: [edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity](this:0x70d3d2e800,id:2815,api:1,p:7486,c:254) new GraphicBuffer needed
2020-04-04 20:41:24.040 7486-7516/edu.berkeley.boinc D/GraphicBuffer: register, handle(0x7c3ae1d0c0) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
2020-04-04 20:41:24.042 7486-7516/edu.berkeley.boinc D/OpenGLRenderer: ProgramCache.generateProgram: 1
2020-04-04 20:41:24.046 254-5780/? I/BufferQueueProducer: [edu.berkeley.boinc/edu.berkeley.boinc.SplashActivity](this:0x70d3d2e800,id:2815,api:1,p:7486,c:254) new GraphicBuffer needed
2020-04-04 20:41:24.049 7486-7516/edu.berkeley.boinc D/GraphicBuffer: register, handle(0x7c3ae1f580) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
2020-04-04 20:41:24.064 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: getPidForProcessName(): /data/data/edu.berkeley.boinc/client/boinc not found in ps output!
2020-04-04 20:41:24.064 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: Starting the BOINC client
2020-04-04 20:41:24.064 7502-7519/edu.berkeley.boinc:remote W/BOINC_GUI: Launching '/data/data/edu.berkeley.boinc/client/boinc' from '/data/data/edu.berkeley.boinc/client/'
2020-04-04 20:41:24.074 894-966/? I/ActivityManager: Displayed edu.berkeley.boinc/.SplashActivity: +558ms [aosp]
2020-04-04 20:41:24.092 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: Starting BOINC client failed with exception: Cannot run program "/data/data/edu.berkeley.boinc/client/boinc" (in directory "/data/data/edu.berkeley.boinc/client"): error=2, No such file or directory
2020-04-04 20:41:24.093 7502-7519/edu.berkeley.boinc:remote E/BOINC_GUI: IOException
    java.io.IOException: Cannot run program "/data/data/edu.berkeley.boinc/client/boinc" (in directory "/data/data/edu.berkeley.boinc/client"): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)
        at java.lang.Runtime.exec(Runtime.java:691)
        at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:649)
        at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:572)
        at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:378)
        at edu.berkeley.boinc.client.Monitor.access$200(Monitor.java:77)
        at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:366)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:128)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)
        at java.lang.Runtime.exec(Runtime.java:691) 
        at edu.berkeley.boinc.client.Monitor.runClient(Monitor.java:649) 
        at edu.berkeley.boinc.client.Monitor.clientSetup(Monitor.java:572) 
        at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:378) 
        at edu.berkeley.boinc.client.Monitor.access$200(Monitor.java:77) 
        at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:366) 
        at java.util.TimerThread.mainLoop(Timer.java:555) 
        at java.util.TimerThread.run(Timer.java:505) 
2020-04-04 20:41:24.093 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: BOINC client failed to start
2020-04-04 20:41:24.102 1550-1550/? D/TaskWatcherService: pkgName: edu.berkeley.boinc taskId: 438
2020-04-04 20:41:24.111 1550-1550/? D/PowerSaverService: current package:edu.berkeley.boinc, activity:edu.berkeley.boinc.SplashActivity, SMode:0, PMode:2
2020-04-04 20:41:24.134 1550-1564/? I/AppOpsStatusUpdateHandler: pkgName = edu.berkeley.boinc
2020-04-04 20:41:24.310 1673-1677/? D/GasService: FG app changed: from com.asus.launcher to edu.berkeley.boinc
2020-04-04 20:41:25.009 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: Monitor.clientSetup()
2020-04-04 20:41:25.011 894-1837/? V/ActivityManager: Broadcast: Intent { act=edu.berkeley.boinc.clientstatuschange flg=0x10 } ordered=false userid=0 callerApp=ProcessRecord{71536bd 7502:edu.berkeley.boinc:remote/u0a571}
2020-04-04 20:41:25.016 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: BOINC platform: aarch64-android-linux-gnu for os.arch: aarch64
2020-04-04 20:41:25.017 7502-7519/edu.berkeley.boinc:remote E/BOINC_GUI: IOException: arm64-v8a/boinc
2020-04-04 20:41:25.018 7502-7519/edu.berkeley.boinc:remote E/BOINC_GUI: IOException: /data/data/edu.berkeley.boinc/client/boinc (No such file or directory)
2020-04-04 20:41:25.067 7502-7519/edu.berkeley.boinc:remote D/BOINC_GUI: getPidForProcessName(): /data/data/edu.berkeley.boinc/client/boinc not found in ps output!`

**Steps To Reproduce**
1.  Clone git repository
2.  Run command -> vagrant up
3.  Login with vagrant/vagrant
4.  Change OPENSSL_VERSION on buildAndroidBOINC-CI.sh to 1.1.1f
5. Run command -> ./build_all.sh
6. Open Android Studio and Import BOINC project
7. Run project

**Expected behavior**
Open the MainActivity.

**Screenshots**

![image](https://user-images.githubusercontent.com/13201694/78459270-38498f80-768e-11ea-8a60-de40fae2ca0f.png)

**System Information**
 - OS: Windows 10 Pro
          VirtualBox 6.1
 - Device: ASUS_X008DB 
                Android 7.0
                arm64-v8a  
 - BOINC Version:  DEVELOPMENT (e90b4780ce)

**Comment by truboxl** [comment] 2020-04-05 04:20
`make clean` doesn't work on OpenSSL 1.1.1f
Change to `MAKECLEAN=""` for all the `build_openssl*.sh`

You should only consider the build successful when you see the line below after running `./build_all.sh`:
`===== BOINC for x86-64 build done =====`

Else you can't move on to Android Studio phase (more errors ahead)

huh, maybe a build complete output line in `./build_all.sh` is desirable

**Comment by thiagopelikan** [comment] 2020-04-05 20:43
Tks @truboxl, now when I run build_all.sh command I get this error:

![image](https://user-images.githubusercontent.com/13201694/78509487-98126a00-7764-11ea-9469-8d4850bac699.png)

I installed curl from command line, it's seems to be working, but shows not usable from build_all script.

Please, help me again!

Tks,
Thiago

**Comment by AenBleidd** [comment] 2020-04-05 20:48
It is a know issue. Unfortunately, it happens only ones on new system sporadically:
Here's a workaround.
Run these commands:
```
./buildAndroidBOINC-CI.sh --arch x86_64 
./buildAndroidBOINC-CI.sh --arch x86 
./buildAndroidBOINC-CI.sh --arch arm64
./buildAndroidBOINC-CI.sh --arch arm
```

**Comment by truboxl** [comment] 2020-04-06 00:48
I usually run this to clear the build before rerunning `./build_all.sh` if it have some unsolvable error
```
cd ~/boinc
git clear -fxd
cd ~/boinc/android
```
If you don't need to build a universal APK that works on all platforms, you can pick and choose AenBleidd's commands (generally not recommended if you run Android Studio emulators)

Hmm, looks like an overhaul of the Android Client is happening soon...

**Comment by thiagopelikan** [comment] 2020-04-06 14:45
Thank you guys, all sh files finished succesfully, but my app is still freezing on splash screen. Now it says:

`2020-04-06 14:35:03.877 22767-22789/? E/BOINC_GUI: CcStateParser.endElement error: 
    java.lang.NumberFormatException: For input string: "17rch64-android-linux-gnu ABI: arm64-v8a3241 Arch 8 Variant 0x0 Part 0xd03 Rev 4]"
        at java.lang.Integer.parseInt(Integer.java:521)
        at java.lang.Integer.parseInt(Integer.java:556)
        at edu.berkeley.boinc.rpc.StringBuilderExtensionsKt.toInt(StringBuilderExtensions.kt:25)
        at edu.berkeley.boinc.rpc.CcStateParser.endElement(CcStateParser.kt:224)
        at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
        at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
        at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
        at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
        at android.util.Xml.parse(Xml.java:57)
        at edu.berkeley.boinc.rpc.CcStateParser$Companion.parse(CcStateParser.kt:261)
        at edu.berkeley.boinc.rpc.CcStateParser.parse(CcStateParser.kt)
        at edu.berkeley.boinc.rpc.RpcClient.getState(RpcClient.java:538)
        at edu.berkeley.boinc.client.Monitor.readClientStatus(Monitor.java:415)
        at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:391)
        at edu.berkeley.boinc.client.Monitor.access$200(Monitor.java:77)
        at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:366)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2020-04-06 14:35:03.878 22767-22779/? I/art: Enter while loop.
2020-04-06 14:35:03.885 22767-22789/? E/BOINC_GUI: CcStateParser.endElement error: 
    java.lang.NumberFormatException: For input string: "07rch64-android-linux-gnu ABI: arm64-v8a3241 Arch 8 Variant 0x0 Part 0xd03 Rev 4]"
        at java.lang.Integer.parseInt(Integer.java:521)
        at java.lang.Integer.parseInt(Integer.java:556)
        at edu.berkeley.boinc.rpc.StringBuilderExtensionsKt.toInt(StringBuilderExtensions.kt:25)
        at edu.berkeley.boinc.rpc.CcStateParser.endElement(CcStateParser.kt:227)
        at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
        at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
        at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
        at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
        at android.util.Xml.parse(Xml.java:57)
        at edu.berkeley.boinc.rpc.CcStateParser$Companion.parse(CcStateParser.kt:261)
        at edu.berkeley.boinc.rpc.CcStateParser.parse(CcStateParser.kt)
        at edu.berkeley.boinc.rpc.RpcClient.getState(RpcClient.java:538)
        at edu.berkeley.boinc.client.Monitor.readClientStatus(Monitor.java:415)
        at edu.berkeley.boinc.client.Monitor.updateStatus(Monitor.java:391)
        at edu.berkeley.boinc.client.Monitor.access$200(Monitor.java:77)
        at edu.berkeley.boinc.client.Monitor$StatusUpdateTimerTask.run(Monitor.java:366)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2020-04-06 14:35:03.894 894-2103/? V/ActivityManager: Broadcast: Intent { act=edu.berkeley.boinc.clientstatus flg=0x10 } ordered=false userid=0 callerApp=ProcessRecord{b5218ad 22767:edu.berkeley.boinc:remote/u0a576}
2020-04-06 14:35:03.996 894-12410/? V/ActivityManager: Broadcast sticky: Intent { act=android.intent.action.SIG_STR flg=0x20000010 (has extras) } ordered=false userid=-1 callerApp=ProcessRecord{14cd0dc 894:system/1000}
2020-04-06 14:35:04.000 1131-1570/? D/NetworkController.MobileSignalController(1): onSignalStre`

But now it's being created a notification icon saying to pickup a project and when I press it opens the taskListActivity. Is this the normal behaviour?

Tks,
Thiago

**Comment by AenBleidd** [comment] 2020-04-06 16:15
It is a known blocker. Unfortunately, it couldn't be solved without
downgrading to an older API. See #3561 for reference
пн, 6 апр. 2020 г. в 16:46, thiagopelikan <notifications@github.com>:

**Comment by thiagopelikan** [comment] 2020-04-08 12:00
Tks @AenBleidd for your help.

The project is running but it still has something wrong on it. When I load de project I get some wrong information on it, see below:

attachService.monitor.getAttachableProjects()

![image](https://user-images.githubusercontent.com/13201694/78781749-2d854800-7977-11ea-9f6b-75bacd771e61.png)

Can you help me with it?

Tks,
Thiago

**Comment by AenBleidd** [comment] 2021-05-08 19:25
I can't reproduce this with current master.
May not be an issue anymore.
Closing for now as 'Works for me'

**Closed by AenBleidd** 2021-05-08 19:25 UTC
Labels: P: Minor, R: worksforme, C: Android - Build
