### ISSUE TITLE
Add a column in tasks tab showing current task ram usage

### ISSUE THREAD

**Issue by kallinenjp** [BOINC/boinc#3862] opened 2020-06-23 16:48 UTC
Tasks don't convey ram usage. Adding a column in the task tab that shows ram usage would allow users to determine if they are hitting bottlenecks.

**Comment by talregev** [comment] 2020-06-26 14:28
I agree. maybe to do it in separate tab like disk. to do memory and do the projects and boinc memory usege.

**Comment by AenBleidd** [comment] 2020-06-26 14:47
The idea of this ticket is to show RAM usage for every task, as far as I understand, so there is no reason to put it into separate tab 'cause then it will not show the information user requires

**Comment by talregev** [comment] 2020-06-26 14:52
I agree with the general idea to show ram usage.
Sometimes it comfortable to show each task, sometime it comfortable to show each project. 
I just suggest another representation of the data.
Don't forget, I am also an User :)

**Comment by AenBleidd** [comment] 2020-06-26 15:13
I know. But imagine you have 2 projects and your machine has 8 cores.
Project 1 runs 7 tasks
Project 2 runs 1 task
It's most likely that Project 1 will use more RAM than Project 2 but what exactly these numbers will show you?
And don't forget: if you have option to leave paused tasks in memory on, you will see also projects that has no running tasks at the moment.
Show overall RAM usage by all tasks is ok, but show also RAM usage by project looks not-necessary for me. Also remember that we still want to have not overloaded UI.

But developing your idea, I can say that it would be interesting to make tree view for tasks. So in this case when grouping tasks by projects it could be possible to show RAM usage for every project.

In this particular case I'd want to refer to Windows Task Manager that has very usable and not overloaded UI that is very similar to our BOINC Manager (not by view but by functionality).

**Comment by AenBleidd** [comment] 2022-10-07 16:10
Closed as a duplicate of #2638

**Closed by AenBleidd** 2022-10-07 16:10 UTC
Labels: C: Manager, P: Minor, R: duplicate, T: Enhancement
