### ISSUE TITLE
Debian 10 BOINC doesnt respect my preferences

### ISSUE THREAD

**Issue by sacredland** [BOINC/boinc#3619] opened 2020-04-20 00:02 UTC
I run BOINC 7.14.2(x64) on debian 10. 
I setted up my calc. pref. to dont calculate when I am using my PC but BOINC still make calcul. 
I setted it to only transfert between 23h and 8h, and it respect that. Why it still use my cpu/ram while I'm using it. I only want it to calc. when the pc idle..

**Comment by AenBleidd** [comment] 2022-10-07 23:10
Closed as a duplicate of #1187

**Closed by AenBleidd** 2022-10-07 23:10 UTC
Labels: P: Major, R: duplicate, T: Defect, C: Client - Linux
