### ISSUE TITLE
RPC commands not returning full data

### ISSUE THREAD

**Issue by makeasnek** [BOINC/boinc#5349] opened 2023-09-03 22:31 UTC
**Describe the bug**
Two RPC commands are not giving the expected output. I am accessing the RPC via pyBOINC (https://github.com/nielstron/pyboinc). While it's possible that this is a bug in pyboinc, it has no trouble returning correct values from other RPC commands in the form of nested dicts and lists. I have checked and it is using a generic parser, not one built for these specific commands.

I was hoping to get output from BOINC with the same information found in the statistics and job_log files. This would be useful for monitoring clients on machines where I can't access this information easily (Android).

`get_statistics` is only reporting stats from one project (yoyo). The stats menu in BOINC client shows credit from multiple projects. Output from `get_statistics` looks like this:
```
{'project_statistics': {'daily_statistics': {'day': '1691107200.000000', 'host_expavg_credit': 0.096338, 'host_total_credit': 477.90899, 'user_expavg_credit': 0.096338, 'user_total_credit': 477.90899}, 'master_url': 'http://www.rechenkraft.net/yoyo/'}}
```
`get_old_results` produces no output, just a `\n`.

**Expected behavior**
get_statistics should be showing stats for all attached projects with credit
get_old_results should be producing a list of old jobs similar to job_log

**System Information**
 - OS: Ubuntu 20.04.6 x64 in a VM
 - BOINC Version: 7.16.6 (x64) installed from Ubuntu repos

**Additional context**
Unfortunately, I think I will be of little help in terms of debugging this. BOINC is working on this machine, so I am hesitant to install other versions and break things. But reporting this in case the current version is also impacted by this.

**Comment by AenBleidd** [comment] 2023-09-03 23:26
@makeasnek, could you please attach a minimal reproducible script with these two commands that don't work for you? Thank you in advance

**Comment by makeasnek** [comment] 2023-09-04 00:19
```
import asyncio,pprint
from typing import Union,Any,Dict,List,Set
import libs.pyboinc as pyboinc
from libs.pyboinc._parse import parse_generic
import xml.etree.ElementTree as ET
async def run_rpc_command(
    rpc_client: pyboinc.rpc_client,
    command: str,
    arg1: Union[str, None] = None,
    arg1_val: Union[str, None] = None,
    arg2: Union[str, None] = None,
    arg2_val: Union[str, None] = None,
) -> Union[str, Dict[Any, Any], List[Any],None]:
    """
    Runs command on BOINC client via RPC. Has try/except and retries, returns None if unsuccessful
    Example: run_rpc_command(rpc_client,'project_nomorework','http://project.com/project')
    """
    max_retries = 3
    retry_wait = 5
    current_retries = 0
    full_command = "{} {} {} {} {}".format(
        command, arg1, arg1_val, arg2, arg2_val
    )  # added for debugging purposes
    req = ET.Element(command)
    if arg1 is not None:
        a = ET.SubElement(req, arg1)
        if arg1_val is not None:
            a.text = arg1_val
    if arg2 is not None:
        b = ET.SubElement(req, arg2)
        if arg2_val is not None:
            b.text = arg2_val
    try:
        response = await rpc_client._request(req)
        parsed = parse_generic(response)
        if not str(parsed):
            print(
                "Warning: Error w RPC command {}: {}".format(full_command, parsed)
            )
            return None
    except Exception as e:
        print("Error w RPC command {} {}".format(full_command, e))
        return None
    else:
        return parsed
async def setup_connection(
    boinc_ip, boinc_password: str = None, port: int = 31416
) -> Union[pyboinc.rpc_client.RPCClient, None]:
    """
    Sets up a BOINC RPC client connection
    """
    rpc_client = None
    if not boinc_ip:
        boinc_ip = "127.0.0.1"
    rpc_client = await pyboinc.init_rpc_client(boinc_ip, boinc_password, port=port)
    return rpc_client
async def get_stats_helper(rpc_client: pyboinc.rpc_client):
    """
    Return stats from BOINC client. Development on this is stalled due to BOINC not returning all stats + projects in testing.
    """
    return_value = []
    reply = await run_rpc_command(rpc_client, "get_statistics")
    job_logs = await run_rpc_command(rpc_client, "get_old_results")
    return reply,job_logs
loop = asyncio.get_event_loop()
RPC_CONNECTION_OBJECT = loop.run_until_complete(
        setup_connection('127.0.0.1')
    )
reply1,reply2=loop.run_until_complete(
    get_stats_helper(RPC_CONNECTION_OBJECT)
    )
print('BOINC stats are below:')
pprint.pprint(reply1)
print('Job log is:')
pprint.pprint(reply2)
```

Output on my BOINC client:
BOINC stats are below:
{'project_statistics': {'daily_statistics': {'day': '1691193600.000000',
                                             'host_expavg_credit': 0.096338,
                                             'host_total_credit': 477.90899,
                                             'user_expavg_credit': 0.096338,
                                             'user_total_credit': 477.90899},
                        'master_url': 'http://www.rechenkraft.net/yoyo/'}}
Job log is:
'\n'

Screenshot from BOINC manager:
![Screenshot_2023-09-03_17-18-28](https://github.com/BOINC/boinc/assets/90811423/063d7241-7629-4720-9b81-aa3f906f4e68)

**Comment by AenBleidd** [comment] 2023-09-04 01:00
Ok, I run your script and was able to reproduce the issue.
Really, in case of the `get_statistics` request it prints only the last result, in case of `get_old_results` is shows empty output.
But this is definitely an issue on the pyboinc side, because using Wireshark I was able to see all the data that was sent from the client.

Closing this as 'invalid'

**Closed by AenBleidd** 2023-09-04 01:00 UTC
Labels: C: Client - Daemon, R: invalid, T: Defect
