### ISSUE TITLE
Ability to set the affinity to CPU cores

### ISSUE THREAD

**Issue by aon3ko** [BOINC/boinc#5436] opened 2023-11-23 07:07 UTC
**Describe the problem**
The contemporary hardware usually has multiple types of CPU cores, but the tasks are always dispatched by the operating system. Which means that the core count limiting option won't effective like before at minimising the impact on usage and efficiency.

**Describe the solution you'd like**
Ability to choose that use efficiency cores only, by setting the core affinity to those tasks.

**Comment by AenBleidd** [comment] 2023-11-23 09:22
Closed as a duplicate of #830

**Closed by AenBleidd** 2023-11-23 09:22 UTC
Labels: C: Client - Scheduler Policy, P: Undetermined, R: duplicate, T: Enhancement
