### ISSUE TITLE
Adding project with weak auth causes CPU lockup, fails to add

### ISSUE THREAD

**Issue by makeasnek** [BOINC/boinc#5090] opened 2023-02-08 07:46 UTC
**Describe the bug**
When adding a project with a weak authenticator (haven't tested with normal auth), BOINC manager proceeds to use 100% of a single CPU core, stall, and then never attach to the project. Running boinccmd I am able to successfully attach to project and see it in BOINC manager upon launch.

**Steps To Reproduce**
1. Open boinc manager
2. Attach to project

**Expected behavior**
Project should be attached to

**System Information**
BOINC in APT: 7.20.5+dfsg+202212021500~ubuntu20.04.1
BOINC Manager: version 7.20.5 (x64)
BOINC version from boinc --version 7.20.5 x86_64-pc-linux-gnu
OS:  Ubuntu 20.04.5 LTS Codename:	focal

**Comment by AenBleidd** [comment] 2023-02-08 08:30
It would be nice if you could specify if that's any project or just some particular one?
Also, could you please attach logs from the client?

**Comment by makeasnek** [comment] 2023-02-08 08:38
Happened with both TN-Grid and WCG. Unfortunately I can't copy from event log due to the lockup.

Nothing interesting in log, most recent entry is "fetching configuration file from https://worldcomm..."

**Comment by AenBleidd** [comment] 2023-02-15 16:35
@makeasnek, IIRC, when using BOINC Manager, you should pass user password, using weak authenticator is not supported on the GUI.

I'm closing this ticket as 'Invalid'

**Closed by AenBleidd** 2023-02-15 16:35 UTC
Labels: C: Manager, P: Minor, R: invalid, T: Defect

**Comment by davidpanderson** [comment] 2023-02-15 18:45
The BOINC client shouldn't lock up no matter what the user does.  If it does that's a bug.

I was unable to reproduce this (with the WCG and BOINC test projects, using the client in master).
If anyone can repro, let me know.

**Comment by AenBleidd** [comment] 2023-02-15 19:08
I was unable to reproduce this either

**Comment by makeasnek** [comment] 2023-04-08 03:23
I ended up finding the a solution for this bug. The cause was /var/lib/boinc-client/gui_rpc_auth.cfg permissions. If I chmod 777 that file, the freezing stops. Probably something that will get solved with new deb packaging, but just wanted to let you know I found the fix and that BOINC Manager did not warn this was the cause (though boinccmd did when not being run as sudo)
