### ISSUE TITLE
If insufficient RAM for tasks in queue, doesn't download tasks from another project to fill CPU

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#5026] opened 2022-11-26 17:29 UTC
**Describe the bug**
I am running two projects on a 24 thread computer with 32GB RAM.  Yoyo doing only "ecm p2" tasks (which use about 7GB RAM each) and NFS (which uses about half a GB each).  Yoyo has higher weight.  Boinc has downloaded a huge queue of Yoyo tasks and can only fit a few of them into RAM.  Then it just sits there with the CPU mostly idle instead of getting NFS work.

**Steps To Reproduce**
1. Attach to Yoyo and NFS only.
2. Set Yoyo to ecm P2 work only on the server.
3. Set yoyo to weight 100, and NFS to weight 0.

**Expected behaviour**
Fill the CPU threads so it's busy with something, even if it's not my first choice of project.

**System Information**
 - OS: Windows 11
 - BOINC Version: 7.20.2

**Comment by AenBleidd** [comment] 2022-11-26 17:45
Duplicate of #4200

**Closed** 2022-11-26 17:46 UTC
Labels: C: Client - Scheduler Policy, R: duplicate, T: Defect

**Comment by hucker75** [comment] 2022-11-26 19:53
Doesn't seem to be the same thing at all.  Not sure what the other user was talking about.  Boinc does correctly avoid overloading RAM, but it doesn't take the opportunity to run smaller tasks if they will fit into the remaining RAM.

**Comment by AenBleidd** [comment] 2022-11-26 20:23
That's a known and exactly the same

**Comment by AenBleidd** [comment] 2022-11-26 20:26
If you want, you can try to reproduce this on simulator: https://boinc.berkeley.edu/sim_web.php

**Comment by davidpanderson** [comment] 2022-11-26 23:30
In principle this would be good to do, but in practice it would be complex.
In the client, when the CPU scheduler hits the memory limit,
it knows how much unused memory there is,
but this number (which could change a lot from moment to moment)
isn't available to the work fetch logic.
The work fetch logic would have to keep track of the smallest-memory
jobs for each project.
The scheduler RPC protocol would have to be changed to specify
a max memory size,
with a corresponding change to the server code
(otherwise the project might send big-memory jobs that we can't run).

**Comment by hucker75** [comment] 2022-11-26 23:34
Yes, it sounds more complex than I thought, but you said "The work fetch logic would have to keep track of the smallest-memory
jobs for each project."

Now in my case I was running a project which always gave jobs requesting 10GB to start, and used an average of 7GB.  and a second project which always gave jobs about 2/3rds of a GB.  When memory becomes tight, the scheduler could ask fo r jobs from projects it knows to be less memory intensive.

**Comment by davidpanderson** [comment] 2022-11-26 23:46
In general projects can have both big and small jobs.
So we'd need a way (which we currently lack) of requesting only small jobs.
Also the client currently doesn't keep track of the per-project
distribution of memory sizes.

**Comment by hucker75** [comment] 2022-11-26 23:57
Ok, sounds more difficult than I thought.  I'll just buy more RAM!
