### ISSUE TITLE
Android: BOINC v7.16.3 testing

### ISSUE THREAD

**Issue by RichardHaselgrove** [BOINC/boinc#3397] opened 2019-12-08 17:53 UTC
**Describe the bug**
Fails to fetch new work

Forked from #3357 

From attached Event log:

8 Dec 2019 17:08:24|Einstein@Home|
[work_fetch] set_request() for Mali-G71: ninst 1 nused_total 0.00 nidle_now 1.00 fetch share 1.00 req_inst 1.00 req_secs 47520.00

8 Dec 2019 17:08:24|Einstein@Home|
[work_fetch] request: CPU (0.00 sec, 0.00 inst) Mali-G71 (47520.00 sec, 1.00 inst)

Einstein project expects CPU request...

**System Information**
 - OS: Android v9
 - BOINC Version: 7.16.3

[Event log.txt](https://github.com/BOINC/boinc/files/3936644/Event.log.txt)

**Comment by magicrub** [comment] 2019-12-08 18:09
(sorry for the off-topic comment) I'm running v7.4.53 which is the latest release on the Play store. It's dated July 3, 2016 which is quite old. I just "joined the Beta" which hopefully gets my version bumped up. Who is in control of the releases? If the major release is old, are the beta's old too? Are they automated? Seems like an official release is overdue

**Comment by RichardHaselgrove** [comment] 2019-12-08 18:10
Ah. After some deeper fiddling, I've got an event log:

> Requesting new tasks for CPU and Mali-G71

and, indeed, a new task like all the other CPU tasks. Beginning to look like I've got a coprocessor in here :)

**Comment by RichardHaselgrove** [comment] 2019-12-08 18:27
While I'm here - and now I've started a bugrep issue - some noob comments from Android v7.16.3 @ a432e1ccbf

* About: copyright 2016, credits truncated ('Thanks to ... IBM Corporation and'

* Tasks tab: turn arrow expands detail display, won't close it again.

* Preferences: client log flags doesn't re-load previous settings (and I'd like sched_op_debug, please). GUI log level seems ineffective so far.

@magicrub - I got my test version v7.16.3 from [APKMirror](https://www.apkmirror.com/apk/space-sciences-laboratory-u-c-berkeley/boinc/boinc-7-16-3-a432e1ccbf-release/boinc-7-16-3-a432e1ccbf-android-apk-download/)

**Comment by AenBleidd** [comment] 2019-12-08 18:30
Tasks tab is already fixed in master

**Comment by sunk818** [comment] 2019-12-09 18:41
@magicrub Yes, in the Play Store, there's a join beta button (at the bottom of BOINC details screen in Play Store). Once you join, your green button at the very top should change from "Open" to "Update". Update meaning you have the option to install the BETA. Once you Update, it'll change to Open again... and when you run the BOINC beta, check the version in the About page.

Under Preferences, you should see some new UI options if you check on the advanced options. The main one I wanted was the ability to rename android device name.

**Comment by RichardHaselgrove** [comment] 2019-12-11 12:28
Following discussion with @AenBleidd on Monday, further points arising in testing and with debug test apk supplied by Vitali

1) Found that tablet had a 'screensaver mode' which prevented it killing BOINC when the screen went blank. In this mode, it runs all night, no problem.

2) Finished all work, uninstalled BOINC - still couldn't install debug apk (same failure message as Monday)

3) Re-installed v7.16.3 - at end of installation, shows a message that 'computation will start when screen is blanked. But see (1).

4) You are right - uninstall deletes everything (accounts, preferences, user name etc). Reinstall gives the device a new name.

5) On reinstall, I was shown a full list of projects, and chose just one (Einstein). Now, I can't add any more, either from menu or from top-right of projects tab. BOINC logo screen opens, but content area is blank.

6) Can't suspend tasks while they're in cache, unstarted. Can suspend them (instantly) when running: unsuspend process takes a long time.

**Comment by RichardHaselgrove** [comment] 2020-01-14 17:24
The Android client GUI seems to have no way of retrying a stuck upload. Often, when I give the tablet a prod to see what it's up to, I find four completed tasks, all trying and failing to upload. Interestingly, the 'tablet wake up prod'seems to initiate, first work fetch, and them disposal of the stuck tasks. Judging by the project website, the tasks have been stuck for the best part of two days. Event Log shows failures for both uploads and RPCs.

I've been leaving the tablet with  BOINC Manger in the foreground, and kept awake by a screensaver.

**Comment by AenBleidd** [comment] 2020-01-14 17:33
You are not completely right. Sometimes such situation really happen. It's not so often and have no exact steps to reproduce. But mainly it works fine. It could happen that smth happens with the project itself, e.g. today I have connection issues to SETI servers on desktop too.

**Comment by RichardHaselgrove** [comment] 2020-01-14 18:13
I'm familiar with project upload errors - I'm only running Einstein, and I've helped them with a periodic failure transferring data onwards from gateway to backing store. It was, specifically, the lack of a 'retry upload' control in the GUI that made me post.

I'm thinking it's got worse since the last major Samsung OS update, but I have no way of inspecting the state while the screensaver is active, and clearing the screensaver seems to clear the WiFi fault, too.

**Comment by IRainman** [comment] 2020-03-12 12:12
> 
> 
> Tasks tab is already fixed in master

Please release new BETA version in Google Play! It's very important, I want to help with testing on Android 10, but I can't :(

**Comment by IzzySoft** [comment] 2021-03-03 20:04
> The Android client GUI seems to have no way of retrying a stuck upload. Often, when I give the tablet a prod to see what it's up to, I find four completed tasks, all trying and failing to upload. Interestingly, the 'tablet wake up prod'seems to initiate, first work fetch, and them disposal of the stuck tasks.

I currently have 3 tasks hanging in "uploading", some of them for more than 36h already, most of them expiring tomorrow. That's very sad and wasted resources. Interestingly that happens only on one of my devices so far. That very same device now additionally has 2 tasks hanging in "downloading".

I tried all kind of "prodding" (incl. refreshing the project, "retrying" the project, rebooting the device) with no success. What's also strange is that the counter telling "next try in…" is counting **UP** instead of down. Active projects on that device are Rosetta and Universe; the other device only gets work from Universe and has no issues at all. Both run on Android 8.1 (the working one in fact on Android Go 8.1, while the other one runs LineageOS).

As there are not even helpful log messages (neither in the event log nor in logcat) it's hard to tell what the issue is. In logcat I only see `BOINC_GUI: java.io.IOException: Connection refused` with the next line saying `at android.net.LocalSocketImpl.connectLocal(Native Method)` (so I'm not even sure it's related: does upload happen via a local socket?). I wish it would log something like "server responded with [418 I'm a teapot](https://en.wikipedia.org/wiki/HTTP_418)" so we knew what's going on.

For now I've set all projects to not accept new work, as I was not able to upload even a single task from that device: makes no sense to download, process and then throw away. If there's any way how I could successfully prod such "stalled uploads", hints are welcome. I can work on the shell if needed (via ADB), and root access is available. So if there's a way to trigger upload by calling an intent, the command line would do perfectly.

**Comment by AenBleidd** [comment] 2021-03-03 20:08
@IzzySoft, what project has these staled uploads? Were there other successfully uploaded tasks of the same project? Could you please check the status of these tasks on projects page?

**Comment by IzzySoft** [comment] 2021-03-03 20:12
@AenBleidd sure: on the "stuck device" **ALL** tasks are stuck – projects are Rosetta@Home (upload) and Universe@Home (download) with both projects having tasks processed already. On the working device it's only Universe@Home. Lifting my cover (we can redact that later): https://universeathome.pl/universe/results.php?userid=223951 – you can easily tell which client is which. 588829 is the one having the issues, 587974 has no issues at all (those link should also give you further device details which might help).

**Comment by AenBleidd** [comment] 2021-03-03 20:17
These links are accessible for you only ;)

**Comment by IzzySoft** [comment] 2021-03-03 20:19
OK, take these:

https://universeathome.pl/universe/workunit.php?wuid=64211068
https://universeathome.pl/universe/workunit.php?wuid=64287320
https://universeathome.pl/universe/workunit.php?wuid=64328428
https://boinc.bakerlab.org/rosetta/workunit.php?wuid=1203108011
https://boinc.bakerlab.org/rosetta/workunit.php?wuid=1203108125
https://boinc.bakerlab.org/rosetta/workunit.php?wuid=1203107356

**Comment by RichardHaselgrove** [comment] 2021-03-03 20:22
Or try https://boinc.bakerlab.org/rosetta/hosts_user.php?userid=2346263

When things stop uploading or downloading, I usually find the device has failed to reconnect to WiFi. Check connection status...

**Comment by IzzySoft** [comment] 2021-03-03 20:24
@RichardHaselgrove that was my first thought. Opened a browser on the device, and could connect fine to any website. Just tapped the project now and then "open website", opens fine.

**Comment by AenBleidd** [comment] 2021-03-03 20:28
@IzzySoft, if you try to enable http_debug flag and retry upload/download, do you see smth interesting in event log?

**Comment by IzzySoft** [comment] 2021-03-03 20:39
I already had that enabled. Event log stays empty. It worked once after a reboot, but now is empty again. logcat only shows entries for BOINC_GUI. Ah wait, this time there's something in logcat:

28561 28561 E UrlLoad : onPageLoadComplete() - url: https://boinc.bakerlab.org/rosetta/

But that's all. Just a single line, despite of multiple tries. So I'm not even sure it comes from BOINC or rather from when I opened that page with the browser. Retrying the browser: yupp, it was that.

**Comment by AenBleidd** [comment] 2021-03-03 20:48
If log is empty - then BOINC client doesn't working. You said you're able to connect with adb. Could you please then check in running processes whether 'boinc' is running?

**Comment by AenBleidd** [comment] 2021-03-03 20:50
@IzzySoft, could you please join Discord server ( https://discord.gg/wPRafUq ) and write me there? This could speed-up things a little bit.

**Comment by IzzySoft** [comment] 2021-03-03 21:15
@AenBleidd Sorry, but does that also need my shoe size? Any other chat we could use, like IRC, XMPP, Jitsi…? I'm not willing to strip-tease there.

**Comment by AenBleidd** [comment] 2021-03-03 21:17
@IzzySoft, nevermind, let's continue here then.

**Comment by IzzySoft** [comment] 2021-03-03 21:24
OK, thanks. Anything I should try? My last running task now is at 97.87%, so soon I have everything on pending. Could then eg force-kill/restart (though I doubt that does anything but might get the event log working again). If there's a way to transfer completed tasks to another device using the same account to have it uploaded, I could try that as well.

**Comment by AenBleidd** [comment] 2021-03-03 21:27
Try to restart your device and run BOINC again. Then please check the log again. If it's empty again - connect ADB and check whether 'boinc' is among the running processes

**Comment by IzzySoft** [comment] 2021-03-03 21:42
Pre-reboot:

```
$ ps -ef |grep boinc                                                                                                                                                                                                             
shell         6995 32070 0 22:29:34 pts/0 00:00:00 grep boinc
u0_a121      18136 15253 0 02:06:30 ?     00:03:06 edu.berkeley.boinc
u0_a121      18161 15253 3 02:06:31 ?     00:40:27 edu.berkeley.boinc:remote
u0_a121      18481     1 1 02:06:55 ?     00:10:43 boinc --daemon --gui_rpc_unix_domain
```

post-reboot (before opening the UI):

```
$ ps -ef |grep boinc
u0_a121       5664   269 5 22:32:56 ?     00:00:01 edu.berkeley.boinc
u0_a121       5682   269 11 22:32:58 ?    00:00:03 edu.berkeley.boinc:remote
u0_a121       5750     1 8 22:33:00 ?     00:00:02 boinc --daemon --gui_rpc_unix_domain
u0_a121       6019     1 0 22:33:21 ?     00:00:00 boinc --daemon --gui_rpc_unix_domain
shell         6055  5409 0 22:33:30 pts/0 00:00:00 grep boinc
```

Event log now available, but only in the GUI tab. Logcat shows a ton of

```
5682  5732 W BOINC_GUI: connect failure: IO
5682  5732 W BOINC_GUI: java.io.IOException: Connection refused
5682  5732 W BOINC_GUI:     at android.net.LocalSocketImpl.connectLocal(Native Method)
5682  5732 W BOINC_GUI:     at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
5682  5732 W BOINC_GUI:     at android.net.LocalSocket.connect(LocalSocket.java:145)
5682  5732 W BOINC_GUI:     at edu.berkeley.boinc.m.q0.z(Unknown Source:35)
5682  5732 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor.j(Unknown Source:11)
5682  5732 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor.h(Unknown Source:287)
5682  5732 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor.I(Unknown Source:14)
5682  5732 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor.g(Unknown Source:0)
5682  5732 W BOINC_GUI:     at edu.berkeley.boinc.client.Monitor$a.run(Unknown Source:2)
5682  5732 W BOINC_GUI:     at java.util.TimerThread.mainLoop(Timer.java:555)
5682  5732 W BOINC_GUI:     at java.util.TimerThread.run(Timer.java:505)
```

Then, much later: `E BOINC   : 03-Mar-2021 22:33:32 Another instance of BOINC is running.` Then, a little later:

```
5664  5664 E BOINC_GUI: NoticesFragment.onResume error:.
5664  5664 E BOINC_GUI: java.lang.NullPointerException
5664  5664 E BOINC_GUI:     at edu.berkeley.boinc.c.G0(Unknown Source:26)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.Fragment.f1(Unknown Source:17)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.r.m(Unknown Source:33)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.m.C0(Unknown Source:253)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.m.B0(Unknown Source:2)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.m.z0(Unknown Source:58)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.m.A0(Unknown Source:47)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.m.J(Unknown Source:9)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.m.H(Unknown Source:6)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.h.p(Unknown Source:4)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.d.w(Unknown Source:9)
5664  5664 E BOINC_GUI:     at androidx.fragment.app.d.onPostResume(Unknown Source:3)
5664  5664 E BOINC_GUI:     at androidx.appcompat.app.e.onPostResume(Unknown Source:0)
5664  5664 E BOINC_GUI:     at android.app.Activity.performResume(Activity.java:7141)
5664  5664 E BOINC_GUI:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556)
5664  5664 E BOINC_GUI:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621)
5664  5664 E BOINC_GUI:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862)
5664  5664 E BOINC_GUI:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
5664  5664 E BOINC_GUI:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
5664  5664 E BOINC_GUI:     at android.os.Handler.dispatchMessage(Handler.java:106)
5664  5664 E BOINC_GUI:     at android.os.Looper.loop(Looper.java:164)
5664  5664 E BOINC_GUI:     at android.app.ActivityThread.main(ActivityThread.java:6494)
5664  5664 E BOINC_GUI:     at java.lang.reflect.Method.invoke(Native Method)
5664  5664 E BOINC_GUI:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
5664  5664 E BOINC_GUI:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Tasks are still hanging as before. My last running one fell back to 95% (I should probably have properly paused it before). No word about http.

**Comment by IzzySoft** [comment] 2021-03-03 22:08
Contents of the Rosetta project folder, in case that tells you something:

```
drwx------ 3 u0_a121 u0_a121      4096 2021-03-02 00:02 database_357d5d93529_n_methyl
-rwxr-xr-x 1 u0_a121 u0_a121 507570722 2021-03-01 17:30 database_357d5d93529_n_methyl.zip
-rw------- 1 u0_a121 u0_a121         0 2021-03-02 00:08 database_357d5d93529_n_methyl.zip.is_bad
-rw-r--r-- 1 u0_a121 u0_a121  18703709 2021-03-01 17:29 drhicks1_fd_710d6f16_egg_140_102_3b6_4_000000098_0001_PJS-I-23D_xtl_ROSETTA_relax_super2_SAVE_ALL_OUT_IGNORE_THE_REST_1aa1aa1a.zip
-rw------- 1 u0_a121 u0_a121      8665 2021-03-03 00:45 drhicks1_fd_710d6f16_egg_140_102_3b6_4_000000098_0001_PJS-I-23D_xtl_ROSETTA_relax_super2_SAVE_ALL_OUT_IGNORE_THE_REST_1aa1aa1a_1211032_3476_0_r755802094_0
-rw-r--r-- 1 u0_a121 u0_a121  19520171 2021-03-01 17:29 drhicks1_fd_b01107a3_egg_150_5651_82b_1_000000017_0001_PJS-I-36B_orn1_ROSETTA_super_SAVE_ALL_OUT_IGNORE_THE_REST_1aa1aa1a.zip
-rw------- 1 u0_a121 u0_a121      8020 2021-03-02 16:36 drhicks1_fd_b01107a3_egg_150_5651_82b_1_000000017_0001_PJS-I-36B_orn1_ROSETTA_super_SAVE_ALL_OUT_IGNORE_THE_REST_1aa1aa1a_1211348_3476_0_r568000070_0
-rw-r--r-- 1 u0_a121 u0_a121       191 2021-03-01 17:29 flags_710d6f16
-rw-r--r-- 1 u0_a121 u0_a121       191 2021-03-01 17:29 flags_b01107a3
-rw-r--r-- 1 u0_a121 u0_a121       579 2021-03-01 17:28 fr_flags_bcov2
-rw-r--r-- 1 u0_a121 u0_a121      3684 2021-03-01 17:28 miniprotein_relax7_SAVE_ALL_OUT_IGNORE_THE_REST_0oa0nn5h.flags
-rw-r--r-- 1 u0_a121 u0_a121   1681037 2021-03-01 17:28 miniprotein_relax7_SAVE_ALL_OUT_IGNORE_THE_REST_0oa0nn5h.zip
-rw------- 1 u0_a121 u0_a121    482156 2021-03-02 09:34 miniprotein_relax7_SAVE_ALL_OUT_IGNORE_THE_REST_0oa0nn5h_1213627_13_0_r927302239_0
-rwxr-xr-x 1 u0_a121 u0_a121 155125016 2021-03-01 17:28 rosetta_4.20_arm-android-linux-gnu
```

contents of the `flags_710d6f16` file:

```
-parser:protocol dock_and_relax.xml
-beta
-multithreading:total_threads 1 
-default_max_cycles 200 
-in:file:extra_res_fa BAC.params  KAC.params
-parser:script_vars ddg_gate=-40 cms_gate=400
```

Should you need some other content, just let me know. Thanks to root powers, I can access them (on that device).

**Comment by AenBleidd** [comment] 2021-03-03 22:09
Please send me here the content of these files:
- stdoutdae.txt
- stderrdae.txt

**Comment by IzzySoft** [comment] 2021-03-03 22:17
That's quite a bit long, so it comes as [stderr_out.zip](https://github.com/BOINC/boinc/files/6079520/stderr_out.zip) (I skipped the 200M big `stdoutdae.old`).

**Comment by IzzySoft** [comment] 2021-03-03 22:25
`Suspending network activity - user request` probably refers to "no new tasks". I hope that isn't also interpreted as "do not upload either". Btw, what does the "Reset" entry in the project's context menu stand for? I didn't dare touching that as I did not want to drop the finished work.

**Comment by AenBleidd** [comment] 2021-03-03 22:30
Try to disable 'gui_rpc_debug' flag and restart device again, then check 'stdoutdae.txt' file again

**Comment by AenBleidd** [comment] 2021-03-03 22:38
> I hope that isn't also interpreted as "do not upload either"

No, it affects only requests for new tasks.

> Btw, what does the "Reset" entry in the project's context menu stand for?

Remove all files from project folder (including tasks) and reload everything again (all running/incomplete tasks will be aborted and lost forever)

**Comment by IzzySoft** [comment] 2021-03-03 22:43
What was that? All network tasks flushed suddenly! Not sure yet what happened to the uploads, but the pending downloads were completed now. [stdoutdae.zip](https://github.com/BOINC/boinc/files/6079616/stdoutdae.zip)

**Comment by AenBleidd** [comment] 2021-03-03 22:45
Looks like GUI just overloads client with tons of RPC requests. I'll investigate why it's happened (actually, I maybe know why it's happened but still need to work on it)

**Comment by AenBleidd** [comment] 2021-03-03 22:47
> Not sure yet what happened to the uploads, but the pending downloads were completed now

Uploaded and verified: https://boinc.bakerlab.org/rosetta/results.php?hostid=6040651

**Comment by IzzySoft** [comment] 2021-03-03 22:50
Thanks! As long as you already have an idea, that's "light at the end of that tunnel" (and hopefully not the headlights of an oncoming train :rofl:). Do you suggest I could re-enable new tasks then? And how to  "shake loose" future hanging downloads?

And yes, just saw that confirmation. Mighty relief that crunching wasn't wasted (as little as it was). And, more importantly, we didn't "bork" the F-Droid build! That would have been nasty…

**Comment by AenBleidd** [comment] 2021-03-03 22:53
> Do you suggest I could re-enable new tasks then?

Yes.

> And how to "shake loose" future hanging downloads?

Try not to enable all log flags :)
Usually if you see stale downloads/uploads/task, that could be not true, and you need just to restart app (because it could happen that client already did all this but Manager just lost the connection to client and continue showing outdated info).

I have this in my backlog to avoid such situations as much as possible

**Comment by IzzySoft** [comment] 2021-03-03 23:03
> Try not to enable all log flags :)

Now guess why I did that (hint: I was looking for guidance because of something that wasn't working as expected; hint2: that something had to do with finished tasks not being uploaded; hint3: nothing showed up when toggling those flags – found out much later that changing them doesn't only need restarting the client, but rebooting the device; not exactly what a user would expect :wink:)

Or, in other words, cause and effect were bidirectional it seems?

> Usually if you see stale downloads/uploads/task … just to restart app

Force-close and restart? Because I see no door marked "Exit".

> I have this in my backlog to avoid such situations as much as possible

Thanks! I hope I didn't cause too much annoyance with this. But at least now it's documented in this issue and can be found – until a future version makes it easier for the user.

Should you need me to debug something again, just let me know: I'll keep on crunching. Luckily BOINC now starts automatically at boot (that trick with excluding it from battery optimization is now definitely confirmed, as often as I've booted today).

**Comment by AenBleidd** [comment] 2021-03-03 23:08
> Now guess why I did that 

I know :-D

> Or, in other words, cause and effect were bidirectional it seems?

Looks like, I'll investigate this

> Force-close and restart? Because I see no door marked "Exit".

Close (swipe it away from Task Manager (or how it's called on Android?)), restart Manager. That should be enough in most cases.

> I hope I didn't cause too much annoyance with this.

No, that's fine :) You gave me a lot of good information to work with.

> Should you need me to debug something again, just let me know

For sure, thanks for your help with testing!

**Comment by AenBleidd** [comment] 2021-04-28 00:39
This thread is about testing 7.16.3 that is too old for now.
Newer messages are related to 7.16.16 testing. Instead of using 1 thread for every possible issue it's better to open separate tickets for better handling.
Closing this as most (or all) issues mention here either documented in a separate tickets or already fixed.

**Closed by AenBleidd** 2021-04-28 00:39 UTC
Labels: C: Android - Manager, P: Major, R: wontfix, T: Task, E: 1 month
