### ISSUE TITLE
Android BOINC Mgr switches to Notices tab when screen orientation changes

### ISSUE THREAD

**Issue by sirzooro** [BOINC/boinc#1907] opened 2017-05-04 22:33 UTC
One time I noticed that when I changed device orientation from vertical to horizontal, BOINC Mgr was both changing screen orientation and switching from Tasks to Notices tab. This happened every time I changes device orientation, I always ended on Notices tab. After BOINC restart problem disappeared.

**Comment by ChristianBeer** [comment] 2017-05-05 16:00
On what operating system does this happen? Windows or Android? I believe you mean a Windows tablet but I want to make sure.

**Comment by darrholz** [comment] 2017-05-08 16:12
Does not happen on my Samsung Galaxy Phone, or Polaroid Tablet.

**Comment by brevilo** [comment] 2017-08-02 09:35
We definitely need a way to reproduce this problem to be able to analyze and fix it. At the very least we need to the hardware and Android version you use.

Thanks

**Comment by sirzooro** [comment] 2017-08-08 23:01
Xiaomi Redmi 3
Android 5.1.1 LMY47V
MIUI 7.4 by ManhIT 6.5.12 (dev version)
Kernel 3.10.49-perf-ga1f7bc4

**Comment by brevilo** [comment] 2017-08-09 08:14
I can't reproduce it on AOSP 5.1.1 with a recent BOINC (981b0409d3). Does Xiaomi provide its own Android flavor or is it AOSP?

Also, you said "One time" and "After BOINC restart problem disappeared". Does this mean this only happened once to you or does the problem still persist?

**Comment by sirzooro** [comment] 2017-08-09 09:16
Yes, it uses MIUI https://en.wikipedia.org/wiki/MIUI

**Comment by brevilo** [comment] 2017-08-09 09:35
I'm still not sure I understand the event flow here. Can you write the exact list of steps required to reproduce the problem, incl. prerequisites like having used a popup notification before should that indeed be the case. Thanks.

**Comment by sirzooro** [comment] 2017-08-09 09:47
I do not have exact steps, only I suspect that popups may be involved. I think about following scenario:
1. BOINC Client works in background. Task list view is active, it will be displayed after I bring app on top;
2. Phone is locked;
3. Some notification come from project;
4. After some time when I decide to check something on the phone, I notice that there is BOINC icon on the top of screen, so I slide down to display list of active popups;
5. From popup list I select BOINC one. BOINC Client gets focus and switches to notification view, to display selected project news;
6. After I finish reading, I switch back to task list and minimize app.
7. When I bring app on top again, it starts working incorrectly.

I suspect that something like this may trigger this bug. It also may be that popup will appear when phone is unlocked, and I immediately click on it when it is still displayed on top of the screen.
It also may be that I kept BOINC Client active in last step, instead of minimizing it.

**Comment by adamradocz** [comment] 2019-10-02 18:52
Screen orientation works perfectly on v7.14.1.
Can we close this issue?

**Comment by AenBleidd** [comment] 2019-10-02 19:15
@adamradocz, were you able to follow the steps mentioned previous message?

**Comment by adamradocz** [comment] 2019-10-02 19:18
I stuck on point 3. I've never gotten any notification on android.

**Comment by AenBleidd** [comment] 2021-06-18 15:07
This should be already fixed in next release.

**Closed by AenBleidd** 2021-06-18 15:07 UTC
Labels: C: Android - Manager, E: to be determined, P: Minor, R: fixed, T: Defect
