### ISSUE TITLE
Snooze GPU(x)

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1264] opened 2015-02-04 05:53 UTC
**Reported by Ageless on 11 Oct 43463256 16:21 UTC**
As per a [forum feature request](http://boinc.berkeley.edu/dev/forum_thread.php?id=6375&postid=49062) by TRuEQ & !TuVaLu [[br]]
''It would be nice to have an option for "snooze Gpu(X) where there today is snooze GPU down at the windows clock icon when right-clicking the BM icon. ''

''Since I might want to use the GPU, maybe to see a movie and that is connected to my primary display, then it would be nice to snooze that particular GPU and still use all other Gpu's for Boinc. ''

''Today the only way to temporarily do this is to snooze all Gpu's or write a config file.''

''A snooze Gpu(X) would make it alot smoother. ''

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1292

**Comment by informatorius** [comment] 2015-10-25 11:22
Multiple gpus using amd crossfire or nvidia sli for games are more popular today. 
I also like to see this feature.

**Comment by ChristianBeer** [comment] 2017-04-11 12:07
Needs #1149 (reorganization of how the Client handles GPUs)

**Comment by AenBleidd** [comment] 2018-10-25 15:35
Closed as a duplicate of #1432 with more general approach

**Closed by AenBleidd** 2018-10-25 15:35 UTC
Labels: C: Manager, E: 1 week, P: Major, R: duplicate, T: Enhancement
