### ISSUE TITLE
Look and feel of the Stats tab of BOINC manager.

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#754] opened 2015-02-04 02:06 UTC
**Reported by Peter Moss on 7 Aug 38887569 02:40 UTC**
Graphics on the Statistics Tab of BOINC manager.
This is more of a look and feel change to Y-Axes. Get rid of the extraneous decimal points. i.e. A scale with 6 ticks 28660.0 down to 28560.0 each ending in 0.0 is silly/un-necessary, you do not need the '.0' on the ends of each and every one!

Migrated-From: http://boinc.berkeley.edu/trac/ticket/777

**Comment by ChristianBeer** [comment] 2017-04-06 13:52
Duplicate of #656

**Closed by ChristianBeer** 2017-04-06 13:52 UTC
Labels: C: Manager, P: Minor, T: Enhancement
