### ISSUE TITLE
Consolidate wikis on GitHub

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3966] opened 2020-08-07 08:58 UTC
I think that the [wikis](https://boinc.berkeley.edu/trac/wiki) should be consolidated in one place [here on GitHub](https://docs.github.com/en/github/building-a-strong-community/about-wikis). To me this would make them more readable, navigable, easier to edit, and easier to discover for people contributing to or looking at the repository.

**Comment by AenBleidd** [comment] 2020-08-07 09:25
Closed as a duplicate of #2820

**Closed by AenBleidd** 2020-08-07 09:25 UTC
Labels: C: Client - Documentation, C: Server - Documentation, R: duplicate
