### ISSUE TITLE
Move proposed developments from trac/wiki to GitHub as Issues

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc#2822] opened 2018-11-14 17:42 UTC
For better project management the still valid [proposed developments on track/wiki](https://boinc.berkeley.edu/trac/wiki/DevProjects) should be moved to GitHub as issues.

Any thoughts on this?

**Comment by lfield** [comment] 2018-11-15 09:12
This is a duplicate of #2820. But agree that this should be moved to CONTRIBUTING.md and reference the [BOINC policies](https://github.com/BOINC/boinc-policy).

**Comment by adamradocz** [comment] 2018-11-15 10:07
I think similar but slightly different. The #2820 only a Wiki -> Wiki migration, but this issue propose to create issues all the proposed development projects and simply delete them from the wiki.

**Comment by AenBleidd** [comment] 2023-05-14 11:42
All major ideas were already published on GitHub as issues.

**Closed by AenBleidd** 2023-05-14 11:42 UTC
Labels: C: Undetermined, P: Undetermined, T: Task, E: to be determined
