### ISSUE TITLE
Error on home pages on few projects.

### ISSUE THREAD

**Issue by Zwirzu** [BOINC/boinc#2166] opened 2017-10-16 09:47 UTC
I wanted at first report to projects but looks like problem is on boinc side.
I am running Windows 7 32bit. Chrome 61.0.3163.100. The same erron on Android 4.4.2 running Chrome.
My language is Set to Polish. Didn't check on other language settings.
![error1](https://user-images.githubusercontent.com/30357555/31605865-c788ef44-b267-11e7-8d62-a3fa286535e5.png)
![error2](https://user-images.githubusercontent.com/30357555/31605866-c7aa8eec-b267-11e7-89a5-930e573803fa.png)

**Comment by Zwirzu** [comment] 2017-10-16 09:52
Just checked - when set to english there is no problem, other languages the same problem.

**Comment by sirzooro** [comment] 2017-10-23 18:20
This is duplicate of https://github.com/BOINC/boinc/issues/1706. Polish translation needs update.

**Comment by JuhaSointusalo** [comment] 2017-10-23 19:58
Closing as duplicate of #1706 (thanks @sirzooro).

@Zwirzu @sirzooro Please consider helping us to get the Polish translation up to date. If you are even remotely interested see [How to help translate BOINC](https://boinc.berkeley.edu/trac/wiki/TranslateIntro).

**Closed by JuhaSointusalo** 2017-10-23 19:58 UTC
