### ISSUE TITLE
Difference between signup.php and create_account_form.php

### ISSUE THREAD

**Issue by abowery** [BOINC/boinc#3270] opened 2019-09-04 11:13 UTC
This is in server version 1.0.3. Please cancel this bug if this has been fixed in 1.0.4.

BOINC has two means of signing up to a project: signup.php and create_account_form.php
Both are accessible through the main page (index.php).

I am currently implementing the changes required for GDPR 
(https://boinc.berkeley.edu/trac/wiki/GdprCompliance)
I have implemented on our dev site the part to show the  'Terms and Conditions'. 

The bug is that one page shows the 'Terms and Conditions' and the other page doesn't.
This can be seen on our dev site in:

https://dev.cpdn.org/create_account_form.php

And:

https://dev.cpdn.org/signup.php

As a result of this I have changed the signup link on the dev site page to point to create_account_form, however this will need to be fixed in BOINC source code.

**Comment by AenBleidd** [comment] 2019-09-04 11:38
Closing this as a duplicate of #2869
@abowery, please take a look at this issue and the comments there

**Closed by AenBleidd** 2019-09-04 11:38 UTC
Labels: R: duplicate
