### ISSUE TITLE
Support for upcoming Macs with Apple Silicon

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3867] opened 2020-06-24 16:47 UTC
As I understand these will be ARM-based: https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/.

**Comment by AenBleidd** [comment] 2020-06-24 18:07
Closed as a duplicate of #3827

**Closed by AenBleidd** 2020-06-24 18:07 UTC
Labels: R: duplicate
