### ISSUE TITLE
Removing an upload/download rate preference does not return speeds to maximum for in-progress uploads/downloads

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1071] opened 2015-02-04 04:28 UTC
**Reported by JacobKlein on 29 Jul 41291932 02:13 UTC**
If I change a download rate preference to something like 5KB/sec, I can see the speed drop down to match it.

However, if I then clear the preference (or type 0.00 in it), BOINC appears to keep the speed at 5KB/sec unless I restart BOINC.

If I change the preference to something like 9999 before restarting BOINC, I can see the speeds resume.

Essentially, the mechanism that sets BOINC to max speed is not being restored when a speed limit preference is removed.

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1095

**Comment by romw** [comment] 2015-02-04 23:31
**Commented by JacobKlein on 22 Apr 41292184 12:53 UTC**
To clarify, it does not resume maximum speed for the downloads/uploads already in progress. It will use maximum speed for other new downloads/uploads.

So, essentially, I'm asking that the maximum speed setting be set on downloads/uploads that are in progress.

**Comment by lfield** [comment] 2018-10-12 08:50
I have just tested this. I can confirm that if I change the limit it affects existing transfers but if I remove the limit it does not affect existing transfers and they continue at the old limit.

**Comment by Vulpine05** [comment] 2022-07-04 17:07
The source of this problem is here:
https://github.com/BOINC/boinc/blob/beb630e982da5ef8111387307ca4a4a64b42293c/client/file_xfer.cpp#L438
If the bandwidth limit is removed (i.e., changed to 0), then the function for adjusting the bandwidth limit ends at this point.  Any new transfers added to file_xfer_set are initialized to 0 (through libcurl, from what I can tell, source is [https://curl.se/libcurl/c/CURLOPT_MAX_SEND_SPEED_LARGE.html](url)), which is why their bandwidth limit isn't affected.

Possible solutions:

1. Instead of exiting the function when the setting is at 0, go through all active transfers and set to be 0.  The problem with this solution is for each time preferences are read and stored (including at initialization) it adds a little bit more computing time for users that don't have bandwidth limits set.  I'm guessing the time is minimal, and it isn't going to be any different than what a user WITH bandwidth limits would experience.
2. Add some kind of check each time preferences are read, and if the upload/download rate changes from >0 to 0 while the client is running, adjust the active transfers at that case.  I think this isn't preferred; it would make the code a bit more complicated for a niche case.

I did a quick test with option 1 and it appears to work.  It is a little hard to tell because all files were a few kb, so they transferred quickly once I set the bandwidth to unlimited.
Also, passing 0 to libcurl doesn't seem to be a problem.

**Closed** 2022-07-09 09:19 UTC
Labels: C: Manager, P: Minor, R: fixed, T: Defect
