### ISSUE TITLE
Offer a boinc version for Windows 11 on ARM processor

### ISSUE THREAD

**Issue by fckwan** [BOINC/boinc#5204] opened 2023-04-19 20:47 UTC
**Describe the problem**
There are windows 11 machines running on ARM processors.

**Describe the solution you'd like**
Please provide an BOINC for Windows 11 on arm processor.

**Additional context**
[https://boinc.berkeley.edu/download.php](url)
 There is only Windows 32 or 64 bit download of Boinc.

[https://github.com/BOINC/boinc/pull/4523](url)
The above issue seems to be related to this issue. But the build result is not available for download in the download page.

**Comment by AenBleidd** [comment] 2023-04-19 20:57
Closed as a duplicate of #4697

**Closed** 2023-04-19 20:57 UTC
Labels: R: duplicate, T: Task, C: Installer - Windows
