### ISSUE TITLE
LOC: Replace tab characters in menu items with the '\t' escape sequence

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1511] opened 2016-03-21 05:55 UTC
ISSUE:
Some of the localizers have replaced the '\t' escape sequence with the actual tab character thereby breaking things for some languages

KNOWN LANGUAGES:
grep ⇥ . -R

./locale/cs/BOINC-Manager.po:msgstr "&Disk⇥Ctrl+Shift+D"
./locale/cs/BOINC-Manager.po:msgstr "Možnosti záznamu událostí...⇥Ctrl+Shift+F"

./locale/fr/BOINC-Manager.po:msgstr "Options du Journal des événements...⇥Ctrl+Shift+F"
./locale/fr/BOINC-Manager.po:msgstr "Vue Avancée...⇥CTRL+SHIFT+A"

./locale/nl/BOINC-Manager.po:msgstr "&Disk⇥Ctrl+Shift+D"
./locale/nl/BOINC-Manager.po:msgstr "Logboek opties...⇥Ctrl+Shift+F"

**Comment by Ageless93** [comment] 2016-03-21 11:36
Now hold on, what should I do here?

Change &Disk⇥Ctrl+Shift+D to &Disk\tCtrl+Shift+D ??
Or change the places where there's an actual tab, like in "&Berichten
Ctrl+Shift+N" to "&Berichten⇥Ctrl+Shift+N" ??
Because if the latter, then these are broken in a lot more places (and not
done by me, btw, but I suspect by the previous translator.)

I've for now saved everything with the "⇥" sign.


-- Jord van der Elst.

**Comment by Ageless93** [comment] 2016-03-21 11:39
And the thing is, in the original English they all show with the '⇥' sign,
like &Disk⇥Ctrl+Shift+D, Trans&fers⇥Ctrl+Shift+X, Event Log...⇥Ctrl+Shift+E


-- Jord van der Elst.

**Comment by romw** [comment] 2016-03-21 14:58
What tool are you using to make modifications?

BOINC-Manager.pot shows this for the Disk menu item:
#: clientgui/AdvancedFrame.cpp:430
msgid "&Disk\tCtrl+Shift+D"
msgstr ""

**Comment by Ageless93** [comment] 2016-03-21 16:31
Using Transifex through my browser.
Log in, choose Dutch, choose BOINC Manager.pot, choose translate.
Search for CTRL
https://www.transifex.com/boinc/boinc/translate/#nl/manager/40473214?q=CTRL
(requires login, for those on the sideline)

All occurrences with CTRL are shown, with the English version first, the
translation next.
For English I see e.g. &Notices⇥Ctrl+Shift+N, and &Tasks⇥Ctrl+Shift+T
Mousing over the "⇥" character shows "TAB".

Before I edited these lines, there was a physical "TAB" between the Dutch
translation and the key combo, I changed that to exactly as is shown in the
English, by removing the "TAB" and adding the "⇥" character.
I figured, it makes no sense translating &Notices⇥Ctrl+Shift+N into
&Berichten\tCtrl+Shift+N, not when &Berichten⇥Ctrl+Shift+N makes more sense
as shouldn't we translate only the English word?

So if the English versions in Transifex show the wrong character already,
shouldn't you start with fixing that?


-- Jord van der Elst.

**Comment by romw** [comment] 2016-03-21 16:41
Sense for who?  wxWidgets expects to see '\t' and ignores the TAB.  So switching it back to '\t' will have the desired effect as far as the software is concerned.

I wonder if this is a 'Dutch' language bug with the Transifex software, the template as previously shown contains the '\t' escape sequence.

**Comment by Ageless93** [comment] 2016-03-21 16:48
Dear Rom,

How would you expect a translator of any language to know that instead of
the "⇥" character shown in the original text that they should translate to
their language, that they should rip out this "⇥" character and input \t
instead?
That sort of not making sense. For me, the translator.

And I still haven't had an answer, do you want me to change all "⇥"
character occurrences in the Dutch translation to \t?




-- Jord van der Elst.

**Comment by romw** [comment] 2016-03-21 16:53
Go ahead and replace the "⇥" character with \t

I'll go ahead and add some comments to the menu items for future reference.  I guess we have just been lucky in the past.

**Comment by ChristianBeer** [comment] 2016-03-21 16:55
The problem is that Transifex replaces the \t with "⇥" when it shows the original string. If you click "Copy source string" the \t gets copied as a TAB (seemingly blanks). If you select the original text yourself and copy and paste it into the textfield below you get the "⇥" character which is not the same as TAB or \t

So what you need to do is click "copy source string and then translate the words and shortcut letters but don't touch the space between the word and the Ctrl.

**Comment by ChristianBeer** [comment] 2016-03-21 17:01
> Go ahead and replace the "⇥" character with \t
Please don't enter this in Transifex. The "\t" gets escaped and is worthless again. You need to copy a real TAB from a text editor or via "Copy source string" (the little copy icon in the top right corner where the original string is shown in transifex.

**Comment by Ageless93** [comment] 2016-03-21 17:07
Trouble here is, I took over from the previous translator, and so a lot of
that was already translated. In these, they were all copied into place by
Rom, a year ago, bar one that I added 6 months ago.

I now also see how the big TAB comes into play.
I copy for instance "&Berichten" from the translation, then tell Transifex
to copy source string, which resets the Dutch string to the original
English with a small space between &Notices and the key combo. Just pasting
&Berichten in the place of &Notices now enlarges that space to a full tab.
Which is where we started from and what we apparently didn't want.

Unless I am now so confused that I don't know what you want anymore.
So no \t, although this whole thread says that should be done.
But no tab character either.
So then what? The full tab space between the word and the key combo, or the
small (single) space?


-- Jord van der Elst.

**Comment by Ageless93** [comment] 2016-03-21 17:18
Okay, so with images:
I copy the original source, as shown here: http://i.imgur.com/3GsN4Oz.jpg
It has a single small space.

I then write the Dutch translation in the place of "&Notices":
http://i.imgur.com/CIhitB4.jpg
As you can see, without me doing anything, the space has grown to Tab size.

When I save this translation it saves as http://i.imgur.com/M8aZrmF.jpg
That is with the "⇥" character that no one seems to want.

But it appears this is something Transifex does. I sure didn't do it.
So we don't want the "⇥" character, we don't want \t to be there, what do
we want and how do I add it to Transifex that it stays that way?


-- Jord van der Elst.

**Comment by ChristianBeer** [comment] 2016-03-21 17:20
There are three things that we all call tab but are different things. There is the invisible TAB you know from text editors (ASCII value 9). There is the tab character "⇥" which is Unicode U+21E5 and there is the escaped tab string "\t" that is used in C/C++ to use the TAB within strings. What transifex does is actually convert the first one (the invisible TAB) into the third one when you click save and display the second one to distinguish it from normal blank spaces.

We need the first one to be entered in Transifex so the third one get's written to the file.

What Jord describes in his message with pictures is exactly the way to do it!

**Comment by ChristianBeer** [comment] 2016-03-23 10:31
I updated the French and Czech strings in transifex too.
@romw From the two changes in each language only the first was committed to the repository although I waited a few seconds between the changes. Is it possible that the txgh bridge running on your server is rate limiting the commits?

**Comment by Ageless93** [comment] 2016-03-23 12:22
It would seem not all changes are seen as changes.
I updated all CTRL+SHIFT+* key combo's to the "Copy source text" then
change the English for the Dutch word.
So far only one made it over (
https://github.com/BOINC/boinc/commit/5edf64ce0bf8994f9ae187a1d31e6acc8f40271a),
the other 11 are now on the wrong '\t' that I set them to at an earlier
attempt after Rom told me to (
https://github.com/BOINC/boinc/commit/395afda780109fcc097c7a341623369ae5e4b461
)


-- Jord van der Elst.

**Comment by ChristianBeer** [comment] 2016-03-23 14:21
That happened to the German translation too when I tested this. I searched for another string that I could change and then all changes where transfered to github.

**Comment by ChristianBeer** [comment] 2016-03-31 07:14
@romw I deleted the last wrong string from the Czech translation and added it back so a new commit was triggered. Now the "⇥" is gone from the .po files but it is still in the .mo files which just need an update. I'll log a feature request with transifex so they don't accept the "⇥" character as a valid translation.

**Closed by ChristianBeer** 2016-03-31 07:14 UTC
Labels: C: Manager, E: 1 day, P: Blocker, T: Defect
