### ISSUE TITLE
Win7 freezes on shutdown if boinc is running

### ISSUE THREAD

**Issue by fede-boinc** [BOINC/boinc#2560] opened 2018-06-13 21:05 UTC
Hello, i'm here to report a problem with my pc and the BOINC program. After updating to the latest version of BOINC for windows 7 (should be 7.10.2, i'm using another pc right now), the pc is no more able to shut down properly. it start  to shut down but suddently the screen shows only the desktop background and the mouse pointer (it moves but there are no icons to click) and it remains in this state until the AC cable is unplugged. The ctrl-alt-canc or any other keyboard combination has no effect. It seems that he's waiting for something to quit but it never happens.
I can provide more details if it's needed.
Sorry for my basic English i hope that the problem is understandable, ask me if you need more details

**Comment by sunk818** [comment] 2018-06-13 21:31
I have latest version too and don't have this issue. I'm also on windows 7 64-bit. Maybe you can try uninstalling boinc, restart, then install again. If that still doesn't work, you might try deleting all the boinc folder in appdata? Then reinstall boinc

**Comment by Ageless93** [comment] 2018-06-13 21:52
Or instead of doing rigorous things as sunk818 opts for, why not stop BOINC manually before you shut down? 
Or why not [set Windows up to go into hibernation mode](https://www.howtogeek.com/howto/7564/how-to-manage-hibernate-mode-in-windows-7/) instead of shutdown? Then all data from memory - including BOINC and any other running programs - are written into a hibernation file on disk and read at the next time you restart Windows.

**Comment by sunk818** [comment] 2018-06-13 21:57
My point is that I don't have to stop boinc. Why does he have to stop it manually? Either the application or os is problematic. Your workaround is fine but be nice to address the actual problem.

You could also try as admin in command prompt 

Sfc /scannow

**Comment by Ageless93** [comment] 2018-06-13 22:14
You do know that uninstalling/reinstalling BOINC doesn't do much? That it merely removes the BOINC executables from the installation folder and upon reinstalling puts them back? 

When a Windows on shutdown hangs, it's usually caused by something not wanting to leave memory in a timely and nice enough fashion. Which can be boinc.exe or boincmgr.exe, but more likely is that it's any of the project's science applications. Or any library file, or anything else (like anti virus!). 

So in BOINC's case we'll need to know:
- which projects were running at the time of shutdown?
- which science applications specifically, if the project has more than one?
- CPU or GPU or both? 
- what does the BOINC log (from stdoutdae.txt in the data directory) say for the last moments there? 
- what did Windows Event Viewer say about it?
- What happens if he just waits? Sometimes Windows can be quite slow in shutting down, but eventually it will. Even if that takes an hour.
- What happens if he returns to 7.8.3 or whichever other version he ran before this?

**Comment by fede-boinc** [comment] 2018-06-15 17:12
Thanks a lot to all for the replies, i tried the sfc/scannow in the command prompt and the result was negative, no errors found.
i looked also at the boinc log and it seems that nothing stange was going on, her ethe last lines of the log 

> 15-Jun-2018 14:30:27 [---] Resuming GPU computation
15-Jun-2018 14:33:49 [---] Suspending GPU computation - computer is in use
15-Jun-2018 16:40:56 [climateprediction.net] Sending scheduler request: To fetch work.
15-Jun-2018 16:40:56 [climateprediction.net] Requesting new tasks for AMD/ATI GPU
15-Jun-2018 16:40:58 [climateprediction.net] Scheduler request failed: Couldn't connect to server
15-Jun-2018 16:40:59 [---] Project communication failed: attempting access to reference site
15-Jun-2018 16:41:01 [---] Internet access OK - project servers may be temporarily down.
15-Jun-2018 16:41:03 [LHC@home] Sending scheduler request: To fetch work.
15-Jun-2018 16:41:03 [LHC@home] Requesting new tasks for AMD/ATI GPU
15-Jun-2018 16:41:05 [LHC@home] Scheduler request completed: got 0 new tasks
15-Jun-2018 17:02:13 [---] Exiting

> 

from the windows event log i got some errors (21) in the last 24 hours, (i had a faile shutdown in the last 24 hours) but i have no idea to how to locate the (possible) guilty one.

The projects and elaboration that i am running are exactly the same from before the problem started to show off.

I could try to go back to a previous version of boinc, and if someone knows how to decript the windows event viewer then, jus say it :D

**Comment by fede-boinc** [comment] 2018-06-15 17:16
P.S. I have also tried to download again the installer of the new version and select the "repair installation" button, but i got no benefits from that

**Comment by sirzooro** [comment] 2018-07-05 07:44
Please check logs which were added after you started shutting down windows and before forced reboot. Please also check non-critical logs, some useful info may be there too.

**Comment by fede-boinc** [comment] 2018-07-05 08:33
Thanks to all, finally i’ve downgraded to the previous version (7.8.3) and the problem is disappeared!

**Comment by AenBleidd** [comment] 2018-09-20 15:03
Verified with BOINC 7.12.1 and Windows 7 Enterprise x64 6.1 build 7601 SP 1. Everything is fine.
@fede-boinc, ss it still an issue for you?

**Comment by fede-boinc** [comment] 2018-09-20 17:32
> 
> 
> Verified with BOINC 7.12.1 and Windows 7 Enterprise x64 6.1 build 7601 SP 1. Everything is fine.
> @fede-boinc, ss it still an issue for you?

Just installed the new version and everything works fine! thank you all

**Comment by AenBleidd** [comment] 2018-09-20 20:09
Sounds great. I close it.

**Closed by AenBleidd** 2018-09-20 20:09 UTC
Labels: C: Client - Daemon, P: Undetermined, R: worksforme
