### ISSUE TITLE
Flatpak version on flathub uses outdated Gnome runtime

### ISSUE THREAD

**Issue by HinzundKunz** [BOINC/boinc#5734] opened 2024-08-06 06:24 UTC
Info: org.gnome.Platform//44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   edu.berkeley.BOINC

**System Information**
Operating System: KDE neon 6.0
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.5.0-45-generic (64-bit)
Graphics Platform: Wayland
Processors: 6 × AMD Ryzen 5 4500U with Radeon Graphics
Memory: 15,0 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Acer
Product Name: Aspire A515-44G
System Version: V1.12

Boinc version 7.22.1
wxWidget version 3.2.2

**Additional context**

**Comment by AenBleidd** [comment] 2024-08-06 08:12
Closing as a duplicate of https://github.com/flathub/edu.berkeley.BOINC/issues/16

**Closed by AenBleidd** 2024-08-06 08:12 UTC
Labels: R: duplicate, T: Defect, C: Build System
