### ISSUE TITLE
Win: system tray puts wrong window on top

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#5741] opened 2024-08-08 21:36 UTC
When you hover over the BOINC system tray icon it shows 2 mini windows: Manager and Event Log.
If you click on one,  it opens both, with the wrong one on top.

**Comment by AenBleidd** [comment] 2024-08-08 21:48
Closing this as a duplicate of #1741 (yes, eventually we need to fix it).

**Closed by AenBleidd** 2024-08-08 21:48 UTC
Labels: C: Manager, R: duplicate, T: Defect
