### ISSUE TITLE
Bind tasks to cores that communicate to GPU

### ISSUE THREAD

**Issue by smoe** [BOINC/boinc#3973] opened 2020-08-15 16:24 UTC
**Describe the problem**

OpenCL NVidia apps hog on the CPU, keeping single cores 100% busy. These keep polling instead of being interrupt driven if I understood this right. But from having the same up run on an AMD card, I know that it only needs about 30% of CPU time, so having a single core supply two GPUs should be fine, also on NVidia. With multi-GPU setups (like former mining rigs) that gets mighty annoying as there is no core left to contribute to non-GPU projects / save the extra cores' energy / have the system more responsive.

I set the app_config such that a task is said to need a full GPU (it is a small GPU) but only half a CPU
```
<app_config>
    <app>
      <name>hsgamma_FGRPB1G</name>
         <gpu_versions>
            <gpu_usage>1</gpu_usage>
            <cpu_usage>0.5</cpu_usage>
         </gpu_versions>
   </app>
</app_config>
```
**Describe the solution you'd like**

The effect was that the same number of GPU jobs was started and additional four non-GPU jobs, but the GPU jobs kept occupying the full respective cores and the non-GPU jobs shared the core that was left. Somehow, the communication with the hardware was dominating. Preferred would be that by executing the task with `taskset` a specific core would be specified on which the job would be executed. The hardware-communicating and dominating tasks would then equally share the core and have an effective 50% CPU load.

**Comment by AenBleidd** [comment] 2020-08-15 17:07
Closed as a duplicate of #1282

**Closed by AenBleidd** 2020-08-15 17:07 UTC
Labels: R: duplicate

**Comment by RichardHaselgrove** [comment] 2020-08-15 17:10
And also refer to my #2949

**Comment by smoe** [comment] 2020-08-15 22:22
I agree that  #1282/#2949 should be addressed first and possibly allows also to fix this issue here ... or OpenCL has evolved on NVidia in the meantime.
