### ISSUE TITLE
"Notices" tab doesn't play nice with dark DE themes

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#1126] opened 2015-02-04 04:51 UTC
**Reported by sandro tosi on 24 Dec 41863987 05:25 UTC**
Hello,
the "Notices" tabs behaving badly on a dark desktop env theme. Attached you can
find a screenshot of what I mean, you can barely see the links, but text is
completely missed (black on black).

Regards,
Sandro

Migrated-From: http://boinc.berkeley.edu/trac/ticket/1153

**Comment by ChristianBeer** [comment] 2017-04-07 15:53
duplicate of #1072

**Closed by ChristianBeer** 2017-04-07 15:53 UTC
Labels: C: Manager, P: Undetermined, T: Defect
