### ISSUE TITLE
limit web RPCs to specific sources

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2526] opened 2018-05-20 22:22 UTC
AM -> project RPCs like create_account can be abused by spammers who,
for whatever reason, create millions of bogus accounts.

I propose that projects be able to have a list of acceptable sources of these RPCs
(e.g. a list of vetted AMs).
Each AM would have a PKE key pair.
RPC requests would include something encrypted with the private key.
Simplest thing would be to include the Unix time, both clear and encrypted.

**Comment by JuhaSointusalo** [comment] 2018-05-22 18:45
Duplicate of #2308

**Closed by JuhaSointusalo** 2018-05-22 18:45 UTC
Labels: C: Server - Other, Feature Request
