### ISSUE TITLE
Looks terrible on Adwaita-Dark GTK theme

### ISSUE THREAD

**Issue by TheTechRobo** [BOINC/boinc#4055] opened 2020-10-13 22:42 UTC
**Describe the bug**
Looks like absolute CRAP on "dark" GTK themes

**Steps To Reproduce**
1. Set GTK theme to Adwaita-Dark
2. Relaunch Boinc-Manager

**Expected behavior**
I expected it to look decent!

**Screenshots**

![image](https://user-images.githubusercontent.com/52163910/95923442-864cf780-0d83-11eb-80ef-b3664770a4d7.png)

![image](https://user-images.githubusercontent.com/52163910/95923480-96fd6d80-0d83-11eb-82c8-7baa72d7232f.png)

**System Information**
 - OS: Elive 3.8.14 (Debian Buster)
 - BOINC Version: 7.14.2 (the one in the repos)

**Additional context**
This might not count as a bug, but I wasn't sure whether to file this as a feature request or a bug

**Comment by AenBleidd** [comment] 2020-10-14 04:06
Closed as a duplicate of #3115

**Closed by AenBleidd** 2020-10-14 04:06 UTC
Labels: R: duplicate
