### ISSUE TITLE
Server compile error with FCGI and GCC 11

### ISSUE THREAD

**Issue by gchilders** [BOINC/boinc#5095] opened 2023-02-09 20:56 UTC
**Describe the bug**
I encounter the following error when trying to compile the server with GCC 11 and FCGI enabled. It compiles ok with GCC 10.

gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04)

  CXX      libboinc_fcgi_la-coproc.lo
In file included from /usr/include/features.h:486,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from /usr/include/fcgi_stdio.h:18,
                 from boinc_fcgi.h:19,
                 from coproc.cpp:22:
/usr/include/wchar.h:582:24: error: ‘malloc’ attribute argument 1 is ambiguous
  582 |   __attribute_malloc__ __attr_dealloc_fclose;
      |                        ^~~~~~~~~~~~~~~~~~~~~
/usr/include/wchar.h:582:24: note: use a cast to the expected type to disambiguate
make[2]: *** [Makefile:1808: libboinc_fcgi_la-coproc.lo] Error 1

**Steps To Reproduce**
1. ./configure --disable-client --disable-manager --enable-fcgi
2. make

**System Information**
 - OS: Ubuntu 22.04.1 LTS
 - BOINC Version: master

**Comment by AenBleidd** [comment] 2023-02-09 20:58
It is a known issue (#5042).
We're working on the fix.

**Comment by AenBleidd** [comment] 2023-02-09 20:59
Closed as a duplicate of #5042

**Closed by AenBleidd** 2023-02-09 20:59 UTC
Labels: P: Major, R: duplicate, C: Build System
