### ISSUE TITLE
Minimised Manager window opens after closing last other app on desktop

### ISSUE THREAD

**Issue by JuhaSointusalo** [BOINC/boinc#1556] opened 2016-06-08 19:03 UTC
From [forums](http://boinc.berkeley.edu/dev/forum_thread.php?id=10995):

After using the Boinc Manager I can click on the close or minimize button and the window seems to close.

On closing the last other than BOINC window on my desktop; BOINC Manager window will open by itself. This will happen multiple times, seemingly without end.

OS: Ubuntu 14.04.3 LTS

---

Upgraded to Ubuntu 16.04 LTS yesterday w/ kernel 4.4.0

Still having the same prob, only now the BOINC Manager opens after any other window is closed.

---

14.04: only Advanced View (?)
16.04: both Simple and Advanced Views (?)

Seems to be some weird interaction between Manager and Unity; can't repro on Mint 17 (=Ubuntu 14.04) running Cinnamon.

**Comment by simonbate** [comment] 2016-10-19 18:13
I didn't see this problem on 16.04, but recently upgraded to 16.10 and now it occurs all the time.

**Comment by Ageless93** [comment] 2017-10-24 17:23
Is this still a reproducible problem with BOINC 7.8 and any new Ubuntu?

**Comment by AenBleidd** [comment] 2018-10-02 14:06
Up

**Comment by ab1vl** [comment] 2018-10-31 13:33
10-31-18: With all the machination going on with Linux DE types these days IMHO it is virtually impossible to fix  bugs that come and go with distro releases. Moreover, Ubuntu is moving away from Unity so I'm not sure anytime spent on debugging BOINC on Unity is warranted now.   I can verify that I cannot reproduce this behavior on a fresh install of Lubuntu 18.04 x64 with BOINC Manager 7.12.0 (x64) wxWidgets 3.0.4.  Note that Lubuntu 18.04 marks the intro of LXQt, replacing LXDE packaged with 17.10  and earlier.   It even displays project graphics correctly however  BOINC slideshow does not work.  

I suggest closing this out and limiting testing to whichever distros and versions the linux package manager is willing to support and debug.

**Comment by AenBleidd** [comment] 2022-10-07 18:46
Closing this since there were a lot of updated of BOINC and there was no any additional error report last 4 years

**Closed by AenBleidd** 2022-10-07 18:46 UTC
Labels: C: Manager, P: Minor, R: worksforme, T: Defect, Validate

**Comment by ab1vl** [comment] 2022-10-07 18:56
Hey man, how are you these days? Hope the awful invasion has not hurt you
or loved ones.
My name is Chuck Yahrling and we used to interact back a few years ago.  I
gave up on trying to contribute to SETI  4 years ago.

I am retired and still geek around computers and single board
microprocessors now.  Play drums in a couple of bands too.

Wishing you all the best and praying for your safety!

Chuck
