### ISSUE TITLE
Build failure api/makefile.in not found / created

### ISSUE THREAD

**Issue by jamesdakon** [BOINC/boinc#4804] opened 2022-06-20 14:02 UTC
Upon merging version 7.17 with 7.21 we encountered a build error with the following error:

config.status: error: cannot find input file: `api/Makefile.in'
make: *** No targets specified and no makefile found.  Stop.

**Comment by AenBleidd** [comment] 2022-06-20 14:45
@jamesdakon, could you please provide exact steps to reproduce this?

Please follow this instruction to build BOINC software: https://boinc.berkeley.edu/trac/wiki/CompileClient

**Comment by RichardHaselgrove** [comment] 2022-06-20 14:52
Is 'Compile Client' right for the API? Shouldn't is be more like https://boinc.berkeley.edu/trac/wiki/BasicApi

**Comment by AenBleidd** [comment] 2022-06-20 15:02
@RichardHaselgrove, yes, the link is still correct because it describes the way to build boinc client (that by default also enables libraries that are essential when building application for BOINC).
Your link is mostly about the way of interacting with boinc library.

**Comment by talregev** [comment] 2022-06-20 19:10
Can you run this command and the output?
`./_autosetup`

**Comment by AenBleidd** [comment] 2022-06-21 12:27
@CyberTailor, @jamesdakon, could this happen because of old build tools?
From the log of @jamesdakon:
```
Checking version of 'make' >= 379... succeeded. (382)
Checking version of 'm4' >= 104... succeeded. (104)
Checking version of 'pkg-config' >= 15... succeeded. (27)
Checking version of 'autoreconf' >= 258... succeeded. (269)
Checking version of 'automake' >= 108... succeeded. (113)
Checking version of 'libtoolize' >= 105... succeeded. (204)
```
On my system it succeeds:
```
Checking version of 'make' >= 379... succeeded. (402)
Checking version of 'm4' >= 104... succeeded. (104)
Checking version of 'pkg-config' >= 15... succeeded. (29)
Checking version of 'autoreconf' >= 258... succeeded. (269)
Checking version of 'automake' >= 108... succeeded. (116)
Checking version of 'libtoolize' >= 105... succeeded. (204)
```

**Comment by talregev** [comment] 2022-06-21 12:35
Can you take master (version 7.21.0) and apply your changes and try again? (without git merge)

**Comment by AenBleidd** [comment] 2023-09-07 06:35
I'm unable to reproduce this, and also there was no any updates on this during last year.
Closing as 'works for me'

**Closed by AenBleidd** 2023-09-07 06:35 UTC
Labels: C: Client - Build, P: Undetermined, R: worksforme, T: Defect, E: to be determined, Validate
