### ISSUE TITLE
Text drawn white-on-white, can't be seen

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1412] opened 2015-10-20 04:15 UTC
We've had several reports of this, e.g.:

Hello, the Samsung Galaxy Note 4 N910F not work with their program it is only the lettering on white background as more does not happen.

It may depend on the theme (color scheme) used on the phone, or the Android version

**Comment by AenBleidd** [comment] 2015-10-22 23:16
I have such issue with BOINC version 7.4.37 on Android 4.0.3 on HTC Desire C. This is the last version of this app for my cell phone. Previous version had normal black text on white background. I hope this can help you to find the source of issue on the newest version of boinc app.

**Comment by AenBleidd** [comment] 2019-05-13 14:39
Couldn't reproduce this with latest development version. Need to be verified one more time once new version will be released

**Closed** 2019-10-02 19:24 UTC
Labels: C: Android - Manager, P: Critical, R: worksforme
