### ISSUE TITLE
Open BOINC Web... opens the Account Manager web page instead of the BOINC web page

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#770] opened 2015-02-04 02:13 UTC
**Reported by Luke1410 on 16 Jul 38937925 17:46 UTC**
Environment:
Windows Vista (Ultimate) 64-bit - SP1
BOINC 6.2.19

Reproduce:
1. Right-click on the BOINC icon in the Windows toolbar (next to the clock).
2. Choose "Open BOINC Web..."

Acutal Result:
My BOINC Manager's Webpage is opened in the browser (i.e. http://www.gridrepublic.org/)

Expected Result:
The BOINC webpage is opened (i.e. http://boinc.berkeley.edu/ )

In case that's working as designed, I'd suggest to:
1. rename the entry in the context menu (to something like: "Open [manager name here](insert) web page".
2. add another entry: "Open BOINC web page" which in all cases opens http://boinc.berkeley.edu/

Migrated-From: http://boinc.berkeley.edu/trac/ticket/793

**Comment by romw** [comment] 2015-02-04 19:12
**Commented by romw on 22 Feb 39155828 09:46 UTC**
Should be fixed in current releases.

**Comment by romw** [comment] 2015-02-04 19:12
**Commented by JacobKlein on 24 Jul 41331042 17:20 UTC**
This does not appear to be fixed.

Current behavior in 6.12.26: If not connected to an Account Manager, the "Open BOINC Web..." option isn't even listed when I right-click the tray icon. If connected to an Account Manager, the option is listed, and clicking the option takes me to the Account Manager's website.

Expected behavior: The "Open BOINC Web..." option should either always be on the tray right-click menu, or never be on it. Also, clicking it should always take you to http://boinc.berkeley.edu/ regardless of whether the Manager is using an Account Manager or not. If you feel the need to have a menu option for going to the Account Manager page, it should be a separate option.

**Comment by ChristianBeer** [comment] 2017-04-07 08:43
I could reproduce the issue with 7.6.33. The systray icon entry "Open BOINC Web ..." appears when an account manager is used and opens the account manager URL in a browser. It should be consistently labeld and/or shown.

**Comment by Ageless93** [comment] 2017-08-17 14:51
One for the present round of small fixes? What do you think, Vitalii?

**Comment by AenBleidd** [comment] 2017-08-17 14:55
@Ageless I'll take a look at it. I don't use Account Manager so I can't reproduce it right now but I'll take a look at it in any case

**Comment by Ageless93** [comment] 2017-08-17 15:17
Hi Vitalii,

Thanks. I don't think it's so much that it needs to be checked if it's
reproducible, it just needs the text "Open BOINC Web..." changed to "Open
Account Manager page..." or something similar.


-- Jord van der Elst.

**Comment by AenBleidd** [comment] 2017-09-04 02:02
Fixed via #1033 
Now it shows correct description so the issue is not reproducible now.

**Closed** 2017-09-05 07:39 UTC
Labels: C: Manager, E: 1 day, P: Major, T: Defect
