### ISSUE TITLE
When BOINC Manager is out of focus, clicking on Event Log will put BOINC Manager window in focus

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#3943] opened 2020-07-22 22:28 UTC
This is something that happens whenever I have both BOINC Manager and the Event Log open on the same monitor, with Event Log over BOINC Manager (so event log has focus). When I now switch temporarily to another program so that it has focus, and then switch back to the Event Log window, as soon as I click anywhere on the Event Log window the BOINC Manager window will always fetch focus and get in my way. 

I have a video of that here: https://photos.app.goo.gl/JzD5jYh34vRR1kTc9
I do expect that the event log window keeps focus as it is the window on the top. And I click on it, not on BOINC Manager. 

BOINC 7.16.7, Windows 10.

**Comment by AenBleidd** [comment] 2020-07-22 22:38
Closing as a duplicate of #1741

**Closed by AenBleidd** 2020-07-22 22:38 UTC
Labels: C: Manager, P: Minor, R: duplicate, E: to be determined
