### ISSUE TITLE
Move dependencies to github based repositories

### ISSUE THREAD

**Issue by TheAspens** [BOINC/boinc#2346] opened 2018-02-09 22:19 UTC
The dependencies for building the Windows client are hosted here: http://boinc.berkeley.edu/gitweb/

It isn't clear who has access to maintain them and I don't think that they need to be maintained somewhere different then where we maintain the source code for BOINC.

I propose that we move the following:
- http://boinc.berkeley.edu/git/boinc_depends_win_vs2010.git
- http://boinc.berkeley.edu/git/boinc_depends_win_vs2013.git

To:
- https://github.com/BOINC/boinc/boinc_depends_win_vs2010
- https://github.com/BOINC/boinc/boinc_depends_win_vs2010

We would then need to update the wiki pages:
  
- https://boinc.berkeley.edu/trac/wiki/CompileClient
- https://boinc.berkeley.edu/trac/wiki/SourceCodeGit#Windowsbuilddependencies

And the CI scripts.

Would there be anything else to update?

**Comment by JuhaSointusalo** [comment] 2018-02-09 22:31
The deps repos are too large to be hosted on GitHub without paying for it. IIRC it's both a few files and repo as a whole that are too large.

As for who can update them, there's the admin repo (which maybe shouldn't be visible, I don't know) and I see one knreed there :)

**Comment by adamradocz** [comment] 2018-02-10 10:53
Is it necessary to support a bunch of old VS? I think supporting only the latest stable version should be enough, and the dependency size would be much smaller.

**Comment by AenBleidd** [comment] 2018-02-10 11:36
Tye dependency size of one version (e.g. VS2013 x86) is big too because of
binary files. These fules must not be in git. I am thinking about the
solution to make a script that will downliad and build all necessary
dependencies.

Best regards,
Vitalii

Sent via Android

10 февр. 2018 г. 12:53 пользователь "Adam Radocz" <notifications@github.com>
написал:

**Comment by CharlieFenton** [comment] 2018-02-10 11:50
> I am thinking about the solution to make a script that will downliad and build all necessary dependencies.

This is how it is already done for Macintosh and Linux. I long ago wrote the scripts to build them on the Mac. @ChristianBeer and I adapted them for use by Travis CI, and he added the code to automatically download them from the Internet. You can find the relevant scripts for Macintosh in the GIT repository in the top-level directories _3rdParty_ and _mac_build_. In  particular, look at:
_3rdParty/buildMacDependencies.sh_
_mac_build/dependencyNames.sh_
_mac_build/setupForBOINC.sh_
_mac_build/build*.sh_
_mac_build/HowToBuildBOINC_XCode.rtf_

**Comment by AenBleidd** [comment] 2018-02-10 12:06
@CharlieFenton, thank you for this reference.

**Comment by ChristianBeer** [comment] 2018-02-11 09:05
I investigated moving the dependencies last year (can't find the mails exchanged at the time) but they were to big to transfer even to a free GIT LFS service. Storing the binary build artifacts in a git repository as a kind of cache seemed good a the time when you have your own git server. Now that we want to move away from that we  need to come up with a different way to store those big files.

An approach I see viable is to only store the build scripts in a git repository and upload the build artifacts to a free service where we can download them again. Much like the integrated cache in Travis-CI works. In general the archive the specified directory and upload it to AWS storage. The URL contains some kind of hash which they use to download the file again. If the file is not there the cache is treated empty. The scripts are kind of smart as they detect changes in the cache directory and update the file as needed at the end of a successful build.

As an exercise for the reader here is a list of deployment providers available in Travis-CI: https://docs.travis-ci.com/user/deployment/ and here for AppVeyor: https://www.appveyor.com/docs/deployment/ What we want to do is deploy the build artifacts of our depencies and use them in our own build.

**Comment by ChristianBeer** [comment] 2018-02-11 13:49
Looking at the list I posted earlier. None of the storage providers are free for open source projects. For all of them you have to pay for storage and traffic. Another alternative would be that a member of the BOINC developers community provides a place to store the build artifacts which allows uploads via FTP and downloads via HTTP. I don't know the traffic requirements.

**Comment by TheAspens** [comment] 2018-02-12 17:00
It doesn't sound like there is a clear better solution then the existing repositories (once we resolve the issues around managing access to update the repositories).

How hard would it be to script the building of the dependencies?  The scripts would make it easier to generate current versions of the dependencies and we could figure out how to give more people access to those repositories.  It might also eliminate the need to have the repositories at all if we decide people can just run the script to build the dependencies.  What does everyone think?

**Comment by AenBleidd** [comment] 2018-02-12 19:08
I can manage this. I think it is not hard. I can switch to this task
because it seems that my work on Android CI is bigger than I thought before.
If you want I can do this. I like the work like this.

Best regards,
Vitalii Koshura

2018-02-12 19:00 GMT+02:00 Kevin Reed <notifications@github.com>:

**Comment by JuhaSointusalo** [comment] 2018-02-13 21:47
I put my opinion in #2348 because I was actually looking at multiple related issues at once. In short, use vcpkg and to do that move to VS2017 and drop VS2010/2013.

**Comment by AenBleidd** [comment] 2018-02-13 22:28
I agree. We need to discuss this and decide how to do this in a best way.

Best regards,
Vitalii Koshura

2018-02-13 23:47 GMT+02:00 Juha Sointusalo <notifications@github.com>:

**Comment by CharlieFenton** [comment] 2018-02-17 04:00
Ideally, anyone should be able to check out a tagged repository from GIT and use its contents to build an exact duplicate of the binaries that were originally built and released with that version number. In order to do that, one must also use the same dependencies that were used for the original build. This includes not just the version number of each dependency but also all parameters used in building that dependency.

For the Mac, this is ensured because the build scripts for all dependencies are included in the GIT repository, and the Xcode project (also saved in the GIT repository) specifies the version number for each dependency it links with. There is also a text file _mac_build/HowToBuildBOINC_XCode.rtf_ which lists the required version numbers for its associated version of BOINC. And for more recent versions of BOINC,  there is a file _mac_build/dependencyNames.sh_ used by the Travis CI scripts but also human-readable giving the same information.

With the current system of saving the built dependencies in a separate repository, I don't know if the BOINC client and manager Visual Studio project  files enforce the use of the correct dependent library versions. In any case, if a new pre-built dependency library is created, it must not overwrite any earlier ones, to ensure that older BOINC builds can be replicated. And there needs to be some indication in the GIT repository of which version of the pre-built dependencies to use.

If we switch to a method where each person building BOINC also builds her own copy of the dependent libraries (as we do for Macintosh, and which I favor), then the scripts or other files for building the dependencies should be included in the same GIT repository as the other BOINC files in  a way that ensures consistent results no matter when a build is done from a particular GIT tag.

**Comment by TheAspens** [comment] 2018-02-23 22:25
I agree that this is related to the discussion in #2348 where the discussion talks about automating the builds of the dependencies.  Shall I close this issue in favor of that one or do we want to separate the issues?

As far as Charlie's comments go - it would be great if we could use a package manager or automated build tool that allows you to specify the version used in a configuration file of some sort (like maven, gradle, bower, etc).  That way the configuration file can be checked into git with the versions used at that point in time and then updated as appropriate.

**Comment by ras0219-msft** [comment] 2018-02-24 00:53
>That way the configuration file can be checked into git with the versions used at that point in time and then updated as appropriate.

A submodule reference to a particular commit in vcpkg is how we represent this. It also means you can completely hide the use of vcpkg inside your build script, if preferred (just run our bootstrap script and install the needed libraries). The BOINC org on GitHub can fork vcpkg if you need to make any local modifications / provide tags / etc.

**Comment by CharlieFenton** [comment] 2018-02-24 03:09
> It also means you can completely hide the use of vcpkg inside your build script, if preferred (just run our bootstrap script and install the needed libraries).

While I realize we are discussing MS Windows here, on the Macs which I use for both development and testing I consider it extremely important to keep the computer's configuration standard as it comes out of the box. So I _never_ install third-party libraries which might not also be on every BOINC user's system. This is to prevent the possibility that the BOINC software I build works on my computer but not on computers which don't have those third-party libraries installed.

For that reason, I oppose any solution that requires installing third-party libraries. Also, as I have written in comments to PR #2348:

> Another consideration is that to be truly open source, people should be able to build the client, manager and screensaver themselves.  

Requiring them to install additional their-party libraries or tools is an impediment to that goal.

**Comment by ras0219-msft** [comment] 2018-02-24 04:19
Sorry, I realize I was quite ambiguous with my post!

>I consider it extremely important to keep the computer's configuration standard as it comes out of the box.

We _completely_ agree -- Vcpkg is designed from the ground up to not require[1] any system-wide configuration or installation. When I said `install`, I meant you could use a pre-build step like:
```
>git clone https://github.com/BOINC/vcpkg --branch boinc-deps-v1.2
>vcpkg\bootstrap-vcpkg.bat
>vcpkg\vcpkg.exe install <dependencies>
```
The `install` command above downloads the source code from the upstream repo (such as GitHub) and builds it locally in the vcpkg folder using the current compiler. They don't get put into `C:\Program Files`.

If you static link, then distribution is pretty solved already. If you use shared linking, we can automatically copy any of the locally built DLL files that the application needs into your build's output folder, right next the executable file so it's immediately ready to run or zip/msi up for distribution.

[1] We do offer an optional user-wide setting which enables a "unix-like" `/usr/include` experience, but it is completely optional and not interesting for your use case.

**Comment by JuhaSointusalo** [comment] 2018-02-26 20:35
For a quick example of how Git submodules work check [SixTrack repository](https://github.com/SixTrack/SixTrack/tree/master/SixTrack). They have forked BOINC and libarchive to apply some patches to both. The forked repositories are included in SixTrack repository as submodules, both pointing to a specific commit in the forked repositories.

In our case we'd have something like 3rdparty/win/[vcpkg @ 71d44ce](https://github.com/Microsoft/vcpkg/tree/71d44cebdb85926bc00241fc08f0dcaaedb868d2). To find what zlib's build options were at that time you simply open [ports/zlib/portfile.cmake](https://github.com/Microsoft/vcpkg/blob/71d44cebdb85926bc00241fc08f0dcaaedb868d2/ports/zlib/portfile.cmake) from the vcpkg link.

Forking external repositories is not requirement for using submodules but I think that's what I'm going to do. This way I can make vcpkg built dependencies XP compatible out of the box. And then we can easily rollback library upgrades or apply patches of our own if we need to.

I haven't started working on this because it looks like 7.10 could use some bug fixing first. As for closing this issue, once I get around to opening a PR I'll add Closes #xyz everything related I can find that's still open.

**Comment by CharlieFenton** [comment] 2018-11-11 00:53
Since I had never heard of _GIT LFS_, I suspect others may also not be familiar with the term. Here is the explanation: https://blog.github.com/2015-04-08-announcing-git-large-file-storage-lfs/

I am not clear whether or not Adam is suggesting we use _GIT LFS_. Notice that it requires installing a GIT extension on your build system, which I feel is unacceptable. See my comment [here ](
https://github.com/BOINC/boinc/issues/2346#issuecomment-368194140) and reply from @ras0219-msft [here](
https://github.com/BOINC/boinc/issues/2346#issuecomment-368198552).

I still advocate for eliminating the pre-built dependencies on Windows and providing scripts to build them locally, as discussed earlier in this thread.

**Comment by AenBleidd** [comment] 2019-05-23 10:47
Closing this in favor of #2348

**Closed by AenBleidd** 2019-05-23 10:47 UTC
Labels: C: Client - Build, R: wontfix, T: Task, E: 1 day, C: Build System
