### ISSUE TITLE
[Simple View] Ubuntu 19.10 Empty Computing Preferences screen

### ISSUE THREAD

**Issue by CyberCyclone** [BOINC/boinc#3415] opened 2020-01-01 02:42 UTC
I've installed BOINC from the Software Package Manager and it runs / computes fine. The GUI theme however is pretty broken. The preferences page is 100% blank.

![Screenshot from 2020-01-01 12-39-14](https://user-images.githubusercontent.com/4373888/71637648-e9a5e700-2c93-11ea-82f4-c31191357e5f.png)

**Comment by AenBleidd** [comment] 2020-01-01 11:23
Looks like a duplicate of #3115

**Comment by CyberCyclone** [comment] 2020-01-02 22:36
I've turned off dark theme (using Adwaita default). Still an issue when viewing Computing Preferences screen:

![Screenshot from 2020-01-03 08-31-27](https://user-images.githubusercontent.com/4373888/71697397-9e124b00-2e03-11ea-9cc6-6c7721984079.png)

The home screen looks fine though:
![Screenshot from 2020-01-03 08-35-20](https://user-images.githubusercontent.com/4373888/71697529-fc3f2e00-2e03-11ea-9df6-32944e830a81.png)

**Comment by AenBleidd** [comment] 2020-01-03 09:43
Verified with 7.16.3 from the official package. This issue is happen when using Simple View only.
@CyberCyclone, try to switch to Advanced View, (View -> Advanced View). Everything should be fine

**Comment by CyberCyclone** [comment] 2020-01-03 10:28
Thanks @AenBleidd, that fixed it for me.

**Closed** 2022-10-07 16:30 UTC
Labels: C: Manager, P: Major, R: duplicate, T: Defect, E: to be determined, C: Manager - Simple View, Validate
