### ISSUE TITLE
Boinc Projects that use Virtualbox crash on Ubuntu 22.04.1 

### ISSUE THREAD

**Issue by grahjenk** [BOINC/boinc#4921] opened 2022-09-10 01:13 UTC
Boinc Rosetta@home tasks hang immediately and indefinitely with message: "Communication with VM Hypervisor failed".

8-CPU Boinc LHC@home fail after 12 seconds with message: "Computation error (8CPUs)".

**Steps To Reproduce**
1. Upgrade a Ubuntu 20.4.3 (Intel i7-4790) machine to Ubuntu 22.04.1
2. Observe that normal Virtualbox guests like FreeBSD, NetBSD and Alma Linux continue to behave as expected.
3. Observe behaviour as noted above for Boinc projects that use Virtualbox.

**System Information**
 - OS: Ubuntu 22.04.1 LTS
 - BOINC Version: 7.18.1+dfsg-4

**Additional context**
Also tried:  boinc-7.20.2+dfsg+202208252251~ubuntu22.10.1
And:  virtualbox 6.1.38 (from Ubuntu 22.04.1 "proposed" packages)

See also:
https://bugs.launchpad.net/ubuntu/+source/boinc/+bug/1986647

**Comment by Toby-Broom** [comment] 2022-09-10 09:35
it probably this, #3355

**Comment by grahjenk** [comment] 2022-09-11 10:05
Thanks Toby. I changed the ProtectSystem value in boinc-client.service to 'full' and that resolved the issue.

Then I found that the Ubuntu 20.04.3 version of that file differed only from the 22.04.1 version only in declaring 'PrivateTmp=true', so I've put that version in place instead, and it seems to be working.

Regards ..
________________________________

**Comment by AenBleidd** [comment] 2022-09-24 23:05
Closed as a duplicate of #3355

**Closed by AenBleidd** 2022-09-24 23:05 UTC
Labels: P: Undetermined, R: duplicate, T: Defect, C: Client - Linux
