### ISSUE TITLE
Android 9: BOINC doesn't autostart, killed in 15 min

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2771] opened 2018-10-20 05:05 UTC
user email:
On Android 9 Boinc is killed after 15 minutes. I think Android Doze kills the app. I've turned of battery optimization for Boinc, but it still happens. 

And Boinc doesn't autostart in Android 9.

**Comment by GennadyNL** [comment] 2018-10-21 20:41
The same issue is also reproducible with Android 8.1 (phone model: OnePlus 5T): the application is force stopped automatically somewhere between 5 and 60 minutes. Turning off the battery optimization indeed does not help. May be it has to do with Background Execution Limits (https://developer.android.com/about/versions/oreo/background) in Android 8 and 9. Hopefully you can fix it, such powerful phones are not contributing now.

**Comment by adamradocz** [comment] 2018-10-21 20:43
@GennadyNL did you try the methode described here #2549?

**Comment by GennadyNL** [comment] 2018-10-22 14:11
@adamradocz No, I do not see the similarities for now. My OnePlus 5T was processing 8 workunits simultaneously, using all 8 cores also according to the CPU Info tool.

**Comment by adamradocz** [comment] 2018-10-22 14:41
What if you lock the boinc in the app switcher?

![screenshot_20181022-163728_system_ui](https://user-images.githubusercontent.com/16503773/47298906-42eaa300-d619-11e8-9448-d750b673f6d7.png)

**Comment by GennadyNL** [comment] 2018-10-22 15:29
@adamradocz no difference, it gets killed

**Comment by truboxl** [comment] 2018-10-24 15:53
I think this is a regression from version 7.4.53

That version's autostart work correctly under Android 8.1 on my Nokia 5...

**Comment by AenBleidd** [comment] 2019-04-30 14:11
Closing this as a duplicate of #2467

**Closed by AenBleidd** 2019-04-30 14:11 UTC
Labels: C: Android - Manager, P: Major, R: duplicate, E: to be determined
