### ISSUE TITLE
Client: Add setting for max CPU time when the computer is in use and inactive 

### ISSUE THREAD

**Issue by racheldotey** [BOINC/boinc#4582] opened 2021-11-15 16:24 UTC
**Describe the problem**
My problem is that I want to give BOINC more of my CPU time, but I don't want to keep changing the settings. As an example, I want to set the app to use at most 50% of my CPU time when I am using the computer, and then use 100% when I am not using it. 

**Describe the solution you'd like**
Extend the BOINC client settings to allow me to set a percentage (or suspend as you have now) for when the computer is active, and a percentage for when the computer is inactive. 

**Additional context**
Yes I can just set it to 50% all the time, but that leaves a lot of processing power unused when I let it run all night.

**Comment by AenBleidd** [comment] 2021-11-15 16:37
Closing as a duplicate of #41

**Closed by AenBleidd** 2021-11-15 16:37 UTC
Labels: C: Client - Scheduler Policy, R: duplicate

**Comment by davidpanderson** [comment] 2021-11-16 09:10
See also #2993
