### ISSUE TITLE
Android BOINC 7.16.16 adding Einstein now requires username in all lower chars

### ISSUE THREAD

**Issue by Ageless93** [BOINC/boinc#4196] opened 2021-02-16 18:02 UTC
I was adding Einstein, but each time I gave my password BOINC would end with the message "There have been problems attaching scientific projects: Einstein: Could not connect."
Which is not very useful to tell me what went wrong. So I tested my password via the website, could log in fine there with that password. But in my account profile for Einstein my name shows as JORD (all caps). Changing my name in the app to all caps didn't work. Changing my name to jord in all lower case in the app did work. 

This is fundamentally different from the earlier #3765 where I reported that my name required to be in all caps. 
Adding World Community Grid requires my name again to be Jord with a capitalized J. It refused to add the project with jord, all lower case. This is something we cannot explain to people.

**Comment by RichardHaselgrove** [comment] 2021-02-19 14:11
Couldn't attach to World Community Grid, either - with lower case email address, and either lower or normal case user name.

New account, successfully added Linux (before Android) and Windows (after) clients. Other two OS show 'Terms of Use' before attaching, Android doesn't. Only line in Event Log (detail level 5) is

`Fetching configuration file from http://www.worldcommunitygrid.org/get_project_config.php`

Process:
Open 'attach' wizard
Select WCG
Read project information blurb
Click 'Continue'
**Separately**, select checkbox for project
Click 'Continue' on main wizard page
Supply email, username, password (NB - no question whether 'new' or 'returning' user)
Read hint 1 of 3, click continue
GUI reports

```
There have been problems connecting projects:
World Community Grid
Could not connect
```
Only controls on page are chevron against WCG project, 'Finish' button.
Clicked chevron, brought up name/password form - this time with buttons for 'Register' and 'Sign in'. Signed in, successful. Page header still says 'There have been problems...', but 'could not connect' line has cleared.

Soon after, got 'Welcome' notification from WCG.

**Comment by AenBleidd** [comment] 2021-04-24 18:16
Error looks not connected to the user name and should be fixed in #4343.
Closing this as invalid

**Closed by AenBleidd** 2021-04-24 18:16 UTC
Labels: C: Android - Manager, P: Blocker, R: invalid

**Comment by brevilo** [comment] 2021-04-26 11:37
FWIW, the issue title is misleading as a) the issue is mostly dealing with WCG and b) the "username" [isn't used at all](https://github.com/BOINC/boinc/issues/3765#issuecomment-633662239) to sign in a user at E@H.

**Comment by AenBleidd** [comment] 2021-04-26 11:38
Originally Einstein@home was a reason of this fix ;) WCG was added later. Sorry for misleading title.
