### ISSUE TITLE
Second Boinc client closing for no reason, no logs given.

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#5121] opened 2023-02-28 16:09 UTC
I have a machine with a perfectly working Boinc client.  It runs 24/7 for weeks on end just fine.

I added a second Boinc client by creating a folder "BOINC2" under ProgramData, then running

"c:\Program Files\BOINC\boinc.exe" --allow_multiple_clients --redirectio --detach_console --gui_rpc_port 31418 --dir C:\ProgramData\BOINC2

Sometimes it works for 2 days, sometimes 10 minutes, then suddenly the second boinc.exe is gone from the task manager.  The first instance never goes wrong.  I'm nowhere near out of RAM, it's about a third used (of 32GB) last time I checked.  The log files stdoutdae.txt and stderrdae.txt in the BOINC2 folder are never written to so I can't see what's wrong.  Those logs in the normal Boinc directory are updated fine.

**Comment by AenBleidd** [comment] 2023-02-28 18:49
I can't reproduce this. In my case everything works fine.
I'd suggest you to try next:
1. Run the same command but without `--redirectio --detach_console`.
This will allow you to see in the console window what is going on, probably already at this point you'll find a good error message.
2. Try to run with different folder (it might happen that for some reason BOINC has no permissions to access `C:\ProgramData` folder (that is odd but still could be).
3. When running new instance of BOINC, you should verify that the folder exists (in your case `C:\ProgramData\BOINC2` because by default BOINC client doesn't create this folder and just fails with the next error: `chdir: No such file or directory`
Most probably 3rd is your case, you just see no error anywhere because you forced BOINC client to redirect all output to the log file, that could not be created because there is no folder where BOINC can put this file.

**Comment by hucker75** [comment] 2023-03-01 14:37
I ran your shortened version from a command prompt and it lasted all night.  Trying various things, it seems to be a permissions problem.  It used to only be Linux with this nonsense, but Windows is doing it too.  I think running it from a command prompt automatically made it have admin rights (for some reason my command prompts are always admin), so I made sure Boinc was running with admin priveledges, and also made every single folder and file under the BOINC2 folder have full control for everyone.  Now it's happy.

**Comment by AenBleidd** [comment] 2023-03-01 15:18
>  I think running it from a command prompt automatically made it have admin rights (for some reason my command prompts are always admin),

It depends on your Windows settings. Even if you're admin, not always your command line is running with admin privileges.
if you want to be sure, you should search for `cmd`, and then from the context menu select 'Run as administrator'.

> Now it's happy (except still no logs - I even deleted the files in case it was having trouble overwriting them).

If you run shortened command without `--redirectio --detach_console`, log files won't be created, instead everything will be printed in the cmd window.

Do you have any errors when running with shortened command?

**Comment by hucker75** [comment] 2023-03-01 16:30
It's running ok now, but I changed a few things, so I don't know which helped.  I'm using the shortened command (without --redirectio --detach_console), I'm running it as an admin (from a shortcut placed in the windows start menu startup group, with the shortcut set to run as administrator), and I've set everything under the BOINC2 folder to have "full control" for "everyone".  It' fine like this, I control it from Boinctasks ion another machine anyway, and it's behaving like any other machine, I can see the log live in there.

**Comment by AenBleidd** [comment] 2023-03-01 16:32
@hucker75, your issue looks similar to #5009 
Could you please specify what Windows version do you run?

**Comment by hucker75** [comment] 2023-03-01 17:11
Windows 11, and I have the two updates mentioned in the other issue, KB5019980 and KB5020622

**Comment by AenBleidd** [comment] 2023-03-01 22:25
Ok, so looks like it's a duplicate of #5009.
I'm closing this issue in favor of the previous one, and I just raised the priority of it, 'cause it might be a release blocker for Win11

**Closed by AenBleidd** 2023-03-01 22:25 UTC
Labels: P: Undetermined, R: duplicate, T: Defect, C: Client - Windows, Validate
