### ISSUE TITLE
World Community Grid keeps override BOINC prefs

### ISSUE THREAD

**Issue by AndCycle** [BOINC/boinc#1777] opened 2017-02-01 05:23 UTC
I recently discover the global_prefs.xml been overwrite by BAM and WCG by turn,
BOINC can't decide which one to use, as it just take whatever any project says about prefs.

here is the thread
https://boincstats.com/en/forum/9/11379,1

```
01-Feb-2017 08:31:54 [World Community Grid] Starting task MCM1_0130025_1109_0
01-Feb-2017 08:31:56 [World Community Grid] Started upload of MCM1_0130019_3555_1_r295879939_0
01-Feb-2017 08:32:03 [World Community Grid] Finished upload of MCM1_0130019_3555_1_r295879939_0
01-Feb-2017 08:48:10 [---] Contacting account manager at https://bam.boincstats.com/
01-Feb-2017 08:48:14 [---] Account manager: BAM! User: 34887, AndCycle
01-Feb-2017 08:48:14 [---] Account manager: BAM! Host: 531829
01-Feb-2017 08:48:14 [---] Account manager: Number of BAM! connections for this host: 20485
01-Feb-2017 08:48:14 [---] Account manager contact succeeded
01-Feb-2017 08:48:14 [---] General prefs: from http://bam.boincstats.com/ (last modified 30-Jan-2017 05:07:35)
01-Feb-2017 08:48:14 [---] Host location: none
01-Feb-2017 08:48:14 [---] General prefs: using your defaults
01-Feb-2017 08:48:14 [---] Preferences:
01-Feb-2017 08:48:14 [---]    max memory usage when active: 19115.83MB
01-Feb-2017 08:48:14 [---]    max memory usage when idle: 28673.74MB
01-Feb-2017 08:48:14 [---]    max disk usage: 100.00GB
01-Feb-2017 08:48:14 [---]    suspend work if non-BOINC CPU load exceeds 50%
01-Feb-2017 08:48:14 [---]    (to change preferences, visit a project web site or select Preferences in the Manager)
01-Feb-2017 08:48:17 [rosetta@home] Sending scheduler request: To report completed tasks.
01-Feb-2017 08:48:17 [rosetta@home] Reporting 2 completed tasks
01-Feb-2017 08:48:17 [rosetta@home] Not requesting tasks: don't need
01-Feb-2017 08:48:20 [rosetta@home] Scheduler request completed
01-Feb-2017 08:48:20 [World Community Grid] General prefs: from World Community Grid (last modified 29-Jan-2017 23:46:07)
01-Feb-2017 08:48:20 [World Community Grid] Host location: none
01-Feb-2017 08:48:20 [World Community Grid] General prefs: using your defaults
01-Feb-2017 08:48:20 [---] Preferences:
01-Feb-2017 08:48:20 [---]    max memory usage when active: 15929.86MB
01-Feb-2017 08:48:20 [---]    max memory usage when idle: 23894.79MB
01-Feb-2017 08:48:20 [---]    max disk usage: 4.00GB
01-Feb-2017 08:48:20 [---]    don't use GPU while active
01-Feb-2017 08:48:20 [---]    suspend work if non-BOINC CPU load exceeds 50%
01-Feb-2017 08:48:20 [---]    (to change preferences, visit a project web site or select Preferences in the Manager)
01-Feb-2017 09:04:47 [World Community Grid] Computation for task MCM1_0130019_3295_0 finished
01-Feb-2017 09:04:47 [World Community Grid] Starting task MCM1_0130025_0848_1
01-Feb-2017 09:04:49 [World Community Grid] Started upload of MCM1_0130019_3295_0_r250803067_0
01-Feb-2017 09:04:56 [World Community Grid] Finished upload of MCM1_0130019_3295_0_r250803067_0
```

**Comment by AndCycle** [comment] 2017-02-01 05:40
https://github.com/BOINC/boinc/blob/d0b3a79a2c87aa00b33b767457c46e051af2b727/client/cs_scheduler.cpp#L681

this is the related part, I think BOINC blindly trust any global prefs as scheduler reply.

**Comment by ChristianBeer** [comment] 2017-02-01 07:56
The thing is that WCG shouldn't send global preferences in the first place if there are other preferences that are newer. So in addition to the Client change one needs to ask why WCG was refreshing the preferences and is sending them out even if there are newer preferences from BAM send to WCG. Keep in mind that the BAM settings are also send to WCG.

What is possible is that the preferences that are send to WCG are not valid XML and silently ignored by the server. That would explain why the new BAM settings are not saved on WCG.

Your fix to the Client looks fine but does not cover the root of the problem only the symptoms.

**Comment by AndCycle** [comment] 2017-02-01 09:05
thanks for the insight as I know nothing about how AM works,
gonna try to find someone on BAM to work this out.

**Comment by ChristianBeer** [comment] 2017-02-01 14:50
I sent an email to WCG and made them aware of this issue. Maybe they changed something recently.

**Comment by TheAspens** [comment] 2017-02-01 21:46
This sounds like a duplicate of this issue: https://github.com/BOINC/boinc/issues/1675

**Closed** 2017-02-02 10:40 UTC
