### ISSUE TITLE
When would be a version for Windows ARM64?

### ISSUE THREAD

**Issue by Corsair-63** [BOINC/boinc#4817] opened 2022-06-29 13:18 UTC
**Describe the problem**
I've seen many distributions of the cliente but still didn't see a version for windows ARM64.
working under emulation is not a good practice (e.g. x86 neither x64)

**Describe the solution you'd like**
Build a version for the afore mentioned o.s. and also compile projects apps for the same o.s.

**Additional context**

**Comment by AenBleidd** [comment] 2022-06-29 13:32
Hello @Corsair-63,

Thank you for your report.
BOINC for Windows on ARM64 is planned for the next major Release.
Please stay tuned for more updates.

Closing this ticket as a duplicate of #4697

**Closed by AenBleidd** 2022-06-29 13:32 UTC
Labels: P: Minor, R: duplicate, T: Task, C: Installer - Windows
