### ISSUE TITLE
Options>Computing preferences produces a blank square under simple view with Linux Manager.

### ISSUE THREAD

**Issue by Dave-catcher** [BOINC/boinc#5318] opened 2023-08-04 16:41 UTC
**Describe the bug**
Under simple view there is a blank square when one attempts to look at computing preferences. I have it happening with 7.23.0 under XUbuntu 23.04 built from source. At least two other users have the issue on BOINC forums one on both Debian and Ubuntu and another on Arch Linux, (BOINC 7.22.1) I only discovered it by going to simple view after reading the post in the forums as I always used the advanced view.

**Steps To Reproduce**
1. Go to simple view
2. Click on Options>Computing preferencs

**Expected behavior**
I expect to see the computing preferences dialogue with the new additions of both when computer is in use and when not in use sections.

**Screenshots**

**System Information**
 - OS: 
 - BOINC Version: 

**Additional context**

**Comment by AenBleidd** [comment] 2023-08-04 17:23
Closed as a duplicate of #4902

**Closed by AenBleidd** 2023-08-04 17:23 UTC
Labels: P: Major, R: duplicate, T: Defect, C: Manager - Simple View
