### ISSUE TITLE
Cannot close BOINC when in fullscreen

### ISSUE THREAD

**Issue by mhmdanas** [BOINC/boinc#4990] opened 2022-10-25 17:53 UTC
**Describe the bug**
Cannot close the BOINC Manager window when in fullscreen (at least on macOS, I don't know about other OS's). It works when BOINC isn't in fullscreen though.

**Steps To Reproduce**
1. Open BOINC Manager and press the fullscreen button (the green one at the top-left of the window)
2. Try to close the window (either by pressing the red X button at the top-left of the window or by pressing Command+W)
3. You will be switched to another window/app
4. Go back to see that BOINC is actually still open
5. Try to close the window again
6. This time, nothing happens, and you're not switched to another window/app

**Expected behavior**
BOINC manager should just be closed.

**System Information**
 - OS: macOS 12.6
 - BOINC Version: 7.20.2

**Comment by AenBleidd** [comment] 2022-10-25 18:32
@CharlieFenton, could you please check this?

**Comment by CharlieFenton** [comment] 2022-10-26 00:43
I can reproduce it, but I feel it is not worth the effort to try to fix it, for several reasons.
* There is a simple workaround ,which is to click on the green button first to take BOINC Manager out of full screen mode before pressing the red button.
* BOINC works in a nonstandard way: clicking the red button never actually quits BOINC Manager (even when not full screen), but merely hides it. This is true on all OS platforms, not just MacOS, because we want BOINC to keep running when the computer is not  in use. To completely quit BOINC Manager, you must select _Quit BOINC Manager_ from the BOINC Manager menu in the menubar, but that also causes the BOINC client to quit. (You can change that behavior on some platforms, but not on MacOS.)
* BOINC Manager uses only about 1/10 of 1 percent of one CPU, whether visible ("open") or not ("closed"). Thus, its impact is minimal.

**Comment by Vulpine05** [comment] 2022-10-26 01:33
I was just doing some research on a different topic, but I found something that may be relevant.  Check out the EnableFullScreenView function.  No bookmark for the direct function, but here is the one above it for convenience:  [https://docs.wxwidgets.org/trunk/classwx_top_level_window.html#a78a9441746702894fba7653c2d98cb8d](url)

It looks like the function was given some additional features in 3.1.6 of wxWidgets.

**Comment by AenBleidd** [comment] 2022-11-18 14:30
@CharlieFenton, I think we should close this as 'Won't fix'. What do you think?

**Comment by CharlieFenton** [comment] 2022-11-19 11:37
@AenBleidd I agree.

**Closed** 2022-11-19 11:38 UTC
Labels: C: Manager, P: Undetermined, T: Defect, Validate
