### ISSUE TITLE
Limit number of VirtualBox tasks

### ISSUE THREAD

**Issue by hucker75** [BOINC/boinc#4677] opened 2022-03-24 07:32 UTC
On AMD processors where the user's trying to interact with the machine, lots of VB tasks can make the interface very sluggish.  There's currently no way to limit this, apart from at project level.  But if I limit LHC to do only x VB tasks, and also Rosetta, if both happen to be running, I get double the VBs I want.  A global limit would be more useful, preferably with an option for number of tasks and number of cores to give more flexibility.

**Comment by computezrmle** [comment] 2022-03-24 11:27
@hucker75
Please provide more detailed information regarding
- computer's CPU, RAM
- the conditions when the computer starts getting sluggish:
  - how many/what kind of LHC tasks are running
  - how many Rosetta tasks are running
  - what else is running (BOINC/non BOINC)

@AenBleidd
Please replace the vboxwrapper label with the BOINC client label.
Each vboxwrapper instance controls 1 VM and doesn't no what else is running concurrently.

**Comment by hucker75** [comment] 2022-03-24 12:05
Ryzen 9 3900XT, with 64GB dual channel DDR4-3200.

I've noticed a slowdown with any combination of LHC's ATLAS/CMS/Theory, and Rosetta's Python.

More than 12 threads out of the CPU's 24 running a VB task makes a noticeable difference to the interface (Windows 11).

I limit Boinc to 18 threads in total, other things running in Boinc are Universe, etc, simple low demand tasks.

Nothing else demanding is running apart from ISpy - a security camera program which uses 2 cores, one per camera, but I don't think this is causing a problem as if there isn't enough CPU times available, it just drops the camera framerate.

**Comment by AenBleidd** [comment] 2022-03-26 15:43
Closing this as a duplicate of #1728

**Closed by AenBleidd** 2022-03-26 15:43 UTC
Labels: C: Client - Scheduler Policy, P: Major, R: duplicate, T: Enhancement, E: 1 month, C: Apps - VboxWrapper
