### ISSUE TITLE
[android] add custom url to account manager

### ISSUE THREAD

**Issue by SlieT** [BOINC/boinc#3491] opened 2020-03-04 16:35 UTC
**Describe the problem**
The problem to me is that i want to use GRCPool on android.
In general the problem is that i can not add a custom url to the account manager url list.

**Describe the solution you'd like**
Ether add the url https://www.grcpool.com/ (i think its the file values.xml - and maybe some more?)
or
implement a functionality that lets the user add a custom url by himself.

**Additional context**
Since teams of grcpool rank as the 2 most contributing participants i could imagine that this is relevant to more people.
https://boinc.berkeley.edu/chart_list.php

Best Regards

**Comment by AenBleidd** [comment] 2020-03-04 16:37
You need to switch to Beta channel on Play Store: https://support.google.com/googleplay/answer/7003180?hl=en
Then new version of Android application will be available that has this function.
But be aware that newer version is not stable enough as the old one

**Comment by AenBleidd** [comment] 2020-03-04 16:40
Duplicate of #1582

**Closed by AenBleidd** 2020-03-04 16:40 UTC
Labels: C: Android - Manager, R: duplicate

**Comment by SlieT** [comment] 2020-03-04 16:44
Thanks for the fast reply and not sure if i should keep responding to this issue here?

Yet, are there any plans/dates (the roadmap for 19 was updated early jan 20?) on a stable version hence release?

**Comment by AenBleidd** [comment] 2020-03-04 16:47
There are no particular dates and exact plans. I'm the only one developer now who works on Android part. Since it is not my main job (and actually not a job at all) I do stuff when it's possible.
My plan for next few months to stabilize Android client and let it run with no issues on latest Android OSs.

**Comment by SlieT** [comment] 2020-03-04 16:53
Wow i didn't knew that, much respect and big hearted thank you!

(i don't have much BATs but if you verify yourself ill send u some from time to time (:)

**Comment by AenBleidd** [comment] 2020-03-04 16:56
No, thank you. 😄 I don't work for money on this project

**Comment by AenBleidd** [comment] 2020-03-04 16:57
BTW, join our discord channel. You can find the invitation link here: https://github.com/BOINC/boinc

**Comment by SlieT** [comment] 2020-03-04 17:05
alright then, just unconditional internet love .)
thanks and see you there.
