### ISSUE TITLE
BOINC ownership or permissions are not set properly; please reinstall BOINC. (Error code 1202 at projects/virtualbox)

### ISSUE THREAD

**Issue by NenTech** [BOINC/boinc#5975] opened 2024-12-27 19:04 UTC
### Describe the bug

<img width="270" alt="Image" src="https://github.com/user-attachments/assets/ad5a2e23-f896-48c8-b433-fbe7c0d613f5" />

BOINC cannot be started after closing the application or rebooting your Mac.

The only way BOINC can be launched again is using the installer or deleting the '/Library/Application Support/BOINC Data/projects/virtualbox' folder.
With installation the folder gets removed an added again. BOINC starts without issues. When you exit the application immediately, the manager cannot be started again.

### Steps to reproduce

1. Install BOINC Manager (With virtual box installed)
2. Close application
3. Start BOINC Manager again

OR

1. Install BOINC Manager (With virtual box installed)
2. Reboot Mac

### Expected behavior

I expected to have BOINC Manager started without any errors.

### Screenshots

<img width="844" alt="Image" src="https://github.com/user-attachments/assets/935e60cd-bdae-4377-a37e-c1a106143d69" />

<img width="758" alt="Image" src="https://github.com/user-attachments/assets/d7ccf735-d86e-4102-9ec8-9fe175369d29" />

### System information

Fri 27 Dec 19:58:19 2024 |  | Starting BOINC client version 8.0.2 for x86_64-apple-darwin
Fri 27 Dec 19:58:19 2024 |  | log flags: file_xfer, sched_ops, task
Fri 27 Dec 19:58:19 2024 |  | Libraries: libcurl/7.79.1 SecureTransport zlib/1.2.12 c-ares/1.17.2
Fri 27 Dec 19:58:19 2024 |  | Data directory: /Library/Application Support/BOINC Data
Fri 27 Dec 19:58:20 2024 |  | OpenCL: AMD/ATI GPU 0: AMD Radeon Pro 5300M Compute Engine (driver version 1.2 (Dec  6 2024 18:15:14), device version OpenCL 1.2, 4080MB, 4080MB available, 152 GFLOPS peak)
Fri 27 Dec 19:58:20 2024 |  | OpenCL: Intel GPU 0: Intel(R) UHD Graphics 630 (driver version 1.2(Dec  6 2024 18:32:34), device version OpenCL 1.2, 1536MB, 1536MB available, 221 GFLOPS peak)
Fri 27 Dec 19:58:20 2024 |  | OpenCL CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (OpenCL driver vendor: Apple, driver version 1.1, device version OpenCL 1.2)
Fri 27 Dec 19:58:20 2024 |  | Host name: xxxxxx
Fri 27 Dec 19:58:20 2024 |  | Processor: 12 GenuineIntel Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz [x86 Family 6 Model 158 Stepping 10]
Fri 27 Dec 19:58:20 2024 |  | Processor features: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clfsh ds acpi mmx fxsr sse sse2 ss htt tm pbe pni pclmulqdq dtes64 mon dscpl vmx est tm2 ssse3 fma cx16 tpr pdcm sse4_1 sse4_2 x2apic movbe popcnt aes pcid xsave osxsave seglim64 tsctmr avx rdrand f16c
Fri 27 Dec 19:58:20 2024 |  | OS: Mac OS X 15.2 (Darwin 24.2.0)
Fri 27 Dec 19:58:20 2024 |  | Memory: 32.00 GB physical, 100.15 GB virtual
Fri 27 Dec 19:58:20 2024 |  | Disk: 465.63 GB total, 100.15 GB free
Fri 27 Dec 19:58:20 2024 |  | Local time is UTC +1 hours
Fri 27 Dec 19:58:20 2024 |  | VirtualBox version: 7.1.4r165100

### Additional context

On my Windows computer with the same versions installed, there is NO folder virtualbox in the ProgramData/BOINC folder at all. Special not in projects. Maybe this folder is located wrong on Mac OS?

This folder virtualbox on my Windows computer is in C:\Users\User_X\\.VirtualBox

As addition: Using the uninstaller does not give another effect. The folder virtualbox is added every time BOINC Manager is opened.

**Comment by AenBleidd** [comment] 2024-12-27 19:08
Closing this as a duplicate of #5910

**Closed** 2024-12-27 19:09 UTC
Labels: R: duplicate, OS: MacOs

**Comment by NenTech** [comment] 2024-12-27 19:13
> Closing this as a duplicate of [#5910](https://github.com/BOINC/boinc/issues/5910)

This is not the same issue. I only get the error of virtualbox and nothing else. The only problem here looks to me as the wrong location of the virtualbox folder.

**Comment by AenBleidd** [comment] 2024-12-27 19:15
@CharlieFenton, please take a look.
For me this is clearly the same issue.

**Comment by NenTech** [comment] 2024-12-27 19:20
As addition: Using the uninstaller does not give another effect. The folder virtualbox is added every time BOINC Manager is opened.

**Comment by NenTech** [comment] 2024-12-27 19:49
> [@CharlieFenton](https://github.com/CharlieFenton), please take a look. For me this is clearly the same issue.

I did some additional research. The folder is located wrong on macOS.
In Windows this folder is located in 'C:\Users\NenTech\.Virtualbox'
In macOS this folder is located: '/Library/Application Support/BOINC Data/projects/virtualbox'
I think this folder should be located in the user folder as well on macOS.

**Comment by davidpanderson** [comment] 2024-12-27 20:19
Old versions of vboxwrapper (erroneously) created projects/virtualbox
This was fixed in
https://github.com/BOINC/boinc/commit/46d69424620bd281c352c4846feaacd76852d381

**Comment by NenTech** [comment] 2024-12-27 20:57
> Old versions of vboxwrapper (erroneously) created projects/virtualbox This was fixed in [46d6942](https://github.com/BOINC/boinc/commit/46d69424620bd281c352c4846feaacd76852d381)

So if I understand it correctly, the project has to change the vboxwrapper on their server. (Or is there a way I can change it? Just copying in the project directory omits the error but the project is not doing anything anymore.)

**Comment by davidpanderson** [comment] 2024-12-27 21:17
The project has to use the new vboxwrapper.  Which project is this?

**Comment by NenTech** [comment] 2024-12-27 21:41
LHC@home. I already wrote on their message board.

**Comment by computezrmle** [comment] 2024-12-27 22:02
As for LHC@home there's nothing to worry about.
The project admins are aware and a bunch of fresh app versions are already on their ToDo list (after the Christmas holidays).

In the meantime, feel free not to run any tasks.
Due to other issues that have nothing to do with BOINC they don't have tasks for ATLAS and Theory while CMS doesn't send scientific jobs to the VMs anyway.
Best would be to check their message board in January.

**Comment by NenTech** [comment] 2025-01-19 12:26
> Old versions of vboxwrapper (erroneously) created projects/virtualbox This was fixed in [46d6942](https://github.com/BOINC/boinc/commit/46d69424620bd281c352c4846feaacd76852d381)

LHC updated the VBoxWrapper. Now the tasks are failing within 2 seconds:

`<core_client_version>8.0.2</core_client_version>
<![CDATA[
<message>
process exited with code 1 (0x1, -255)</message>
<stderr_txt>
2025-01-19 13:17:01 (1327): vboxwrapper version 26208
2025-01-19 13:17:01 (1327): BOINC client version: 8.0.2
2025-01-19 13:17:01 (1327): Detected: VirtualBox VboxManage Interface (Version: 7.1.4)
2025-01-19 13:17:01 (1327): Detected: Sandbox Configuration Enabled
2025-01-19 13:17:01 (1327): WARNING: Communication with VM Hypervisor failed.
2025-01-19 13:17:01 (1327): ERROR: VBoxManage list hostinfo failed
2025-01-19 13:17:01 (1327): called boinc_finish(1)

</stderr_txt>
]]>`

The user boinc_manager has no access to the ~/Library/VirtualBox folder...
