### ISSUE TITLE
Text clipped on macOS upon app launch

### ISSUE THREAD

**Issue by AustinConlon** [BOINC/boinc#3713] opened 2020-05-14 06:41 UTC
The bug goes away when I switch focus away from the window. Strangely enough, it also goes away when I take a screenshot, so I had to take a picture of my screen to show the issue.

- macOS 10.15.5 Beta (19F83c)
- BOINC Manager version 7.16.6
- wxWidgets version 3.1.0

![IMG_0601](https://user-images.githubusercontent.com/1305957/81901289-230c2e80-9573-11ea-864e-176ae095de8e.jpeg)

**Comment by CharlieFenton** [comment] 2020-05-14 10:16
Not only the text but also the popup menu above it have not been drawn. I can't reproduce this on OS 10.15.4.
> The bug goes away when I switch focus away from the window. Strangely enough, it also goes away when I take a screenshot,

I notice you are running a beta version of OS 10.15.5. This behavior makes me suspect this might be a refresh / drawing bug in the OS 10.15.5 beta.

**Comment by AustinConlon** [comment] 2020-05-15 06:51
Filed this in Feedback Assistant to Apple (FB7702325).

**Comment by AenBleidd** [comment] 2022-06-13 15:28
@AustinConlon, is this still an issue?

**Comment by AenBleidd** [comment] 2023-09-07 06:33
Since there was no any updates on this during last year, closing as 'works for me'.

**Closed by AenBleidd** 2023-09-07 06:33 UTC
Labels: C: Manager, P: Minor, R: worksforme, T: Defect, Newbie
