### ISSUE TITLE
Strange graphs in the Statistics tab

### ISSUE THREAD

**Issue by gskoczylas** [BOINC/boinc#4732] opened 2022-04-27 08:02 UTC
**Describe the bug**
I'm not sure if this is a bug in BOINC, but I've been using it for many years, and this is the first time I've seen such a strange graph in the “Statistics” tab. It is still April, and I see results on the charts as far away as December this year.

The clock on my laptop is automatically synchronised - it shows the correct date and time.

**Screenshots**
![image](https://user-images.githubusercontent.com/12671174/165469090-6b409600-8239-4005-a4d4-7c680c76c370.png)

![image](https://user-images.githubusercontent.com/12671174/165469591-ef93f5be-698a-49c1-8776-62307e9bfb58.png)

**System Information**
 - OS: Windows 10 Enterprise, 64-bit, version 20H2, build 19042.1645
 - BOINC Version:  7.16.20 (x64)

**Additional context**
I don't recall manually modifying the date on my computer in recent times.

**Comment by AenBleidd** [comment] 2022-04-27 08:18
@gskoczylas, thank you for the report.
Looks like you had some issues with current time on your device. It's hard to say when did this happen exactly.
To manually fix this, you should go to BOINCDATA directory (by default it's: C:\ProgramData\BOINC), open 'statistics_PROJECT_NAME.xml' file, search for a block of 'daily_statistics' with the biggest 'day' and remove that 'daily_statistics' block.

I'll keep this issue for a while in case this happens again so we could investigate more why this might happen.

**Comment by gskoczylas** [comment] 2022-04-27 11:11
I removed a few nodes from the XML files and now the graphs look much better.

![image](https://user-images.githubusercontent.com/12671174/165505724-75b95fe1-2024-45f3-91d8-5b1f5fb61740.png)

If such action is repeated, I will write about it here again.

**Comment by Ageless93** [comment] 2022-04-27 12:13
This is not a bug, but something that happens when your system (computer)
clock is off by several hours, days, weeks, months or years, BOINC contacts
the project and gets new info in on credits & RAC. When later the system
clock gets reset to the normal time and all's fixed, that weird line shows
up in the statistics.

**Comment by gskoczylas** [comment] 2022-04-27 19:34
This computer is used practically every day - at least for a while, usually for many hours a day. Almost every day it is turned off for a few hours - overnight.

I too first suspected some problem with the clock, but my clock is automatically synchronised with the standard time server, and I don't recall manipulating the clock recently. The programme cache is not large, so tasks wait no more than a few days to be fully processed.

All in all, this is not a problem. I reported this case just in case. In my opinion, you should always take into account the possibility that one of the latest updates has a bug. Anyway, I think that unless anyone else reports a similar problem, there may indeed have been some strange misrepresentation in this one case.

**Comment by talregev** [comment] 2022-05-21 05:30
Usually the clock is changing if you use dual boot with ubuntu and windows. Ubuntu use gmt+0 and Windows use your local time for example mine is gmt+2/3.  So there is couple hours different if both clocks show the correct time.

**Comment by AenBleidd** [comment] 2022-10-07 23:52
Closing this for now as 'wontfix' since this is not smth that should be fixed from the side of BOINC.

**Closed by AenBleidd** 2022-10-07 23:52 UTC
Labels: C: Client - Daemon, P: Trivial, R: wontfix, T: Defect, Validate
