### ISSUE TITLE
Throttling of multicore apps can cause synchronization errors

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#2796] opened 2018-11-04 21:58 UTC
Amicable Numbers reports that Win version of their multicore app occasionally (~0.1% of jobs)
produces wrong results when CPU throttling is used.

Their app does minimal synchronization; each thread computes, then
acquires a mutex while getting its next inputs.
It uses std::thread to make threads; I think the mutex is implemented as described here:
https://docs.microsoft.com/en-us/windows/desktop/sync/critical-section-objects

BOINC implements suspend/resume by enumerating all threads in the system,
then calling SuspendThread() or ResumeThread() on those belonging to the application;
see suspend_or_resume_threads() in lib/proc_control.cpp.
I guess this doesn't work correctly with the mutex.
My first thought was that throttling was resuming a thread suspended on the mutex,
but I'm not sure this is the case,
because SuspendThread() and ResumeThread() increment and decrement a "suspend counter",
so nested suspends should work correctly.

BTW this doesn't happen on Unix, where multicore apps fork and then use
signals to suspend/resume the child.

**Comment by AenBleidd** [comment] 2019-05-03 15:30
I think this could be closed as' Fixed'. It the issue is still there this ticket can be reopened.

**Closed by AenBleidd** 2019-05-03 15:30 UTC
Labels: C: Client - Daemon, C: Client - Windows, E: 1 day, P: Major, R: fixed, T: Defect
