### ISSUE TITLE
Error 1327: Invalid Drive - Error while Installing BOINC 6.4.5

### ISSUE THREAD

**Issue by romw** [BOINC/boinc#792] opened 2015-02-04 02:24 UTC
**Reported by SETI on 12 Jun 38996368 01:46 UTC**
'''System'''[Vista Enterprise (32-Bit)[[BR]([BR]]
Microsoft)]
Personal Files are in a network Folder (H:)[is reachable

'''How did I found this Issue?'''[[BR]([BR]]
H:)]
Install the Core Client from a local HDD[starting the install process I got the Message:[[BR]([BR]]
while)]
"Error 1327: Invalid Drive H:[[BR]]
[OK]"

see the BOINC_Screen1.png

Migrated-From: http://boinc.berkeley.edu/trac/ticket/815

**Comment by romw** [comment] 2015-02-04 19:35
**Commented by SETI@Home friend [on 25 Aug 38996378 22:13 UTC**
'''EDIT:[[BR](Founder])]'''
I tried to fix the problem by myself trying all hints on this page, but without success:[[BR]]
[http://consumerdocs.installshield.com/selfservice/viewContent.do?externalId=Q110636&sliceId=1]

**Comment by romw** [comment] 2015-02-04 19:35
**Commented by SETI@Home friend [on 3 Nov 38996464 09:46 UTC**
'''Effect'''[[BR](Founder])]
Installation stops.[[BR]]
----

**Comment by romw** [comment] 2015-02-04 19:36
**Commented by SETI@Home friend [on 19 May 38997011 11:06 UTC**
'''EDIT: ''Workaround'''''[[BR](Founder])]
Edit all entries in the registry:[Shell Folders" with Data on others than local Drives or %USERPROFILE%[[BR]([BR]]
"HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User)]
[installing BOINC you can reassign the old Data...
----

''Not nice but operational...''[[BR]([BR]]
after)]
More info PM or "skype:mh-consult"

**Comment by romw** [comment] 2015-02-04 19:36
**Commented by Richard Haselgrove on 21 Oct 39027896 18:13 UTC**
I have come across the same error 1327, and can extend the range of susceptible installations:

 * BOINC v6.2.19
 * Windows XP
 * Local drives (not network)

In my case, I had an earlier BOINC (v6.2.18) installed, with both program and data folders installed on drive D:

That disk started developing faults, so I recovered all available data, un-installed BOINC, and removed the drive for testing and RMA.

Trying to re-install BOINC on drive C: as a temporary measure, I got the error 1327 at the first Installshield 'computing space requirements' screen (as per [Founder]'s screendump), and it skipped immediately to an 'interrupted - run setup again - finish' screen - no remedial action possible.

My workround: !RegEdit to HKEY_LOCAL_MACHINE\SOFTWARE\Space Sciences Laboratory, U.C. Berkeley\BOINC Setup, and change all D: references to C: But you can't expect end users with failed drives to resort to !RegEdit.

Suggestion: assuming you can get network maps accepted as valid drives, trap error 1327 and revert to default installation paths. That would work for ordinary end users, and allow power users to re-select their bespoke paths from the currently-valid drive list.

**Comment by romw** [comment] 2015-02-04 19:36
**Commented by romw on 11 Apr 39159099 08:26 UTC**
Punting setup bugs to 6.10.

**Comment by romw** [comment] 2015-02-04 19:37
**Commented by SETI@Home friend [on 6 Feb 39475594 11:06 UTC**
Hi!

There is an another strange behavior when You try to install from a local drive under Win7...

There is already a BOINC Client (V6.6.31) installed, the message tab reports that there is a new Version. If you try to install you get the Message:
"Error 1327: Invalid Drive y:\
[OK](Founder])" 

The strange thing is, that i can't find a String "Y:" anywhere in my registry ???

Perhaps it help fixing the bug...

Bye! You do a great job!

**Comment by romw** [comment] 2015-02-04 19:37
**Commented by Richard Haselgrove on 5 Oct 39963392 16:53 UTC**
Replying to [romw](comment:7):
> Punting setup bugs to 6.10.
Although punted to 6.10, the same bug has just been reported for v6.10.18 and Windows 7. See

http://boinc.berkeley.edu/dev/forum_thread.php?id=4610

**Comment by romw** [comment] 2015-02-04 19:37
**Commented by romw on 4 Jun 40859063 10:40 UTC**
Setup bugs are being punted to a future release.  This work item should be completed with the new open source installer.

**Comment by romw** [comment] 2015-02-04 19:38
**Commented by Richard Haselgrove on 30 Nov 44536420 06:50 UTC**
Replying to [romw](comment:11):
A user has just re-reported the same problem as my comment #6 (local data drive failed) - with v7.2.42x64

**Comment by ChristianBeer** [comment] 2017-04-07 08:52
Needs to be evaluated if this still applies.

**Comment by Ageless93** [comment] 2017-04-07 09:53
I have just uninstalled BOINC from my system, moved the boinc_7.6.33_windows_x86_64.exe installer to my NAS (which in effect is a massive network drive), started the install from there. No problems. BOINC is installed and running. 

In then uninstalled BOINC again. Now mapped the folder the BOINC installer is in on my NAS as a network drive, started the installer from there and installed BOINC without problems. 

However, error 1327 indicates a problem with the mapped drive letter, as in it no longer existing. 

So I again uninstalled BOINC, then made a shortcut of the BOINC installer to my desktop, disconnected from the mapped network drive, and started the shortcut. It took a little while, but eventually the installer started and installed BOINC. 

Meaning that with the present 7.6.33 and Windows 7 64 bit I cannot reproduce this. 
Maybe it needs a reboot in between, but a backup process on my system prevents me from doing so at the moment (or the next 24 hours or so).

**Comment by Ageless93** [comment] 2017-08-17 14:53
Anyone else able to still reproduce the problem?

**Comment by Ageless93** [comment] 2017-10-24 14:02
Closing because no one answered. Assuming it's fixed.

**Closed by Ageless93** 2017-10-24 14:02 UTC
Labels: C: Installer - Windows, P: Major, T: Defect
