### ISSUE TITLE
Poor system responsiveness with VirtualBox and Hyper-threading

### ISSUE THREAD

**Issue by pschoefer** [BOINC/boinc#2297] opened 2018-01-11 20:33 UTC
Running VirtualBox tasks on more CPU cores than physically present (i.e., default behavior on hyper-threading enabled machines) causes the system to become considerably less responsive to user input.

I have experienced this myself running more than four single-threaded VirtualBox tasks on a (Windows) i7 machine with 4 physical (= 8 virtual) cores and made sure that this was neither due to insufficient RAM nor due to high disk usage. I have seen similar reports from other users, also with multi-threaded VirtualBox tasks.

I'm not sure whether it is a Windows-only issue or also happens on other OSs. Maybe things run more smoothly once #2273 is resolved. On the other hand, there is also a warning message if you try to manually create a VirtualBox with more cores than physically present, so there might be a more general problem with virtualization + hyper-threading.

**Comment by AenBleidd** [comment] 2019-05-02 22:50
Closed as a duplicate of #2542

**Closed by AenBleidd** 2019-05-02 22:50 UTC
Labels: C: Client - Daemon, P: Major, R: duplicate, E: to be determined
