### ISSUE TITLE
Some Android clients don't report CPU vendor or model

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1597] opened 2016-07-29 21:00 UTC
In the S@h database, some Android clients running 7.4.53 are reporting blank p_vendor and p_model.  Seems to be the case with all Android 7.0 and some Android 6.0.

This would cause these clients to not get jobs for HR apps.

**Comment by ChristianBeer** [comment] 2016-07-30 08:41
related to #1562

**Comment by brevilo** [comment] 2017-04-11 13:00
I can't reproduce that error using a build based on 6e8c453 (current master).

Tested:
* AOSP 6.0.1 (M4B30Z on `hammerhead`)

**Comment by JuhaSointusalo** [comment] 2018-10-20 14:41
The problem was that an arm64 version of the client was added to the Android package but that client didn't have code to get CPU vendor or model on arm64 devices. Since then that code was added to the client and now that we have a new Android package with new client this problem should be fixed (even if the new Android package has not yet reached release quality).

**Closed by JuhaSointusalo** 2018-10-20 14:41 UTC
Labels: C: Android - Manager, E: 1 day, P: Major, T: Defect
