### ISSUE TITLE
update BOINC Manager icon

### ISSUE THREAD

**Issue by chrstphrchvz** [BOINC/boinc#2468] opened 2018-04-13 20:01 UTC
The older "aero"/glossy icon is still used for the BOINC Manager icon. I really like the newer "flat" icon style. Here's a cropped-by-hand version of the logo to try to match the proportions of the old one (OK to use this if deemed "good enough", but I think working with the SVG will yield something slightly more accurate and maintainable):
![boinc_flat_cropped](https://user-images.githubusercontent.com/7941193/38755151-4956f8c8-3f2a-11e8-8343-3d1204dc57d1.png)

Here's a few mockups of what that would look like on recent macOS:
![boinc_tinyselect](https://user-images.githubusercontent.com/7941193/38755395-2e239e0c-3f2b-11e8-9fc7-8daeed3e3ce2.png)
![boinc_tiny](https://user-images.githubusercontent.com/7941193/38755396-2e368206-3f2b-11e8-8663-8b3d78145980.png)

![boinc_darkdock](https://user-images.githubusercontent.com/7941193/38755063-fb3e12ca-3f29-11e8-922d-0e2bb4ab6088.png)
![boinc_darkswitcher](https://user-images.githubusercontent.com/7941193/38755064-fb5259ec-3f29-11e8-81ac-d5a6bd497d65.png)
![boinc_lightdock](https://user-images.githubusercontent.com/7941193/38755065-fb6343c4-3f29-11e8-871e-0e70b084d403.png)
![boinc_lightswitcher](https://user-images.githubusercontent.com/7941193/38755066-fb738054-3f29-11e8-8a13-9d1f4a7151a6.png)

**Comment by chrstphrchvz** [comment] 2018-04-13 20:26
I now see where the newer icon is already in clientgui/res/templates/icons/…

So maybe the issue I'm seeing on macOS is that the BOINCMgr.icns file needs to be refreshed with the newer icon.

**Comment by CharlieFenton** [comment] 2018-04-13 23:53
This is a matter of taste. I personally strongly prefer the older style icons.

**Comment by adamradocz** [comment] 2018-04-14 07:27
I think the new is better.

**Comment by CharlieFenton** [comment] 2018-04-14 10:08
> I now see where the newer icon is already in clientgui/res/templates/icons/…

Actually, those files are artwork for the BOINC icon on MS Windows, though some of them could be used to create a _BOINCMgr.icns_ file for the Mac, (preferably with the addition of  512X512 and 1024X1024 renderings.) There are instructions for converting a set of PNG files to a single .icns file [here](http://applehelpwriter.com/2012/12/16/make-your-own-icns-icons-for-free/) and [here](https://stackoverflow.com/questions/12306223/how-to-manually-create-icns-files-using-iconutil), though you probably already know how to do this. You may need to have _Xcode_ installed to have the _iconutil_ utility;  I'm not sure.

By the way, I have been the Mac programmer for BOINC for many years, but have now retired. I've continued volunteering on a limited basis to keep BOINC working on the Mac, but am phasing out my  efforts. Would either of you like to get more directly involved in writing BOINC code for the Mac? As an open source project, BOINC has a number of people writing / maintaining code who are familiar with MS Windows, Linux and Android, but I seem to be the only person on the project familiar with Macintosh programming.

The areas where most of the Mac-specific code is needed are the BOINC Manager, the BOINC Mac installer and uninstaller and the screensaver. Over the years, BOINC has evolved into a somewhat complex project with quite a bit of code, so there is a significant learning curve to get familiar with all its details, but I am happy to answer questions and provide guidance to a new set of Mac BOINC programmers. BOINC sure could use the help.

**Comment by truboxl** [comment] 2020-05-22 12:31
I thought this is macOS related issue?

**Comment by AenBleidd** [comment] 2020-05-22 12:33
@truboxl, you're right. I closed this by mistake

**Comment by talregev** [comment] 2020-05-22 14:29
@AenBleidd 
You can take the svg icon I create it and add to mac version.

**Comment by AenBleidd** [comment] 2020-05-22 20:17
@talregev, the problem is that I have no Mac to do this :)

**Comment by talregev** [comment] 2020-05-22 20:26
@AenBleidd How you release binary for mac without mac?

**Comment by AenBleidd** [comment] 2020-05-22 20:34
I'm not release manager of BOINC for Mac :)

**Comment by CharlieFenton** [comment] 2020-05-22 23:50
I strongly prefer the current Mac icons. There is no reason to change them other than personal taste.

**Comment by davidpanderson** [comment] 2020-05-23 06:34
Agree w/ Charlie.

**Comment by AenBleidd** [comment] 2020-05-23 08:14
Closing this for now. If there will be any requirements change from Apple or any global redesign happen on BOINC, this issue could be reopened.

**Closed by AenBleidd** 2020-05-23 08:14 UTC
Labels: C: Manager, C: Undetermined, E: to be determined

**Comment by talregev** [comment] 2020-05-23 09:17
@davidpanderson @AenBleidd @CharlieFenton
There is a two strong reason why to switch to new svg icon:
1. It will be visual great without any blur at any size of screen.
2. Unify all the client Icons to new svg icon.

Why you don't convert the old icon to be svg?
Because all icon here is png. Convert from png to vector icon (svg) it hard task.
Take the old icon and convert it to svg it hard if not impossible task.
I already have technical issue to convert other flat simple icon.
The new svg icon created from this png, because this icon is very simple.

So it not just matter of personal taste.

**Comment by AenBleidd** [comment] 2020-05-23 09:33
@talregev, as far as I know, existing icon still looks fine. And by default, Mac applications doesn't use svg icon. So there is no real need to do such replacement

**Comment by talregev** [comment] 2020-05-23 10:05
You will have different icon for each client.

**Comment by CharlieFenton** [comment] 2020-05-23 10:41
> You will have different icon for each client.

As BOINC has had since 2002.

I'm not certain, but from the documentation I've found, I believe Mac application icons must be *.png files. I do know that a collection of *.png files (at different sizes) is then converted into a single Mac-specific *.icns file using a development tool supplied by Apple. Of course, there are third-party utilities to convert *.svg files to *.png.

I don't know if MS Windows can use *.svg files as application icons.

**Comment by CharlieFenton** [comment] 2020-05-23 10:48
You can see the current Mac icon [in this Wikipedia article](https://en.wikipedia.org/wiki/Berkeley_Open_Infrastructure_for_Network_Computing).

**Comment by RichardHaselgrove** [comment] 2020-05-23 10:50
https://docs.microsoft.com/en-us/windows/win32/menurc/icon-resource says that a Windows icon resource has to be a bitmap. The icon file itself contains multiple bitmaps for use at different resolutions and in different situations.

**Comment by talregev** [comment] 2020-05-23 11:01
@CharlieFenton
It very easy programmability to create a png from svg dynamically while the program running.
I don't think that it the issue.
I think the moderst here really want the old icon for Mac.

**Comment by RichardHaselgrove** [comment] 2020-05-23 11:08
Icons are displayed by the operating system when the program is **not** running. Dynamic doesn't come into it.

**Comment by talregev** [comment] 2020-05-23 11:10
I can create any size of icon in png from svg, for a simple clicks in inkscape. It not the issue here.
