### ISSUE TITLE
My Boinc Manager freeze up when adding project

### ISSUE THREAD

**Issue by ManAtWork** [BOINC/boinc#4831] opened 2022-07-07 18:15 UTC
**Describe the bug**
The Bonic Manager freezes up completely when I log on my account in adding the project

**Steps To Reproduce**
1.  After receiving the notice in Bonic Manager, it requires us to change the URL of World Community Grid project to https://master.worldcommunitygrid.org. I tried to use Add Project with this new URL under World Community Grid project.
2. After that, Bonic Manager connected to the project successfully and asked me to create new account or choose to log on with an existing account
3. When I attempt to input my email address to log on the account, the Bonic Manager freezes up completely. I cannot even input anything or go to the previous page. It locked up. I have to use Task Manager to shut it down.

**Expected behavior**
In general, I can input my email address and password to log on my World Community Grid account.

**Screenshots**
<img width="459" alt="image" src="https://user-images.githubusercontent.com/816289/177841084-a21780c0-a41d-433f-8255-9432b8cb24a8.png">
<img width="471" alt="image" src="https://user-images.githubusercontent.com/816289/177841489-73473c71-92fb-467e-ad2a-0c048689977e.png">

**System Information**
 - OS: Windows 10 Professional (version 21H2)
 - BOINC Version: 7.16.11 (x64)

**Additional context**

**Comment by RichardHaselgrove** [comment] 2022-07-07 18:25
What keyboard input language are you using? If non-english, please switch to english and try again. I think this occurs with non-roman script languages.

**Comment by AenBleidd** [comment] 2022-08-09 21:18
This should be already fixed in BOINC 7.20.2.

Closed as a duplicate of #4014

**Closed by AenBleidd** 2022-08-09 21:18 UTC
Labels: R: duplicate
