### ISSUE TITLE
make Boinc sensitive to cpu temperature

### ISSUE THREAD

**Issue by hpvpp** [BOINC/boinc#1591] opened 2016-07-27 00:46 UTC
On installation, find out about the maximum cpu temperature and set that as the default maximum temperature above which Boinc is suspended.
Allow the user to modify that temperature (down).

**Comment by ChristianBeer** [comment] 2016-07-27 08:28
This gets asked from time to time in the forums too. Getting the maximum temperature allowed by the Chip vendor is not possible I think. But getting the current CPU temperature is possible. At least for Linux we could use the libsensors library from [lm-sensors](http://www.lm-sensors.org/) (Website seems to be down right now). This is also part of major distributions. On windows it seems to be possible to query this information via the WMI interface. See this [SO question](http://stackoverflow.com/questions/23314886/get-cpu-temperature). But if the motherboard driver does not have the information we can't do anything about it.

**Comment by hpvpp** [comment] 2016-08-04 00:08
Okay, but we can find the maximum temperature ourselves so why not give us the option to then set it for Boinc?

**Comment by ChristianBeer** [comment] 2017-04-12 09:16
duplicate of #1378

**Closed by ChristianBeer** 2017-04-12 09:16 UTC
Labels: C: Client - Scheduler Policy, Feature Request, E: 1 month
