### ISSUE TITLE
BOINC doesn't work on Android 5.1.1

### ISSUE THREAD

**Issue by davidpanderson** [BOINC/boinc#1473] opened 2016-01-22 06:21 UTC
Hi Boinc Team After updating to android 5.1.1 on my Samsung Galaxy Note 4 I experience some Problems running your App.

It stops after a while without warning. I also set the Boinc app to start automatically that does not work either.

**Comment by Aselox** [comment] 2016-01-23 16:38
Same issue here with Note 3 (Note5 5.1.1 rom). It could have to do with Samsung's modified ART runtime. If anyone can test on Android 5.1.1 from other manufacturers, it could help focusing this issue in the right direction.

**Comment by exzoo** [comment] 2016-02-01 10:34
micromax q415 - doesnt work seti@home, einstein@home, worldcommunitygrid@home. Hes are on qualcomm snapdragon 200 and android 5.1.1

**Comment by PastorZ** [comment] 2016-03-09 14:31
I also have problems running BOINC with World Community Grid ever since updating to Lollipop. In order to get BOINC to run I have to open the app on the cell phone and then turn off the screen, otherwise it won't run even if the phone is fully charged.

**Comment by Niko13** [comment] 2016-07-15 10:16
Same issue here.
Version 7.4 .53 doesn't get Workunits for Seti@Home on my Huawei ALE-L21 with Android-Version 5.0.1, Patch-Level 1.2.2016. Last Versions before works already fine.

**Comment by brevilo** [comment] 2017-04-11 12:49
I can't reproduce that error on AOSP 5.1.1 using a build based on 6e8c45346 (current `master`).

**Comment by AenBleidd** [comment] 2019-04-30 14:09
Closing this in favor of #2467 as it has the same issues described

**Closed by AenBleidd** 2019-04-30 14:09 UTC
Labels: C: Android - Manager, P: Major, T: Defect
