### ISSUE TITLE
Email address remains even after clean installation.

### ISSUE THREAD

**Issue by Vulpine05** [BOINC/boinc#5234] opened 2023-05-13 03:10 UTC
**Describe the bug**
I was testing a clean install and uninstall for 7.22.1, and when I went to add a project after the clean installation, the email address I had been using for my previous installation was automatically filled in.

**Steps To Reproduce**
Literally copying the first three steps from the BOINC alpha testing for Clean Install and Uninstall:
1. Rename the BOINC data directory to a temporary directory name.
2. Uninstall BOINC.
3. Install new BOINC.
4. Tools->Add Project, then select any project and click Next.
5. Under the "Email address" field, my email address is present.  It doesn't matter if either radio button is selected.

**Expected behavior**
With a clean installation, I wouldn't expect any email address filled in until at least one project has successfully been added.

**System Information**
 - OS: Windows 10
 - BOINC Version: 7.22.1, but I know I have seen this in previous versions.

**Additional context**
I didn't check to see if cleaning the registry would fix this issue.  I am assuming that is where the problem originates from.

**Comment by davidpanderson** [comment] 2023-05-13 03:43
This is indeed kept in the registry, namely
HKEY_CURRENT_USER
SOFTWARE
Space Science Laboratory, U.C. Berkeley
BOINC Manager
Wizards
DefaultEmailAddress

I suppose uninstall should delete this

**Comment by AenBleidd** [comment] 2023-05-13 10:41
I believe this should be optional (as well as cleaning BOINC Data directory) and disabled by default.

For the next release I plan to work on the new installer, so I'll put this feature to the scope with other festures.

**Comment by Vulpine05** [comment] 2023-05-13 13:48
> I believe this should be optional (as well as cleaning BOINC Data directory) and disabled by default.

I agree, now that you mention it. Thank you!

**Comment by AenBleidd** [comment] 2023-05-13 18:47
Closing this as a duplicate of #675

**Closed by AenBleidd** 2023-05-13 18:47 UTC
Labels: P: Minor, R: duplicate, T: Task, C: Installer - Windows
